// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountBalance = "AccountBalances"

// AccountBalance mapped from table <AccountBalances>
type AccountBalance struct {
	ID        int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	AccountID int32     `gorm:"column:AccountId;not null" json:"AccountId"`
	Date      time.Time `gorm:"column:Date;not null" json:"Date"`
	Balance   float64   `gorm:"column:Balance;not null;default:0.00" json:"Balance"`
}

// TableName AccountBalance's table name
func (*AccountBalance) TableName() string {
	return TableNameAccountBalance
}
