// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountBudget = "AccountBudgets"

// AccountBudget mapped from table <AccountBudgets>
type AccountBudget struct {
	AccountBudgetID int32   `gorm:"column:AccountBudgetId;primaryKey;autoIncrement:true" json:"AccountBudgetId"`
	AccountID       int32   `gorm:"column:AccountId;not null" json:"AccountId"`
	FiscalYear      int32   `gorm:"column:FiscalYear;not null" json:"FiscalYear"`
	July            float64 `gorm:"column:July;not null" json:"July"`
	August          float64 `gorm:"column:August;not null" json:"August"`
	September       float64 `gorm:"column:September;not null" json:"September"`
	October         float64 `gorm:"column:October;not null" json:"October"`
	November        float64 `gorm:"column:November;not null" json:"November"`
	December        float64 `gorm:"column:December;not null" json:"December"`
	January         float64 `gorm:"column:January;not null" json:"January"`
	February        float64 `gorm:"column:February;not null" json:"February"`
	March           float64 `gorm:"column:March;not null" json:"March"`
	April           float64 `gorm:"column:April;not null" json:"April"`
	May             float64 `gorm:"column:May;not null" json:"May"`
	June            float64 `gorm:"column:June;not null" json:"June"`
	Memo            string  `gorm:"column:Memo;not null" json:"Memo"`
}

// TableName AccountBudget's table name
func (*AccountBudget) TableName() string {
	return TableNameAccountBudget
}
