// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountBankSetting = "AccountBankSettings"

// AccountBankSetting mapped from table <AccountBankSettings>
type AccountBankSetting struct {
	AccountBankSettingID   int32     `gorm:"column:AccountBankSettingId;primaryKey;autoIncrement:true" json:"AccountBankSettingId"`
	RowID                  int32     `gorm:"column:RowId;not null" json:"RowId"`
	AccountID              int32     `gorm:"column:AccountId;not null" json:"AccountId"`
	NextChequeNo           string    `gorm:"column:NextChequeNo;not null" json:"NextChequeNo"`
	StatementFrequency     string    `gorm:"column:StatementFrequency;not null" json:"StatementFrequency"`
	LastReconciliationDate time.Time `gorm:"column:LastReconciliationDate" json:"LastReconciliationDate"`
	ClosingBalance         float64   `gorm:"column:ClosingBalance;not null" json:"ClosingBalance"`
	BankID                 int32     `gorm:"column:BankId" json:"BankId"`
	AccountNo              string    `gorm:"column:AccountNo;not null" json:"AccountNo"`
	UserNo                 string    `gorm:"column:UserNo;not null" json:"UserNo"`
	UserName               string    `gorm:"column:UserName;not null" json:"UserName"`
}

// TableName AccountBankSetting's table name
func (*AccountBankSetting) TableName() string {
	return TableNameAccountBankSetting
}
