// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccount = "Accounts"

// Account mapped from table <Accounts>
type Account struct {
	AccountID          int32   `gorm:"column:AccountId;primaryKey;autoIncrement:true" json:"AccountId"`
	Code               string  `gorm:"column:Code;not null" json:"Code"`
	Description        string  `gorm:"column:Description;not null" json:"Description"`
	CreditDebit        string  `gorm:"column:CreditDebit;not null" json:"CreditDebit"`
	Type               string  `gorm:"column:Type;not null" json:"Type"`
	OpeningBalance     float64 `gorm:"column:OpeningBalance;not null" json:"OpeningBalance"`
	ClosingBalance     float64 `gorm:"column:ClosingBalance;not null" json:"ClosingBalance"`
	Classification     string  `gorm:"column:Classification;not null" json:"Classification"`
	DefaultGSTType     string  `gorm:"column:DefaultGSTType" json:"DefaultGSTType"`
	DivisionID         int32   `gorm:"column:DivisionId" json:"DivisionId"`
	ParentID           int32   `gorm:"column:ParentId" json:"ParentId"`
	CashFlowActivityID int32   `gorm:"column:CashFlowActivityId;not null" json:"CashFlowActivityId"`
	EraID              int32   `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion        int32   `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
