// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountSetting = "AccountSettings"

// AccountSetting mapped from table <AccountSettings>
type AccountSetting struct {
	AccountSettingID                  int32   `gorm:"column:AccountSettingId;primaryKey" json:"AccountSettingId"`
	EnableDivisions                   bool    `gorm:"column:EnableDivisions;not null" json:"EnableDivisions"`
	AccountFormat                     string  `gorm:"column:AccountFormat;not null" json:"AccountFormat"`
	EnableDivisionsOtherIncome        bool    `gorm:"column:EnableDivisionsOtherIncome;not null" json:"EnableDivisionsOtherIncome"`
	EnableDivisionsOtherExpenses      bool    `gorm:"column:EnableDivisionsOtherExpenses;not null" json:"EnableDivisionsOtherExpenses"`
	DivisionID                        int32   `gorm:"column:DivisionId" json:"DivisionId"`
	BankRecShowReceipts               bool    `gorm:"column:BankRecShowReceipts;not null" json:"BankRecShowReceipts"`
	BankRecShowPayments               bool    `gorm:"column:BankRecShowPayments;not null" json:"BankRecShowPayments"`
	BankRecGroupCheques               bool    `gorm:"column:BankRecGroupCheques;not null" json:"BankRecGroupCheques"`
	BankRecGroupCash                  bool    `gorm:"column:BankRecGroupCash;not null" json:"BankRecGroupCash"`
	BankRecGroupCredit                bool    `gorm:"column:BankRecGroupCredit;not null" json:"BankRecGroupCredit"`
	BankRecGroupDirect                bool    `gorm:"column:BankRecGroupDirect;not null" json:"BankRecGroupDirect"`
	RecordDepositDetails              bool    `gorm:"column:RecordDepositDetails;not null" json:"RecordDepositDetails"`
	CombinePayments                   bool    `gorm:"column:CombinePayments;not null;default:1" json:"CombinePayments"`
	CombineReceiptsCheque             int32   `gorm:"column:CombineReceiptsCheque;not null;default:1" json:"CombineReceiptsCheque"`
	CombineReceiptsCard               int32   `gorm:"column:CombineReceiptsCard;not null;default:1" json:"CombineReceiptsCard"`
	CombineReceiptsCash               int32   `gorm:"column:CombineReceiptsCash;not null;default:1" json:"CombineReceiptsCash"`
	CombineReceiptsEFTPOS             int32   `gorm:"column:CombineReceiptsEFTPOS;not null" json:"CombineReceiptsEFTPOS"`
	CombineReceiptsDirectDebit        int32   `gorm:"column:CombineReceiptsDirectDebit;not null;default:2" json:"CombineReceiptsDirectDebit"`
	StatementHistorySection           string  `gorm:"column:StatementHistorySection;not null" json:"StatementHistorySection"`
	CalculationSummarySection         string  `gorm:"column:CalculationSummarySection;not null" json:"CalculationSummarySection"`
	ReceiptMethod                     string  `gorm:"column:ReceiptMethod;not null" json:"ReceiptMethod"`
	BankAccountID                     int32   `gorm:"column:BankAccountId" json:"BankAccountId"`
	BankDivisionID                    int32   `gorm:"column:BankDivisionId" json:"BankDivisionId"`
	DebtorAccountID                   int32   `gorm:"column:DebtorAccountId" json:"DebtorAccountId"`
	DebtorDivisionID                  int32   `gorm:"column:DebtorDivisionId" json:"DebtorDivisionId"`
	CreditorAccountID                 int32   `gorm:"column:CreditorAccountId" json:"CreditorAccountId"`
	CreditorDivisionID                int32   `gorm:"column:CreditorDivisionId" json:"CreditorDivisionId"`
	SuspenseAccountID                 int32   `gorm:"column:SuspenseAccountId" json:"SuspenseAccountId"`
	SuspenseDivisionID                int32   `gorm:"column:SuspenseDivisionId" json:"SuspenseDivisionId"`
	PayrollNettWagesAccountID         int32   `gorm:"column:PayrollNettWagesAccountId" json:"PayrollNettWagesAccountId"`
	PayrollNettWagesDivisionID        int32   `gorm:"column:PayrollNettWagesDivisionId" json:"PayrollNettWagesDivisionId"`
	PayrollTaxWithheldAccountID       int32   `gorm:"column:PayrollTaxWithheldAccountId" json:"PayrollTaxWithheldAccountId"`
	PayrollTaxWithheldDivisionID      int32   `gorm:"column:PayrollTaxWithheldDivisionId" json:"PayrollTaxWithheldDivisionId"`
	PayrollSuperAccountID             int32   `gorm:"column:PayrollSuperAccountId" json:"PayrollSuperAccountId"`
	PayrollSuperDivisionID            int32   `gorm:"column:PayrollSuperDivisionId" json:"PayrollSuperDivisionId"`
	PayrollDeductionsAccountID        int32   `gorm:"column:PayrollDeductionsAccountId" json:"PayrollDeductionsAccountId"`
	PayrollDeductionsDivisionID       int32   `gorm:"column:PayrollDeductionsDivisionId" json:"PayrollDeductionsDivisionId"`
	ControlDebtorsAccountID           int32   `gorm:"column:ControlDebtorsAccountId" json:"ControlDebtorsAccountId"`
	ControlDebtorsDivisionID          int32   `gorm:"column:ControlDebtorsDivisionId" json:"ControlDebtorsDivisionId"`
	ControlCreditorsAccountID         int32   `gorm:"column:ControlCreditorsAccountId" json:"ControlCreditorsAccountId"`
	ControlCreditorsDivisionID        int32   `gorm:"column:ControlCreditorsDivisionId" json:"ControlCreditorsDivisionId"`
	GstAccruedOnSalesAccountID        int32   `gorm:"column:GstAccruedOnSalesAccountId" json:"GstAccruedOnSalesAccountId"`
	GstAccruedOnPurchasesAccountID    int32   `gorm:"column:GstAccruedOnPurchasesAccountId" json:"GstAccruedOnPurchasesAccountId"`
	BasLiabilityAccountID             int32   `gorm:"column:BasLiabilityAccountId" json:"BasLiabilityAccountId"`
	BasPAYGAccountID                  int32   `gorm:"column:BasPAYGAccountId" json:"BasPAYGAccountId"`
	BasFBTAccountID                   int32   `gorm:"column:BasFBTAccountId" json:"BasFBTAccountId"`
	BasWETAccountID                   int32   `gorm:"column:BasWETAccountId" json:"BasWETAccountId"`
	BasLuxuryCarAccountID             int32   `gorm:"column:BasLuxuryCarAccountId" json:"BasLuxuryCarAccountId"`
	BasDeferredAccountID              int32   `gorm:"column:BasDeferredAccountId" json:"BasDeferredAccountId"`
	BasFuelAccountID                  int32   `gorm:"column:BasFuelAccountId" json:"BasFuelAccountId"`
	ControlJournalAccountID           int32   `gorm:"column:ControlJournalAccountId;not null" json:"ControlJournalAccountId"`
	WagesPostingAccountID             int32   `gorm:"column:WagesPostingAccountId" json:"WagesPostingAccountId"`
	WagesDeductionsAccountID          int32   `gorm:"column:WagesDeductionsAccountId" json:"WagesDeductionsAccountId"`
	WagesSuperannuationAccountID      int32   `gorm:"column:WagesSuperannuationAccountId" json:"WagesSuperannuationAccountId"`
	WagesPostingDivisionID            int32   `gorm:"column:WagesPostingDivisionId" json:"WagesPostingDivisionId"`
	WagesDeductionsDivisionID         int32   `gorm:"column:WagesDeductionsDivisionId" json:"WagesDeductionsDivisionId"`
	WagesSuperDivisionID              int32   `gorm:"column:WagesSuperDivisionId" json:"WagesSuperDivisionId"`
	ReceiptChequeRequired             bool    `gorm:"column:ReceiptChequeRequired;not null;default:1" json:"ReceiptChequeRequired"`
	ReceiptCardRequired               bool    `gorm:"column:ReceiptCardRequired;not null;default:1" json:"ReceiptCardRequired"`
	ReceiptReferenceRequired          bool    `gorm:"column:ReceiptReferenceRequired;not null" json:"ReceiptReferenceRequired"`
	SurchargePercent                  float64 `gorm:"column:SurchargePercent;not null;default:0.0000" json:"SurchargePercent"`
	SurchargeAccountID                int32   `gorm:"column:SurchargeAccountId" json:"SurchargeAccountId"`
	SurchargeDivisionID               int32   `gorm:"column:SurchargeDivisionId" json:"SurchargeDivisionId"`
	ControlStockOnHandAccountID       int32   `gorm:"column:ControlStockOnHandAccountId" json:"ControlStockOnHandAccountId"`
	ControlStockOnHandDivisionID      int32   `gorm:"column:ControlStockOnHandDivisionId" json:"ControlStockOnHandDivisionId"`
	ControlStockCostOfSalesAccountID  int32   `gorm:"column:ControlStockCostOfSalesAccountId" json:"ControlStockCostOfSalesAccountId"`
	ControlStockCostOfSalesDivisionID int32   `gorm:"column:ControlStockCostOfSalesDivisionId" json:"ControlStockCostOfSalesDivisionId"`
	ControlStockAdjustmentAccountID   int32   `gorm:"column:ControlStockAdjustmentAccountId" json:"ControlStockAdjustmentAccountId"`
	ControlStockAdjustmentDivisionID  int32   `gorm:"column:ControlStockAdjustmentDivisionId" json:"ControlStockAdjustmentDivisionId"`
}

// TableName AccountSetting's table name
func (*AccountSetting) TableName() string {
	return TableNameAccountSetting
}
