// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountLedger = "AccountLedgers"

// AccountLedger mapped from table <AccountLedgers>
type AccountLedger struct {
	ID           int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	AccountID    int32     `gorm:"column:AccountId;not null" json:"AccountId"`
	Type         int32     `gorm:"column:Type;not null" json:"Type"`
	ReferenceID  int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	ReferenceNo  string    `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	For          string    `gorm:"column:For;not null" json:"For"`
	Date         time.Time `gorm:"column:Date;not null" json:"Date"`
	Details      string    `gorm:"column:Details;not null" json:"Details"`
	Amount       float64   `gorm:"column:Amount;not null;default:0.00" json:"Amount"`
	CloseOffDate time.Time `gorm:"column:CloseOffDate" json:"CloseOffDate"`
}

// TableName AccountLedger's table name
func (*AccountLedger) TableName() string {
	return TableNameAccountLedger
}
