// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountRange = "AccountRanges"

// AccountRange mapped from table <AccountRanges>
type AccountRange struct {
	AccountRangeID     int32  `gorm:"column:AccountRangeId;primaryKey;autoIncrement:true" json:"AccountRangeId"`
	Classification     string `gorm:"column:Classification;not null" json:"Classification"`
	Heading            string `gorm:"column:Heading;not null" json:"Heading"`
	CashFlowActivityID int32  `gorm:"column:CashFlowActivityId;not null" json:"CashFlowActivityId"`
	FromAccountCode    string `gorm:"column:FromAccountCode;not null" json:"FromAccountCode"`
	ToAccountCode      string `gorm:"column:ToAccountCode;not null" json:"ToAccountCode"`
	Level              int32  `gorm:"column:Level;not null" json:"Level"`
}

// TableName AccountRange's table name
func (*AccountRange) TableName() string {
	return TableNameAccountRange
}
