// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountDivision = "AccountDivisions"

// AccountDivision mapped from table <AccountDivisions>
type AccountDivision struct {
	AccountDivisionID int32   `gorm:"column:AccountDivisionId;primaryKey;autoIncrement:true" json:"AccountDivisionId"`
	AccountID         int32   `gorm:"column:AccountId;not null" json:"AccountId"`
	DivisionID        int32   `gorm:"column:DivisionId;not null" json:"DivisionId"`
	CurrentBalance    float64 `gorm:"column:CurrentBalance;not null" json:"CurrentBalance"`
	OpeningBalance    float64 `gorm:"column:OpeningBalance;not null" json:"OpeningBalance"`
	ClosingBalance    float64 `gorm:"column:ClosingBalance;not null" json:"ClosingBalance"`
}

// TableName AccountDivision's table name
func (*AccountDivision) TableName() string {
	return TableNameAccountDivision
}
