// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAddress = "Addresses"

// Address mapped from table <Addresses>
type Address struct {
	ID       int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Street   string `gorm:"column:Street;not null" json:"Street"`
	Suburb   string `gorm:"column:Suburb;not null" json:"Suburb"`
	Postcode string `gorm:"column:Postcode;not null" json:"Postcode"`
	State    string `gorm:"column:State;not null" json:"State"`
	Country  string `gorm:"column:Country;not null" json:"Country"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
