// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAdminLog = "AdminLogs"

// AdminLog mapped from table <AdminLogs>
type AdminLog struct {
	AdminLogID           int32     `gorm:"column:AdminLogId;primaryKey;autoIncrement:true" json:"AdminLogId"`
	StartTime            time.Time `gorm:"column:StartTime;not null" json:"StartTime"`
	OperationDescription string    `gorm:"column:OperationDescription;not null" json:"OperationDescription"`
	FinishTime           time.Time `gorm:"column:FinishTime" json:"FinishTime"`
}

// TableName AdminLog's table name
func (*AdminLog) TableName() string {
	return TableNameAdminLog
}
