// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAssembly = "Assembly"

// Assembly mapped from table <Assembly>
type Assembly struct {
	AssemblyID      int32     `gorm:"column:AssemblyId;primaryKey;autoIncrement:true" json:"AssemblyId"`
	Code            string    `gorm:"column:Code;not null" json:"Code"`
	Description     string    `gorm:"column:Description;not null" json:"Description"`
	UnitID          int32     `gorm:"column:UnitId;not null" json:"UnitId"`
	LastUpdated     time.Time `gorm:"column:LastUpdated;not null" json:"LastUpdated"`
	PriceCategoryID int32     `gorm:"column:PriceCategoryId" json:"PriceCategoryId"`
	EstimateTypeID  int32     `gorm:"column:EstimateTypeId" json:"EstimateTypeId"`
	EraID           int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion     int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Assembly's table name
func (*Assembly) TableName() string {
	return TableNameAssembly
}
