// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyClientPrice = "AssemblyClientPrices"

// AssemblyClientPrice mapped from table <AssemblyClientPrices>
type AssemblyClientPrice struct {
	AssemblyClientPriceID int32   `gorm:"column:AssemblyClientPriceId;primaryKey;autoIncrement:true" json:"AssemblyClientPriceId"`
	AssemblyID            int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	ClientID              int32   `gorm:"column:ClientId;not null" json:"ClientId"`
	BasedOn               string  `gorm:"column:BasedOn;not null" json:"BasedOn"`
	Retail                float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName AssemblyClientPrice's table name
func (*AssemblyClientPrice) TableName() string {
	return TableNameAssemblyClientPrice
}
