// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyPricebook = "AssemblyPricebook"

// AssemblyPricebook mapped from table <AssemblyPricebook>
type AssemblyPricebook struct {
	AssemblyPricebookID int32   `gorm:"column:AssemblyPricebookId;primaryKey;autoIncrement:true" json:"AssemblyPricebookId"`
	AssemblyID          int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	PricebookID         int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	RowID               int32   `gorm:"column:RowId;not null" json:"RowId"`
	Cost                float64 `gorm:"column:Cost;not null" json:"Cost"`
	Quantity            float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Retail              float64 `gorm:"column:Retail;not null" json:"Retail"`
	FixedQuantity       float64 `gorm:"column:FixedQuantity" json:"FixedQuantity"`
}

// TableName AssemblyPricebook's table name
func (*AssemblyPricebook) TableName() string {
	return TableNameAssemblyPricebook
}
