// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyLabourRate = "AssemblyLabourRates"

// AssemblyLabourRate mapped from table <AssemblyLabourRates>
type AssemblyLabourRate struct {
	AssemblyLabourRateID int32   `gorm:"column:AssemblyLabourRateId;primaryKey;autoIncrement:true" json:"AssemblyLabourRateId"`
	AssemblyID           int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	LabourRateID         int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	RowID                int32   `gorm:"column:RowId;not null" json:"RowId"`
	Hours                float64 `gorm:"column:Hours;not null" json:"Hours"`
	Cost                 float64 `gorm:"column:Cost;not null" json:"Cost"`
	Retail               float64 `gorm:"column:Retail;not null" json:"Retail"`
	FixedHours           float64 `gorm:"column:FixedHours;not null" json:"FixedHours"`
}

// TableName AssemblyLabourRate's table name
func (*AssemblyLabourRate) TableName() string {
	return TableNameAssemblyLabourRate
}
