// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyLabourRatesCostCentre = "AssemblyLabourRatesCostCentres"

// AssemblyLabourRatesCostCentre mapped from table <AssemblyLabourRatesCostCentres>
type AssemblyLabourRatesCostCentre struct {
	AssemblyLabourRatesCostCentresID int32   `gorm:"column:AssemblyLabourRatesCostCentresId;primaryKey;autoIncrement:true" json:"AssemblyLabourRatesCostCentresId"`
	AssemblyLabourRatesID            int32   `gorm:"column:AssemblyLabourRatesId;not null" json:"AssemblyLabourRatesId"`
	CostCentreID                     int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	Quantity                         float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	FixedQuantity                    float64 `gorm:"column:FixedQuantity;not null;default:0.0000" json:"FixedQuantity"`
}

// TableName AssemblyLabourRatesCostCentre's table name
func (*AssemblyLabourRatesCostCentre) TableName() string {
	return TableNameAssemblyLabourRatesCostCentre
}
