// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyPricebookCostCentre = "AssemblyPricebookCostCentres"

// AssemblyPricebookCostCentre mapped from table <AssemblyPricebookCostCentres>
type AssemblyPricebookCostCentre struct {
	AssemblyPricebookCostCentreID int32   `gorm:"column:AssemblyPricebookCostCentreId;primaryKey;autoIncrement:true" json:"AssemblyPricebookCostCentreId"`
	AssemblyPricebookID           int32   `gorm:"column:AssemblyPricebookId;not null" json:"AssemblyPricebookId"`
	CostCentreID                  int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	Quantity                      float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	FixedQuantity                 float64 `gorm:"column:FixedQuantity;not null" json:"FixedQuantity"`
}

// TableName AssemblyPricebookCostCentre's table name
func (*AssemblyPricebookCostCentre) TableName() string {
	return TableNameAssemblyPricebookCostCentre
}
