// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAssemblyClassificationPrice = "AssemblyClassificationPrices"

// AssemblyClassificationPrice mapped from table <AssemblyClassificationPrices>
type AssemblyClassificationPrice struct {
	AssemblyClassificationPriceID int32   `gorm:"column:AssemblyClassificationPriceId;primaryKey;autoIncrement:true" json:"AssemblyClassificationPriceId"`
	AssemblyID                    int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	ClientClassificationID        int32   `gorm:"column:ClientClassificationId;not null" json:"ClientClassificationId"`
	BasedOn                       string  `gorm:"column:BasedOn;not null" json:"BasedOn"`
	Retail                        float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName AssemblyClassificationPrice's table name
func (*AssemblyClassificationPrice) TableName() string {
	return TableNameAssemblyClassificationPrice
}
