// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAttachment = "Attachments"

// Attachment mapped from table <Attachments>
type Attachment struct {
	AttachmentID int32  `gorm:"column:AttachmentId;primaryKey" json:"AttachmentId"`
	Path         string `gorm:"column:Path;not null" json:"Path"`
	Extension    string `gorm:"column:Extension;not null" json:"Extension"`
	Description  string `gorm:"column:Description;not null" json:"Description"`
	FileID       int32  `gorm:"column:FileId;not null" json:"FileId"`
}

// TableName Attachment's table name
func (*Attachment) TableName() string {
	return TableNameAttachment
}
