// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAuditMerge = "AuditMerge"

// AuditMerge mapped from table <AuditMerge>
type AuditMerge struct {
	AuditMergeID int32     `gorm:"column:AuditMergeId;primaryKey;autoIncrement:true" json:"AuditMergeId"`
	UserID       int32     `gorm:"column:UserId;not null" json:"UserId"`
	Date         time.Time `gorm:"column:Date;not null" json:"Date"`
	Details      string    `gorm:"column:Details" json:"Details"`
}

// TableName AuditMerge's table name
func (*AuditMerge) TableName() string {
	return TableNameAuditMerge
}
