// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAudit = "Audit"

// Audit mapped from table <Audit>
type Audit struct {
	AuditID int32  `gorm:"column:AuditId;primaryKey" json:"AuditId"`
	Changes string `gorm:"column:Changes;not null" json:"Changes"`
}

// TableName Audit's table name
func (*Audit) TableName() string {
	return TableNameAudit
}
