// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAxiapacSetting = "AxiapacSettings"

// AxiapacSetting mapped from table <AxiapacSettings>
type AxiapacSetting struct {
	Name        string `gorm:"column:Name;primaryKey" json:"Name"`
	Value       string `gorm:"column:Value" json:"Value"`
	Description string `gorm:"column:Description" json:"Description"`
}

// TableName AxiapacSetting's table name
func (*AxiapacSetting) TableName() string {
	return TableNameAxiapacSetting
}
