// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBank = "Banks"

// Bank mapped from table <Banks>
type Bank struct {
	BankID      int32     `gorm:"column:BankId;primaryKey;autoIncrement:true" json:"BankId"`
	BSB         string    `gorm:"column:BSB;not null" json:"BSB"`
	Bank        string    `gorm:"column:Bank;not null" json:"Bank"`
	Branch      string    `gorm:"column:Branch;not null" json:"Branch"`
	Address     string    `gorm:"column:Address;not null" json:"Address"`
	Postcode    string    `gorm:"column:Postcode" json:"Postcode"`
	Country     string    `gorm:"column:Country;not null" json:"Country"`
	EffectiveAt time.Time `gorm:"column:EffectiveAt;not null" json:"EffectiveAt"`
	IsObsolete  bool      `gorm:"column:IsObsolete;not null" json:"IsObsolete"`
}

// TableName Bank's table name
func (*Bank) TableName() string {
	return TableNameBank
}
