// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBankingStatement = "BankingStatements"

// BankingStatement mapped from table <BankingStatements>
type BankingStatement struct {
	BankingStatementID int32     `gorm:"column:BankingStatementId;primaryKey;autoIncrement:true" json:"BankingStatementId"`
	BankingID          int32     `gorm:"column:BankingId;not null" json:"BankingId"`
	Date               time.Time `gorm:"column:Date;not null" json:"Date"`
	Amount             float64   `gorm:"column:Amount;not null" json:"Amount"`
	OpeningBalance     float64   `gorm:"column:OpeningBalance;not null" json:"OpeningBalance"`
	ClosingBalance     float64   `gorm:"column:ClosingBalance;not null" json:"ClosingBalance"`
	Reconciled         bool      `gorm:"column:Reconciled;not null" json:"Reconciled"`
}

// TableName BankingStatement's table name
func (*BankingStatement) TableName() string {
	return TableNameBankingStatement
}
