// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBankingStatementItem = "BankingStatementItems"

// BankingStatementItem mapped from table <BankingStatementItems>
type BankingStatementItem struct {
	BankingStatementItemID int32   `gorm:"column:BankingStatementItemId;primaryKey;autoIncrement:true" json:"BankingStatementItemId"`
	BankingStatementID     int32   `gorm:"column:BankingStatementId;not null" json:"BankingStatementId"`
	Amount                 float64 `gorm:"column:Amount;not null" json:"Amount"`
	Balance                float64 `gorm:"column:Balance;not null" json:"Balance"`
	StatementRowNo         int32   `gorm:"column:StatementRowNo;not null;default:1" json:"StatementRowNo"`
}

// TableName BankingStatementItem's table name
func (*BankingStatementItem) TableName() string {
	return TableNameBankingStatementItem
}
