// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBanking = "Banking"

// Banking mapped from table <Banking>
type Banking struct {
	BankingID                    int32     `gorm:"column:BankingId;primaryKey" json:"BankingId"`
	DivisionID                   int32     `gorm:"column:DivisionId" json:"DivisionId"`
	StatementFrequency           string    `gorm:"column:StatementFrequency;not null" json:"StatementFrequency"`
	LastStatementNo              int32     `gorm:"column:LastStatementNo" json:"LastStatementNo"`
	LastStatementDate            time.Time `gorm:"column:LastStatementDate;not null" json:"LastStatementDate"`
	LastStatementBalance         float64   `gorm:"column:LastStatementBalance;not null" json:"LastStatementBalance"`
	ClosingReconcileDate         time.Time `gorm:"column:ClosingReconcileDate;not null" json:"ClosingReconcileDate"`
	ClosingReconcileBalance      float64   `gorm:"column:ClosingReconcileBalance;not null" json:"ClosingReconcileBalance"`
	CurrentReconciliationDate    time.Time `gorm:"column:CurrentReconciliationDate;not null" json:"CurrentReconciliationDate"`
	WIPNextStatementDate         time.Time `gorm:"column:WIPNextStatementDate" json:"WIPNextStatementDate"`
	CurrentReconciliationBalance float64   `gorm:"column:CurrentReconciliationBalance;not null" json:"CurrentReconciliationBalance"`
	BankID                       int32     `gorm:"column:BankId" json:"BankId"`
	AccountNo                    string    `gorm:"column:AccountNo;not null" json:"AccountNo"`
	NextChequeNo                 int32     `gorm:"column:NextChequeNo" json:"NextChequeNo"`
	BankAccountType              int32     `gorm:"column:BankAccountType;not null" json:"BankAccountType"`
	EFTUserNo                    string    `gorm:"column:EFTUserNo" json:"EFTUserNo"`
	EFTUserName                  string    `gorm:"column:EFTUserName" json:"EFTUserName"`
	EFTTraceAccountNo            string    `gorm:"column:EFTTraceAccountNo" json:"EFTTraceAccountNo"`
	EFTSelfBalance               bool      `gorm:"column:EFTSelfBalance;not null" json:"EFTSelfBalance"`
	ShouldStartNextStatement     bool      `gorm:"column:ShouldStartNextStatement;not null" json:"ShouldStartNextStatement"`
	EFTTraceBankID               int32     `gorm:"column:EFTTraceBankId" json:"EFTTraceBankId"`
	DataVersion                  int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	EraID                        int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa                        time.Time `gorm:"column:Circa;not null" json:"Circa"`
}

// TableName Banking's table name
func (*Banking) TableName() string {
	return TableNameBanking
}
