// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBankingTransaction = "BankingTransactions"

// BankingTransaction mapped from table <BankingTransactions>
type BankingTransaction struct {
	BankingTransactionID   int32     `gorm:"column:BankingTransactionId;primaryKey;autoIncrement:true" json:"BankingTransactionId"`
	BankingID              int32     `gorm:"column:BankingId;not null" json:"BankingId"`
	TransactionID          int32     `gorm:"column:TransactionId" json:"TransactionId"`
	BasID                  int32     `gorm:"column:BasId" json:"BasId"`
	Type                   string    `gorm:"column:Type;not null" json:"Type"`
	TransNo                string    `gorm:"column:TransNo;not null" json:"TransNo"`
	Reference              string    `gorm:"column:Reference;not null" json:"Reference"`
	Details                string    `gorm:"column:Details;not null" json:"Details"`
	Date                   time.Time `gorm:"column:Date;not null" json:"Date"`
	Amount                 float64   `gorm:"column:Amount;not null" json:"Amount"`
	Reconciled             bool      `gorm:"column:Reconciled;not null" json:"Reconciled"`
	DateBanked             time.Time `gorm:"column:DateBanked" json:"DateBanked"`
	BankingStatementItemID int32     `gorm:"column:BankingStatementItemId" json:"BankingStatementItemId"`
}

// TableName BankingTransaction's table name
func (*BankingTransaction) TableName() string {
	return TableNameBankingTransaction
}
