// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBa = "Bas"

// Ba mapped from table <Bas>
type Ba struct {
	BasID                      int32     `gorm:"column:BasId;primaryKey;autoIncrement:true" json:"BasId"`
	Reference                  string    `gorm:"column:Reference;not null" json:"Reference"`
	Start                      time.Time `gorm:"column:Start;not null" json:"Start"`
	Finish                     time.Time `gorm:"column:Finish;not null" json:"Finish"`
	FormCode                   string    `gorm:"column:FormCode;not null" json:"FormCode"`
	FormDescription            string    `gorm:"column:FormDescription;not null" json:"FormDescription"`
	Method                     string    `gorm:"column:Method;not null" json:"Method"`
	GSTOption                  int32     `gorm:"column:GSTOption" json:"GSTOption"`
	G1                         float64   `gorm:"column:G1" json:"G1"`
	G2                         float64   `gorm:"column:G2" json:"G2"`
	G3                         float64   `gorm:"column:G3" json:"G3"`
	G10                        float64   `gorm:"column:G10" json:"G10"`
	G11                        float64   `gorm:"column:G11" json:"G11"`
	G21                        float64   `gorm:"column:G21" json:"G21"`
	G22                        float64   `gorm:"column:G22" json:"G22"`
	G23                        float64   `gorm:"column:G23" json:"G23"`
	G24                        string    `gorm:"column:G24" json:"G24"`
	W1                         float64   `gorm:"column:W1" json:"W1"`
	W2                         float64   `gorm:"column:W2" json:"W2"`
	W3                         float64   `gorm:"column:W3" json:"W3"`
	W4                         float64   `gorm:"column:W4" json:"W4"`
	PAYGOption                 int32     `gorm:"column:PAYGOption" json:"PAYGOption"`
	T1                         float64   `gorm:"column:T1" json:"T1"`
	T2                         float64   `gorm:"column:T2" json:"T2"`
	T3                         float64   `gorm:"column:T3" json:"T3"`
	T4                         string    `gorm:"column:T4" json:"T4"`
	T7                         float64   `gorm:"column:T7" json:"T7"`
	T8                         float64   `gorm:"column:T8" json:"T8"`
	T9                         float64   `gorm:"column:T9" json:"T9"`
	F1                         float64   `gorm:"column:F1" json:"F1"`
	F2                         float64   `gorm:"column:F2" json:"F2"`
	F3                         float64   `gorm:"column:F3" json:"F3"`
	F4                         string    `gorm:"column:F4" json:"F4"`
	Payment1A                  float64   `gorm:"column:Payment1A" json:"Payment1A"`
	Payment1C                  float64   `gorm:"column:Payment1C" json:"Payment1C"`
	Payment1E                  float64   `gorm:"column:Payment1E" json:"Payment1E"`
	Payment4                   float64   `gorm:"column:Payment4" json:"Payment4"`
	Payment5A                  float64   `gorm:"column:Payment5A" json:"Payment5A"`
	Payment6A                  float64   `gorm:"column:Payment6A" json:"Payment6A"`
	Payment7                   float64   `gorm:"column:Payment7" json:"Payment7"`
	Payment7C                  float64   `gorm:"column:Payment7C" json:"Payment7C"`
	Refund1B                   float64   `gorm:"column:Refund1B" json:"Refund1B"`
	Refund1D                   float64   `gorm:"column:Refund1D" json:"Refund1D"`
	Refund1F                   float64   `gorm:"column:Refund1F" json:"Refund1F"`
	Refund5B                   float64   `gorm:"column:Refund5B" json:"Refund5B"`
	Refund6B                   float64   `gorm:"column:Refund6B" json:"Refund6B"`
	Refund7D                   float64   `gorm:"column:Refund7D" json:"Refund7D"`
	Payment8A                  float64   `gorm:"column:Payment8A" json:"Payment8A"`
	Refund8B                   float64   `gorm:"column:Refund8B" json:"Refund8B"`
	Balance                    float64   `gorm:"column:Balance" json:"Balance"`
	EraID                      int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Status                     string    `gorm:"column:Status;not null" json:"Status"`
	StatusDescription          string    `gorm:"column:StatusDescription;not null" json:"StatusDescription"`
	SBR                        bool      `gorm:"column:SBR;not null" json:"SBR"`
	Circa                      time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DueDate                    time.Time `gorm:"column:DueDate;not null" json:"DueDate"`
	CalculatedAt               time.Time `gorm:"column:CalculatedAt" json:"CalculatedAt"`
	ReconciledAt               time.Time `gorm:"column:ReconciledAt" json:"ReconciledAt"`
	LodgedAt                   time.Time `gorm:"column:LodgedAt" json:"LodgedAt"`
	ReceiptID                  string    `gorm:"column:ReceiptId" json:"ReceiptId"`
	Workflow                   string    `gorm:"column:Workflow;not null" json:"Workflow"`
	DataVersion                int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	Authorised                 bool      `gorm:"column:Authorised;not null" json:"Authorised"`
	AccountsCloseOffDate       time.Time `gorm:"column:AccountsCloseOffDate;not null" json:"AccountsCloseOffDate"`
	DebtorsCloseOffDate        time.Time `gorm:"column:DebtorsCloseOffDate;not null" json:"DebtorsCloseOffDate"`
	CreditorsCloseOffDate      time.Time `gorm:"column:CreditorsCloseOffDate;not null" json:"CreditorsCloseOffDate"`
	PayrollValidatedDate       time.Time `gorm:"column:PayrollValidatedDate;not null" json:"PayrollValidatedDate"`
	AccountsCloseOffAuthorise  bool      `gorm:"column:AccountsCloseOffAuthorise;not null" json:"AccountsCloseOffAuthorise"`
	DebtorsCloseOffAuthorise   bool      `gorm:"column:DebtorsCloseOffAuthorise;not null" json:"DebtorsCloseOffAuthorise"`
	CreditorsCloseOffAuthorise bool      `gorm:"column:CreditorsCloseOffAuthorise;not null" json:"CreditorsCloseOffAuthorise"`
	PayrollValidatedAuthorise  bool      `gorm:"column:PayrollValidatedAuthorise;not null" json:"PayrollValidatedAuthorise"`
	SaveWorksheet              time.Time `gorm:"column:SaveWorksheet" json:"SaveWorksheet"`
}

// TableName Ba's table name
func (*Ba) TableName() string {
	return TableNameBa
}
