// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBasItem = "BasItems"

// BasItem mapped from table <BasItems>
type BasItem struct {
	BasItemID           int32     `gorm:"column:BasItemId;primaryKey;autoIncrement:true" json:"BasItemId"`
	BasID               int32     `gorm:"column:BasId;not null" json:"BasId"`
	Source              string    `gorm:"column:Source;not null" json:"Source"`
	SourceID            int32     `gorm:"column:SourceId;not null" json:"SourceId"`
	Reference           string    `gorm:"column:Reference;not null" json:"Reference"`
	Date                time.Time `gorm:"column:Date;not null" json:"Date"`
	BankAccountCode     string    `gorm:"column:BankAccountCode;not null" json:"BankAccountCode"`
	Type                string    `gorm:"column:Type;not null" json:"Type"`
	Amount              float64   `gorm:"column:Amount;not null" json:"Amount"`
	GstAmount           float64   `gorm:"column:GstAmount;not null" json:"GstAmount"`
	CalculatedGstAmount float64   `gorm:"column:CalculatedGstAmount;not null" json:"CalculatedGstAmount"`
	PostingAmount       float64   `gorm:"column:PostingAmount;not null;default:0.00" json:"PostingAmount"`
}

// TableName BasItem's table name
func (*BasItem) TableName() string {
	return TableNameBasItem
}
