// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBasPosting = "BasPostings"

// BasPosting mapped from table <BasPostings>
type BasPosting struct {
	BasPostingsID   int32   `gorm:"column:BasPostingsId;primaryKey;autoIncrement:true" json:"BasPostingsId"`
	BasID           int32   `gorm:"column:BasId;not null" json:"BasId"`
	BasType         string  `gorm:"column:BasType;not null" json:"BasType"`
	Amount          float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID  int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
}

// TableName BasPosting's table name
func (*BasPosting) TableName() string {
	return TableNameBasPosting
}
