// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBatchPaymentSupplier = "BatchPaymentSuppliers"

// BatchPaymentSupplier mapped from table <BatchPaymentSuppliers>
type BatchPaymentSupplier struct {
	BatchPaymentSupplierID int32     `gorm:"column:BatchPaymentSupplierId;primaryKey;autoIncrement:true" json:"BatchPaymentSupplierId"`
	BatchPaymentID         int32     `gorm:"column:BatchPaymentId;not null" json:"BatchPaymentId"`
	SupplierID             int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	SupplierCode           string    `gorm:"column:SupplierCode;not null" json:"SupplierCode"`
	SupplierName           string    `gorm:"column:SupplierName;not null" json:"SupplierName"`
	SupplierEmail          string    `gorm:"column:SupplierEmail" json:"SupplierEmail"`
	SupplierOnHold         bool      `gorm:"column:SupplierOnHold;not null" json:"SupplierOnHold"`
	BankID                 int32     `gorm:"column:BankId" json:"BankId"`
	BSB                    string    `gorm:"column:BSB" json:"BSB"`
	AccountNo              string    `gorm:"column:AccountNo" json:"AccountNo"`
	AccountName            string    `gorm:"column:AccountName" json:"AccountName"`
	Reference              string    `gorm:"column:Reference;not null" json:"Reference"`
	Owing                  float64   `gorm:"column:Owing;not null" json:"Owing"`
	Payment                float64   `gorm:"column:Payment;not null" json:"Payment"`
	PurchasesCount         int32     `gorm:"column:PurchasesCount;not null" json:"PurchasesCount"`
	InDisputeCount         int32     `gorm:"column:InDisputeCount;not null" json:"InDisputeCount"`
	Excluded               bool      `gorm:"column:Excluded;not null" json:"Excluded"`
	Authorised             time.Time `gorm:"column:Authorised" json:"Authorised"`
	ABAFileCreated         time.Time `gorm:"column:ABAFileCreated" json:"ABAFileCreated"`
	TransactionID          int32     `gorm:"column:TransactionId" json:"TransactionId"`
	TransNo                int32     `gorm:"column:TransNo" json:"TransNo"`
	RemittanceCreated      time.Time `gorm:"column:RemittanceCreated" json:"RemittanceCreated"`
	RemittanceFileID       int32     `gorm:"column:RemittanceFileId" json:"RemittanceFileId"`
	RemittanceEmailed      time.Time `gorm:"column:RemittanceEmailed" json:"RemittanceEmailed"`
	WorkflowStatus         string    `gorm:"column:WorkflowStatus;not null" json:"WorkflowStatus"`
	WorkflowStatusMemo     string    `gorm:"column:WorkflowStatusMemo;not null" json:"WorkflowStatusMemo"`
}

// TableName BatchPaymentSupplier's table name
func (*BatchPaymentSupplier) TableName() string {
	return TableNameBatchPaymentSupplier
}
