// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBatchPayment = "BatchPayment"

// BatchPayment mapped from table <BatchPayment>
type BatchPayment struct {
	BatchPaymentID                   int32     `gorm:"column:BatchPaymentId;primaryKey;autoIncrement:true" json:"BatchPaymentId"`
	BatchNo                          int32     `gorm:"column:BatchNo;not null" json:"BatchNo"`
	Date                             time.Time `gorm:"column:Date;not null" json:"Date"`
	DueDate                          time.Time `gorm:"column:DueDate" json:"DueDate"`
	TradingTerms                     string    `gorm:"column:TradingTerms;default:S" json:"TradingTerms"`
	TradingDays                      int32     `gorm:"column:TradingDays" json:"TradingDays"`
	PaymentMethods                   string    `gorm:"column:PaymentMethods" json:"PaymentMethods"`
	BusinessNature                   string    `gorm:"column:BusinessNature" json:"BusinessNature"`
	BankingID                        int32     `gorm:"column:BankingId" json:"BankingId"`
	BankingBSB                       string    `gorm:"column:BankingBSB" json:"BankingBSB"`
	BankingAccountCode               string    `gorm:"column:BankingAccountCode" json:"BankingAccountCode"`
	BankingAccountNo                 string    `gorm:"column:BankingAccountNo" json:"BankingAccountNo"`
	Amount                           float64   `gorm:"column:Amount;not null" json:"Amount"`
	ABAFileID                        int32     `gorm:"column:ABAFileId" json:"ABAFileId"`
	RemittanceFromEmailAccountID     int32     `gorm:"column:RemittanceFromEmailAccountId" json:"RemittanceFromEmailAccountId"`
	WorkflowStatus                   string    `gorm:"column:WorkflowStatus;not null" json:"WorkflowStatus"`
	Calculated                       time.Time `gorm:"column:Calculated" json:"Calculated"`
	Authorised                       time.Time `gorm:"column:Authorised" json:"Authorised"`
	SuppliersPaid                    time.Time `gorm:"column:SuppliersPaid" json:"SuppliersPaid"`
	ABAFileCreated                   time.Time `gorm:"column:ABAFileCreated" json:"ABAFileCreated"`
	ABAProcessedDate                 time.Time `gorm:"column:ABAProcessedDate" json:"ABAProcessedDate"`
	RemittanceCreated                time.Time `gorm:"column:RemittanceCreated" json:"RemittanceCreated"`
	RemittanceEmailed                time.Time `gorm:"column:RemittanceEmailed" json:"RemittanceEmailed"`
	Finalised                        time.Time `gorm:"column:Finalised" json:"Finalised"`
	RemittanceMessageTemplateSubject string    `gorm:"column:RemittanceMessageTemplateSubject" json:"RemittanceMessageTemplateSubject"`
	RemittanceMessageTemplateBody    string    `gorm:"column:RemittanceMessageTemplateBody" json:"RemittanceMessageTemplateBody"`
	EraID                            int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion                      int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	Circa                            time.Time `gorm:"column:Circa;not null" json:"Circa"`
}

// TableName BatchPayment's table name
func (*BatchPayment) TableName() string {
	return TableNameBatchPayment
}
