// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameBatchPaymentPosting = "BatchPaymentPostings"

// BatchPaymentPosting mapped from table <BatchPaymentPostings>
type BatchPaymentPosting struct {
	BatchPaymentPostingID  int32     `gorm:"column:BatchPaymentPostingId;primaryKey;autoIncrement:true" json:"BatchPaymentPostingId"`
	BatchPaymentSupplierID int32     `gorm:"column:BatchPaymentSupplierId;not null" json:"BatchPaymentSupplierId"`
	PurchaseID             int32     `gorm:"column:PurchaseId;not null" json:"PurchaseId"`
	PurchaseInvoiceNo      string    `gorm:"column:PurchaseInvoiceNo;not null" json:"PurchaseInvoiceNo"`
	PurchaseDate           time.Time `gorm:"column:PurchaseDate;not null" json:"PurchaseDate"`
	PurchaseDueDate        time.Time `gorm:"column:PurchaseDueDate;not null" json:"PurchaseDueDate"`
	InDispute              bool      `gorm:"column:InDispute;not null" json:"InDispute"`
	Owing                  float64   `gorm:"column:Owing;not null" json:"Owing"`
	Payment                float64   `gorm:"column:Payment;not null" json:"Payment"`
	WorkflowStatus         string    `gorm:"column:WorkflowStatus;not null" json:"WorkflowStatus"`
	WorkflowStatusMemo     string    `gorm:"column:WorkflowStatusMemo;not null" json:"WorkflowStatusMemo"`
}

// TableName BatchPaymentPosting's table name
func (*BatchPaymentPosting) TableName() string {
	return TableNameBatchPaymentPosting
}
