// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBusinessNature = "BusinessNature"

// BusinessNature mapped from table <BusinessNature>
type BusinessNature struct {
	BusinessNatureID int32  `gorm:"column:BusinessNatureId;primaryKey;autoIncrement:true" json:"BusinessNatureId"`
	Code             string `gorm:"column:Code;not null" json:"Code"`
	Description      string `gorm:"column:Description;not null" json:"Description"`
	Obsolete         bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName BusinessNature's table name
func (*BusinessNature) TableName() string {
	return TableNameBusinessNature
}
