// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCalendarRegion = "CalendarRegions"

// CalendarRegion mapped from table <CalendarRegions>
type CalendarRegion struct {
	CalendarRegionID       int32  `gorm:"column:CalendarRegionId;primaryKey;autoIncrement:true" json:"CalendarRegionId"`
	Code                   string `gorm:"column:Code;not null" json:"Code"`
	Description            string `gorm:"column:Description;not null" json:"Description"`
	State                  string `gorm:"column:State" json:"State"`
	FromPostCode           int32  `gorm:"column:FromPostCode" json:"FromPostCode"`
	ToPostCode             int32  `gorm:"column:ToPostCode" json:"ToPostCode"`
	Obsolete               bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	Master                 bool   `gorm:"column:Master;not null" json:"Master"`
	MasterCalendarRegionID int32  `gorm:"column:MasterCalendarRegionId" json:"MasterCalendarRegionId"`
}

// TableName CalendarRegion's table name
func (*CalendarRegion) TableName() string {
	return TableNameCalendarRegion
}
