// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCard = "Cards"

// Card mapped from table <Cards>
type Card struct {
	CardID      int32  `gorm:"column:CardId;primaryKey;autoIncrement:true" json:"CardId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Card's table name
func (*Card) TableName() string {
	return TableNameCard
}
