// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCashFlowActivity = "CashFlowActivities"

// CashFlowActivity mapped from table <CashFlowActivities>
type CashFlowActivity struct {
	ID          int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Category    string `gorm:"column:Category;not null" json:"Category"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName CashFlowActivity's table name
func (*CashFlowActivity) TableName() string {
	return TableNameCashFlowActivity
}
