// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCheckList = "CheckLists"

// CheckList mapped from table <CheckLists>
type CheckList struct {
	CheckListID int32  `gorm:"column:CheckListId;primaryKey;autoIncrement:true" json:"CheckListId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName CheckList's table name
func (*CheckList) TableName() string {
	return TableNameCheckList
}
