// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameClientBannedTechnician = "ClientBannedTechnicians"

// ClientBannedTechnician mapped from table <ClientBannedTechnicians>
type ClientBannedTechnician struct {
	ClientBannedTechnicianID int32 `gorm:"column:ClientBannedTechnicianId;primaryKey;autoIncrement:true" json:"ClientBannedTechnicianId"`
	ClientID                 int32 `gorm:"column:ClientId;not null" json:"ClientId"`
	EmployeeID               int32 `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
}

// TableName ClientBannedTechnician's table name
func (*ClientBannedTechnician) TableName() string {
	return TableNameClientBannedTechnician
}
