// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameClientClassification = "ClientClassification"

// ClientClassification mapped from table <ClientClassification>
type ClientClassification struct {
	ClientClassificationID int32  `gorm:"column:ClientClassificationId;primaryKey;autoIncrement:true" json:"ClientClassificationId"`
	Code                   string `gorm:"column:Code;not null" json:"Code"`
	Description            string `gorm:"column:Description;not null" json:"Description"`
	Obsolete               bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName ClientClassification's table name
func (*ClientClassification) TableName() string {
	return TableNameClientClassification
}
