// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameClientPreferredTechnician = "ClientPreferredTechnicians"

// ClientPreferredTechnician mapped from table <ClientPreferredTechnicians>
type ClientPreferredTechnician struct {
	ClientPreferredTechnicianID int32 `gorm:"column:ClientPreferredTechnicianId;primaryKey;autoIncrement:true" json:"ClientPreferredTechnicianId"`
	ClientID                    int32 `gorm:"column:ClientId;not null" json:"ClientId"`
	EmployeeID                  int32 `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
}

// TableName ClientPreferredTechnician's table name
func (*ClientPreferredTechnician) TableName() string {
	return TableNameClientPreferredTechnician
}
