// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameClientSetting = "ClientSettings"

// ClientSetting mapped from table <ClientSettings>
type ClientSetting struct {
	ClientSettingID            int32   `gorm:"column:ClientSettingId;primaryKey" json:"ClientSettingId"`
	TradingTermID              int32   `gorm:"column:TradingTermId" json:"TradingTermId"`
	CreditLimit                float64 `gorm:"column:CreditLimit" json:"CreditLimit"`
	PhoneRequired              bool    `gorm:"column:PhoneRequired;not null" json:"PhoneRequired"`
	ReceiptLayoutID            int32   `gorm:"column:ReceiptLayoutId" json:"ReceiptLayoutId"`
	StatementLayoutID          int32   `gorm:"column:StatementLayoutId" json:"StatementLayoutId"`
	PaymentMethodID            int32   `gorm:"column:PaymentMethodId" json:"PaymentMethodId"`
	FromEmailAccountID         int32   `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	ReceiptMessageTemplateID   int32   `gorm:"column:ReceiptMessageTemplateId" json:"ReceiptMessageTemplateId"`
	StatementMessageTemplateID int32   `gorm:"column:StatementMessageTemplateId" json:"StatementMessageTemplateId"`
}

// TableName ClientSetting's table name
func (*ClientSetting) TableName() string {
	return TableNameClientSetting
}
