// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameClientClientClassification = "ClientClientClassification"

// ClientClientClassification mapped from table <ClientClientClassification>
type ClientClientClassification struct {
	ClientClientClassificationID int32 `gorm:"column:ClientClientClassificationId;primaryKey;autoIncrement:true" json:"ClientClientClassificationId"`
	ClientID                     int32 `gorm:"column:ClientId;not null" json:"ClientId"`
	ClientClassificationID       int32 `gorm:"column:ClientClassificationId;not null" json:"ClientClassificationId"`
}

// TableName ClientClientClassification's table name
func (*ClientClientClassification) TableName() string {
	return TableNameClientClientClassification
}
