// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameClient = "Clients"

// Client mapped from table <Clients>
type Client struct {
	ClientID                 int32     `gorm:"column:ClientId;primaryKey;autoIncrement:true" json:"ClientId"`
	Code                     string    `gorm:"column:Code;not null" json:"Code"`
	Name                     string    `gorm:"column:Name;not null" json:"Name"`
	PhoneID                  int32     `gorm:"column:PhoneId" json:"PhoneId"`
	FaxID                    int32     `gorm:"column:FaxId" json:"FaxId"`
	CreditLimit              float64   `gorm:"column:CreditLimit" json:"CreditLimit"`
	BillerID                 int32     `gorm:"column:BillerId" json:"BillerId"`
	BillerName               string    `gorm:"column:BillerName" json:"BillerName"`
	TradingTermID            int32     `gorm:"column:TradingTermId;not null" json:"TradingTermId"`
	Active                   bool      `gorm:"column:Active;not null" json:"Active"`
	CustomerSince            time.Time `gorm:"column:CustomerSince" json:"CustomerSince"`
	WebSite                  string    `gorm:"column:WebSite" json:"WebSite"`
	Email                    string    `gorm:"column:Email" json:"Email"`
	ABN                      string    `gorm:"column:ABN" json:"ABN"`
	StatementLastPrinted     time.Time `gorm:"column:StatementLastPrinted" json:"StatementLastPrinted"`
	OpeningBalance           float64   `gorm:"column:OpeningBalance;not null;default:0.00" json:"OpeningBalance"`
	RetentionAdjustment      float64   `gorm:"column:RetentionAdjustment;not null;default:0.00" json:"RetentionAdjustment"`
	Owing                    float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	ClientClassificationCode string    `gorm:"column:ClientClassificationCode" json:"ClientClassificationCode"`
	Circa                    time.Time `gorm:"column:Circa;not null" json:"Circa"`
	PrintStatement           bool      `gorm:"column:PrintStatement;not null" json:"PrintStatement"`
	CardID                   int32     `gorm:"column:CardId" json:"CardId"`
	CardHolder               string    `gorm:"column:CardHolder" json:"CardHolder"`
	CardNo                   string    `gorm:"column:CardNo" json:"CardNo"`
	CardExpiry               string    `gorm:"column:CardExpiry" json:"CardExpiry"`
	BatchChangeMerge         int32     `gorm:"column:BatchChangeMerge" json:"BatchChangeMerge"`
	BatchNewCode             string    `gorm:"column:BatchNewCode" json:"BatchNewCode"`
	InvoiceLayoutID          int32     `gorm:"column:InvoiceLayoutId" json:"InvoiceLayoutId"`
	JobLayoutID              int32     `gorm:"column:JobLayoutId" json:"JobLayoutId"`
	JobTypeID                int32     `gorm:"column:JobTypeId" json:"JobTypeId"`
	OrderWarning             bool      `gorm:"column:OrderWarning;not null" json:"OrderWarning"`
	ReferenceWarning         bool      `gorm:"column:ReferenceWarning;not null" json:"ReferenceWarning"`
	AccountID                int32     `gorm:"column:AccountId" json:"AccountId"`
	DivisionID               int32     `gorm:"column:DivisionId" json:"DivisionId"`
	BankID                   int32     `gorm:"column:BankId" json:"BankId"`
	AccountNo                string    `gorm:"column:AccountNo" json:"AccountNo"`
	AccountName              string    `gorm:"column:AccountName" json:"AccountName"`
	CCV                      string    `gorm:"column:CCV" json:"CCV"`
	PaymentMethodID          int32     `gorm:"column:PaymentMethodId" json:"PaymentMethodId"`
	EraID                    int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion              int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	AddressID                int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	BillingAddressID         int32     `gorm:"column:BillingAddressId;not null" json:"BillingAddressId"`
	IsEInvoiceEnabled        bool      `gorm:"column:IsEInvoiceEnabled;not null" json:"IsEInvoiceEnabled"`
}

// TableName Client's table name
func (*Client) TableName() string {
	return TableNameClient
}
