// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCorrespondence = "Correspondences"

// Correspondence mapped from table <Correspondences>
type Correspondence struct {
	CorrespondenceID int32  `gorm:"column:CorrespondenceId;primaryKey" json:"CorrespondenceId"`
	Path             string `gorm:"column:Path;not null" json:"Path"`
	Type             string `gorm:"column:Type;not null" json:"Type"`
	Description      string `gorm:"column:Description;not null" json:"Description"`
	EmailID          int32  `gorm:"column:EmailId" json:"EmailId"`
	FileID           int32  `gorm:"column:FileId" json:"FileId"`
}

// TableName Correspondence's table name
func (*Correspondence) TableName() string {
	return TableNameCorrespondence
}
