// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCostCentre = "CostCentres"

// CostCentre mapped from table <CostCentres>
type CostCentre struct {
	CostCentreID int32  `gorm:"column:CostCentreId;primaryKey;autoIncrement:true" json:"CostCentreId"`
	Code         string `gorm:"column:Code;not null" json:"Code"`
	FullCode     string `gorm:"column:FullCode;not null" json:"FullCode"`
	Description  string `gorm:"column:Description;not null" json:"Description"`
	RowID        int32  `gorm:"column:RowId;not null" json:"RowId"`
	ParentID     int32  `gorm:"column:ParentId" json:"ParentId"`
	Type         string `gorm:"column:Type" json:"Type"`
	Level        int32  `gorm:"column:Level;not null" json:"Level"`
	Obsolete     bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName CostCentre's table name
func (*CostCentre) TableName() string {
	return TableNameCostCentre
}
