// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCostCentreTemplate = "CostCentreTemplates"

// CostCentreTemplate mapped from table <CostCentreTemplates>
type CostCentreTemplate struct {
	CostCentreTemplateID int32  `gorm:"column:CostCentreTemplateId;primaryKey;autoIncrement:true" json:"CostCentreTemplateId"`
	Code                 string `gorm:"column:Code;not null" json:"Code"`
	Description          string `gorm:"column:Description;not null" json:"Description"`
}

// TableName CostCentreTemplate's table name
func (*CostCentreTemplate) TableName() string {
	return TableNameCostCentreTemplate
}
