// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCreditorsAgedTrialBalance = "CreditorsAgedTrialBalance"

// CreditorsAgedTrialBalance mapped from table <CreditorsAgedTrialBalance>
type CreditorsAgedTrialBalance struct {
	SupplierID       int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	SupplierCode     string    `gorm:"column:SupplierCode;not null" json:"SupplierCode"`
	SupplierName     string    `gorm:"column:SupplierName;not null" json:"SupplierName"`
	SupplierPhone    string    `gorm:"column:SupplierPhone" json:"SupplierPhone"`
	SupplierContacts string    `gorm:"column:SupplierContacts" json:"SupplierContacts"`
	PurchaseID       int32     `gorm:"column:PurchaseId" json:"PurchaseId"`
	Type             string    `gorm:"column:Type;not null" json:"Type"`
	ReferenceNo      string    `gorm:"column:ReferenceNo" json:"ReferenceNo"`
	InvoiceDueDate   time.Time `gorm:"column:InvoiceDueDate" json:"InvoiceDueDate"`
	InvoiceJobNo     string    `gorm:"column:InvoiceJobNo" json:"InvoiceJobNo"`
	Date             time.Time `gorm:"column:Date;not null" json:"Date"`
	Owing            float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	Amount           float64   `gorm:"column:Amount;not null;default:0.00" json:"Amount"`
	Amount00         float64   `gorm:"column:Amount00;not null;default:0.00" json:"Amount00"`
	Amount30         float64   `gorm:"column:Amount30;not null;default:0.00" json:"Amount30"`
	Amount60         float64   `gorm:"column:Amount60;not null;default:0.00" json:"Amount60"`
	Amount90         float64   `gorm:"column:Amount90;not null;default:0.00" json:"Amount90"`
}

// TableName CreditorsAgedTrialBalance's table name
func (*CreditorsAgedTrialBalance) TableName() string {
	return TableNameCreditorsAgedTrialBalance
}
