// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDebtorsAgedTrialBalance = "DebtorsAgedTrialBalance"

// DebtorsAgedTrialBalance mapped from table <DebtorsAgedTrialBalance>
type DebtorsAgedTrialBalance struct {
	ClientCode         string    `gorm:"column:ClientCode;not null" json:"ClientCode"`
	ClientName         string    `gorm:"column:ClientName;not null" json:"ClientName"`
	ClientPhone        string    `gorm:"column:ClientPhone" json:"ClientPhone"`
	ClientContacts     string    `gorm:"column:ClientContacts" json:"ClientContacts"`
	Type               string    `gorm:"column:Type;not null" json:"Type"`
	ReferenceNo        string    `gorm:"column:ReferenceNo" json:"ReferenceNo"`
	InvoiceID          int32     `gorm:"column:InvoiceId;not null" json:"InvoiceId"`
	InvoiceDueDate     time.Time `gorm:"column:InvoiceDueDate" json:"InvoiceDueDate"`
	InvoiceJobNo       string    `gorm:"column:InvoiceJobNo" json:"InvoiceJobNo"`
	InvoiceContactName string    `gorm:"column:InvoiceContactName" json:"InvoiceContactName"`
	InvoiceContact     string    `gorm:"column:InvoiceContact" json:"InvoiceContact"`
	Date               time.Time `gorm:"column:Date;not null" json:"Date"`
	Owing              float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	Amount             float64   `gorm:"column:Amount;not null;default:0.00" json:"Amount"`
	Amount00           float64   `gorm:"column:Amount00;not null;default:0.00" json:"Amount00"`
	Amount30           float64   `gorm:"column:Amount30;not null;default:0.00" json:"Amount30"`
	Amount60           float64   `gorm:"column:Amount60;not null;default:0.00" json:"Amount60"`
	Amount90           float64   `gorm:"column:Amount90;not null;default:0.00" json:"Amount90"`
}

// TableName DebtorsAgedTrialBalance's table name
func (*DebtorsAgedTrialBalance) TableName() string {
	return TableNameDebtorsAgedTrialBalance
}
