// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDeliveryItemsQuantity = "DeliveryItemsQuantity"

// DeliveryItemsQuantity mapped from table <DeliveryItemsQuantity>
type DeliveryItemsQuantity struct {
	DeliveryItemsQuantityID int32   `gorm:"column:DeliveryItemsQuantityId;primaryKey;autoIncrement:true" json:"DeliveryItemsQuantityId"`
	DeliveryItemID          int32   `gorm:"column:DeliveryItemId;not null" json:"DeliveryItemId"`
	RowID                   int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity                float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	JobID                   int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID            int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	StockLocationID         int32   `gorm:"column:StockLocationId" json:"StockLocationId"`
	OrderItemsQuantityID    int32   `gorm:"column:OrderItemsQuantityId" json:"OrderItemsQuantityId"`
}

// TableName DeliveryItemsQuantity's table name
func (*DeliveryItemsQuantity) TableName() string {
	return TableNameDeliveryItemsQuantity
}
