// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDelivery = "Delivery"

// Delivery mapped from table <Delivery>
type Delivery struct {
	DeliveryID     int32     `gorm:"column:DeliveryId;primaryKey;autoIncrement:true" json:"DeliveryId"`
	SupplierID     int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	DocketNo       string    `gorm:"column:DocketNo;not null" json:"DocketNo"`
	OrderID        int32     `gorm:"column:OrderId" json:"OrderId"`
	Date           time.Time `gorm:"column:Date;not null" json:"Date"`
	EraID          int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa          time.Time `gorm:"column:Circa;not null" json:"Circa"`
	OrderNo        string    `gorm:"column:OrderNo" json:"OrderNo"`
	Amount         float64   `gorm:"column:Amount" json:"Amount"`
	Jobs           string    `gorm:"column:Jobs" json:"Jobs"`
	StockLocations string    `gorm:"column:StockLocations" json:"StockLocations"`
	ProductCode    string    `gorm:"column:ProductCode" json:"ProductCode"`
	DataVersion    int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Delivery's table name
func (*Delivery) TableName() string {
	return TableNameDelivery
}
