// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDeliveryText = "DeliveryText"

// DeliveryText mapped from table <DeliveryText>
type DeliveryText struct {
	DeliveryTextID     int32  `gorm:"column:DeliveryTextId;primaryKey" json:"DeliveryTextId"`
	OrdersList         string `gorm:"column:OrdersList;not null" json:"OrdersList"`
	JobsList           string `gorm:"column:JobsList;not null" json:"JobsList"`
	StockLocationsList string `gorm:"column:StockLocationsList;not null" json:"StockLocationsList"`
}

// TableName DeliveryText's table name
func (*DeliveryText) TableName() string {
	return TableNameDeliveryText
}
