// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDeliveryItem = "DeliveryItems"

// DeliveryItem mapped from table <DeliveryItems>
type DeliveryItem struct {
	DeliveryItemID  int32   `gorm:"column:DeliveryItemId;primaryKey;autoIncrement:true" json:"DeliveryItemId"`
	DeliveryID      int32   `gorm:"column:DeliveryId;not null" json:"DeliveryId"`
	RowID           int32   `gorm:"column:RowId;not null" json:"RowId"`
	Reference       string  `gorm:"column:Reference;not null" json:"Reference"`
	Description     string  `gorm:"column:Description;not null" json:"Description"`
	UnitID          int32   `gorm:"column:UnitId;not null" json:"UnitId"`
	UnitCost        float64 `gorm:"column:UnitCost;not null;default:0.0000" json:"UnitCost"`
	Cost            float64 `gorm:"column:Cost;not null" json:"Cost"`
	PricebookID     int32   `gorm:"column:PricebookId" json:"PricebookId"`
	PackageID       int32   `gorm:"column:PackageId" json:"PackageId"`
	PackageQuantity float64 `gorm:"column:PackageQuantity" json:"PackageQuantity"`
	ProductCode     string  `gorm:"column:ProductCode" json:"ProductCode"`
	Quantity        float64 `gorm:"column:Quantity" json:"Quantity"`
}

// TableName DeliveryItem's table name
func (*DeliveryItem) TableName() string {
	return TableNameDeliveryItem
}
