// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDepartment = "Departments"

// Department mapped from table <Departments>
type Department struct {
	DepartmentID int32  `gorm:"column:DepartmentId;primaryKey;autoIncrement:true" json:"DepartmentId"`
	Code         string `gorm:"column:Code;not null" json:"Code"`
	Description  string `gorm:"column:Description;not null" json:"Description"`
	Obsolete     bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
