// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDetailClause = "DetailClauses"

// DetailClause mapped from table <DetailClauses>
type DetailClause struct {
	DetailClauseID int32  `gorm:"column:DetailClauseId;primaryKey;autoIncrement:true" json:"DetailClauseId"`
	Code           string `gorm:"column:Code;not null" json:"Code"`
	Description    string `gorm:"column:Description;not null" json:"Description"`
	Obsolete       bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName DetailClause's table name
func (*DetailClause) TableName() string {
	return TableNameDetailClause
}
