// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDivision = "Divisions"

// Division mapped from table <Divisions>
type Division struct {
	DivisionID  int32  `gorm:"column:DivisionId;primaryKey;autoIncrement:true" json:"DivisionId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Heading     string `gorm:"column:Heading;not null" json:"Heading"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Division's table name
func (*Division) TableName() string {
	return TableNameDivision
}
