// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDivisionAccountTransaction = "DivisionAccountTransactions"

// DivisionAccountTransaction mapped from table <DivisionAccountTransactions>
type DivisionAccountTransaction struct {
	ID          int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Scope       string  `gorm:"column:Scope;not null" json:"Scope"`
	Owner       string  `gorm:"column:Owner;not null" json:"Owner"`
	DivisionID  int32   `gorm:"column:DivisionId" json:"DivisionId"`
	AccountID   int32   `gorm:"column:AccountId;not null" json:"AccountId"`
	Type        string  `gorm:"column:Type;not null" json:"Type"`
	ReferenceID int32   `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	Debit       float64 `gorm:"column:Debit;not null;default:0.00" json:"Debit"`
	Credit      float64 `gorm:"column:Credit;not null;default:0.00" json:"Credit"`
}

// TableName DivisionAccountTransaction's table name
func (*DivisionAccountTransaction) TableName() string {
	return TableNameDivisionAccountTransaction
}
