// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDowntimeLabourRate = "DowntimeLabourRates"

// DowntimeLabourRate mapped from table <DowntimeLabourRates>
type DowntimeLabourRate struct {
	DowntimeLabourRatesID int32 `gorm:"column:DowntimeLabourRatesId;primaryKey;autoIncrement:true" json:"DowntimeLabourRatesId"`
	LabourRateID          int32 `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
}

// TableName DowntimeLabourRate's table name
func (*DowntimeLabourRate) TableName() string {
	return TableNameDowntimeLabourRate
}
