// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEInvoiceEntity = "EInvoiceEntity"

// EInvoiceEntity mapped from table <EInvoiceEntity>
type EInvoiceEntity struct {
	ID                     int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	CompanyName            string    `gorm:"column:CompanyName;not null" json:"CompanyName"`
	IsPublic               bool      `gorm:"column:IsPublic;not null" json:"IsPublic"`
	IsPurchaseAutoApproved bool      `gorm:"column:IsPurchaseAutoApproved;not null" json:"IsPurchaseAutoApproved"`
	PeppolScheme           string    `gorm:"column:PeppolScheme;not null" json:"PeppolScheme"`
	UpdatedAt              time.Time `gorm:"column:UpdatedAt;not null" json:"UpdatedAt"`
	RegisteredAt           time.Time `gorm:"column:RegisteredAt" json:"RegisteredAt"`
	AddressID              int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	ABN                    string    `gorm:"column:ABN;not null" json:"ABN"`
}

// TableName EInvoiceEntity's table name
func (*EInvoiceEntity) TableName() string {
	return TableNameEInvoiceEntity
}
