// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmailAuditDocument = "EmailAuditDocuments"

// EmailAuditDocument mapped from table <EmailAuditDocuments>
type EmailAuditDocument struct {
	EmailAuditDocumentID int32 `gorm:"column:EmailAuditDocumentId;primaryKey;autoIncrement:true" json:"EmailAuditDocumentId"`
	EmailID              int32 `gorm:"column:EmailId;not null" json:"EmailId"`
	AuditID              int32 `gorm:"column:AuditId;not null" json:"AuditId"`
}

// TableName EmailAuditDocument's table name
func (*EmailAuditDocument) TableName() string {
	return TableNameEmailAuditDocument
}
