// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmailAttachment = "EmailAttachments"

// EmailAttachment mapped from table <EmailAttachments>
type EmailAttachment struct {
	EmailAttachmentID int32  `gorm:"column:EmailAttachmentId;primaryKey;autoIncrement:true" json:"EmailAttachmentId"`
	EmailID           int32  `gorm:"column:EmailId;not null" json:"EmailId"`
	FileID            int32  `gorm:"column:FileId;not null" json:"FileId"`
	Description       string `gorm:"column:Description" json:"Description"`
}

// TableName EmailAttachment's table name
func (*EmailAttachment) TableName() string {
	return TableNameEmailAttachment
}
