// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmailAccount = "EmailAccounts"

// EmailAccount mapped from table <EmailAccounts>
type EmailAccount struct {
	AccountID       int32  `gorm:"column:AccountId;primaryKey;autoIncrement:true" json:"AccountId"`
	Address         string `gorm:"column:Address;not null" json:"Address"`
	DisplayName     string `gorm:"column:DisplayName;not null" json:"DisplayName"`
	UserName        string `gorm:"column:UserName;not null" json:"UserName"`
	PasswordHash    string `gorm:"column:PasswordHash;not null" json:"PasswordHash"`
	PasswordIV      string `gorm:"column:PasswordIV;not null" json:"PasswordIV"`
	Host            string `gorm:"column:Host;not null" json:"Host"`
	Signature       string `gorm:"column:Signature" json:"Signature"`
	Port            int32  `gorm:"column:Port;not null" json:"Port"`
	SslOption       string `gorm:"column:SslOption;not null" json:"SslOption"`
	ServiceProvider string `gorm:"column:ServiceProvider" json:"ServiceProvider"`
	DataVersion     int32  `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName EmailAccount's table name
func (*EmailAccount) TableName() string {
	return TableNameEmailAccount
}
