// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmail = "Email"

// Email mapped from table <Email>
type Email struct {
	EmailID     int32     `gorm:"column:EmailId;primaryKey;autoIncrement:true" json:"EmailId"`
	UserID      int32     `gorm:"column:UserId;not null" json:"UserId"`
	To          string    `gorm:"column:To;not null" json:"To"`
	Body        string    `gorm:"column:Body" json:"Body"`
	Subject     string    `gorm:"column:Subject;not null" json:"Subject"`
	FromAddress string    `gorm:"column:FromAddress;not null" json:"FromAddress"`
	FromDisplay string    `gorm:"column:FromDisplay;not null" json:"FromDisplay"`
	Username    string    `gorm:"column:Username;not null" json:"Username"`
	Host        string    `gorm:"column:Host;not null" json:"Host"`
	Attachments string    `gorm:"column:Attachments;not null" json:"Attachments"`
	ErrorMsg    string    `gorm:"column:ErrorMsg;not null" json:"ErrorMsg"`
	DateCreated time.Time `gorm:"column:DateCreated;not null" json:"DateCreated"`
	Circa       time.Time `gorm:"column:Circa;not null" json:"Circa"`
	TableName_  string    `gorm:"column:TableName;not null" json:"TableName"`
	Path        string    `gorm:"column:Path;not null" json:"Path"`
	TableKeyID  int32     `gorm:"column:TableKeyId;not null" json:"TableKeyId"`
	Cc          string    `gorm:"column:Cc" json:"Cc"`
	Bcc         string    `gorm:"column:Bcc" json:"Bcc"`
}

// TableName Email's table name
func (*Email) TableName() string {
	return TableNameEmail
}
