// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmailTemplate = "EmailTemplates"

// EmailTemplate mapped from table <EmailTemplates>
type EmailTemplate struct {
	EmailTemplateID int32  `gorm:"column:EmailTemplateId;primaryKey;autoIncrement:true" json:"EmailTemplateId"`
	Subject         string `gorm:"column:Subject;not null" json:"Subject"`
	Body            string `gorm:"column:Body;not null" json:"Body"`
	FromAddress     string `gorm:"column:FromAddress;not null" json:"FromAddress"`
}

// TableName EmailTemplate's table name
func (*EmailTemplate) TableName() string {
	return TableNameEmailTemplate
}
