// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmployeeTimesheet = "EmployeeTimesheets"

// EmployeeTimesheet mapped from table <EmployeeTimesheets>
type EmployeeTimesheet struct {
	EmployeeTimesheetID int32     `gorm:"column:EmployeeTimesheetId;primaryKey;autoIncrement:true" json:"EmployeeTimesheetId"`
	EmployeeID          int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	Date                time.Time `gorm:"column:Date;not null" json:"Date"`
	StartTime           string    `gorm:"column:StartTime" json:"StartTime"`
	FinishTime          string    `gorm:"column:FinishTime" json:"FinishTime"`
	Hours               float64   `gorm:"column:Hours;not null;default:0.0000" json:"Hours"`
	Jobs                string    `gorm:"column:Jobs;not null" json:"Jobs"`
	Status              string    `gorm:"column:Status;not null" json:"Status"`
	EraID               int32     `gorm:"column:EraId;not null" json:"EraId"`
	Circa               time.Time `gorm:"column:Circa;not null" json:"Circa"`
}

// TableName EmployeeTimesheet's table name
func (*EmployeeTimesheet) TableName() string {
	return TableNameEmployeeTimesheet
}
