// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeWorkHour = "EmployeeWorkHours"

// EmployeeWorkHour mapped from table <EmployeeWorkHours>
type EmployeeWorkHour struct {
	EmployeeWorkHoursID int32  `gorm:"column:EmployeeWorkHoursId;primaryKey;autoIncrement:true" json:"EmployeeWorkHoursId"`
	EmployeeID          int32  `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	DayOfWeek           int32  `gorm:"column:DayOfWeek;not null" json:"DayOfWeek"`
	Start               string `gorm:"column:Start;not null" json:"Start"`
	Finish              string `gorm:"column:Finish;not null" json:"Finish"`
	Break               int32  `gorm:"column:Break" json:"Break"`
}

// TableName EmployeeWorkHour's table name
func (*EmployeeWorkHour) TableName() string {
	return TableNameEmployeeWorkHour
}
