// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeContact = "EmployeeContacts"

// EmployeeContact mapped from table <EmployeeContacts>
type EmployeeContact struct {
	EmployeeContactID     int32  `gorm:"column:EmployeeContactId;primaryKey;autoIncrement:true" json:"EmployeeContactId"`
	EmployeeID            int32  `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	Title                 string `gorm:"column:Title;not null" json:"Title"`
	FirstName             string `gorm:"column:FirstName;not null" json:"FirstName"`
	Surname               string `gorm:"column:Surname;not null" json:"Surname"`
	Phone                 string `gorm:"column:Phone;not null" json:"Phone"`
	Email                 string `gorm:"column:Email" json:"Email"`
	NextofKinRelationship string `gorm:"column:NextofKinRelationship;not null" json:"NextofKinRelationship"`
	RowID                 int32  `gorm:"column:RowId;not null" json:"RowId"`
}

// TableName EmployeeContact's table name
func (*EmployeeContact) TableName() string {
	return TableNameEmployeeContact
}
