// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmployeeLicence = "EmployeeLicences"

// EmployeeLicence mapped from table <EmployeeLicences>
type EmployeeLicence struct {
	EmployeeLicencesID int32     `gorm:"column:EmployeeLicencesId;primaryKey;autoIncrement:true" json:"EmployeeLicencesId"`
	EmployeeID         int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	LicenceID          int32     `gorm:"column:LicenceId;not null" json:"LicenceId"`
	LicenceNo          string    `gorm:"column:LicenceNo" json:"LicenceNo"`
	Expiry             time.Time `gorm:"column:Expiry;not null" json:"Expiry"`
	Details            string    `gorm:"column:Details;not null" json:"Details"`
	Comments           string    `gorm:"column:Comments;not null" json:"Comments"`
	Obsolete           bool      `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName EmployeeLicence's table name
func (*EmployeeLicence) TableName() string {
	return TableNameEmployeeLicence
}
