// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeLabourRate = "EmployeeLabourRates"

// EmployeeLabourRate mapped from table <EmployeeLabourRates>
type EmployeeLabourRate struct {
	EmployeeLabourRateID int32 `gorm:"column:EmployeeLabourRateId;primaryKey;autoIncrement:true" json:"EmployeeLabourRateId"`
	EmployeeID           int32 `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	LabourRateID         int32 `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
}

// TableName EmployeeLabourRate's table name
func (*EmployeeLabourRate) TableName() string {
	return TableNameEmployeeLabourRate
}
