// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeSkill = "EmployeeSkills"

// EmployeeSkill mapped from table <EmployeeSkills>
type EmployeeSkill struct {
	EmployeeSkillID int32  `gorm:"column:EmployeeSkillId;primaryKey;autoIncrement:true" json:"EmployeeSkillId"`
	EmployeeID      int32  `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	SkillID         int32  `gorm:"column:SkillId;not null" json:"SkillId"`
	LicenceNo       string `gorm:"column:LicenceNo" json:"LicenceNo"`
}

// TableName EmployeeSkill's table name
func (*EmployeeSkill) TableName() string {
	return TableNameEmployeeSkill
}
