// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeOnCost = "EmployeeOnCosts"

// EmployeeOnCost mapped from table <EmployeeOnCosts>
type EmployeeOnCost struct {
	EmployeeOnCostsID int32   `gorm:"column:EmployeeOnCostsId;primaryKey;autoIncrement:true" json:"EmployeeOnCostsId"`
	EmployeeID        int32   `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	PayrollTimeTypeID int32   `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	Rate              float64 `gorm:"column:Rate;not null" json:"Rate"`
	Retail            float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName EmployeeOnCost's table name
func (*EmployeeOnCost) TableName() string {
	return TableNameEmployeeOnCost
}
