// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeSetting = "EmployeeSettings"

// EmployeeSetting mapped from table <EmployeeSettings>
type EmployeeSetting struct {
	EmployeeSettingID       int32   `gorm:"column:EmployeeSettingId;primaryKey;autoIncrement:true" json:"EmployeeSettingId"`
	PayrollTax              float64 `gorm:"column:PayrollTax;not null" json:"PayrollTax"`
	Superannuation          float64 `gorm:"column:Superannuation;not null" json:"Superannuation"`
	AnnualLeaveLoading      float64 `gorm:"column:AnnualLeaveLoading;not null" json:"AnnualLeaveLoading"`
	LongServiceLeaveAccrual float64 `gorm:"column:LongServiceLeaveAccrual;not null" json:"LongServiceLeaveAccrual"`
	WorkersCompensation     float64 `gorm:"column:WorkersCompensation;not null" json:"WorkersCompensation"`
	EmployeeProductivity    float64 `gorm:"column:EmployeeProductivity;not null" json:"EmployeeProductivity"`
}

// TableName EmployeeSetting's table name
func (*EmployeeSetting) TableName() string {
	return TableNameEmployeeSetting
}
