// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmployee = "Employees"

// Employee mapped from table <Employees>
type Employee struct {
	EmployeeID                      int32     `gorm:"column:EmployeeId;primaryKey;autoIncrement:true" json:"EmployeeId"`
	Code                            string    `gorm:"column:Code;not null" json:"Code"`
	PreferredName                   string    `gorm:"column:PreferredName;not null" json:"PreferredName"`
	FirstName                       string    `gorm:"column:FirstName;not null" json:"FirstName"`
	Surname                         string    `gorm:"column:Surname;not null" json:"Surname"`
	MiddleNames                     string    `gorm:"column:MiddleNames;not null" json:"MiddleNames"`
	TitleID                         int32     `gorm:"column:TitleId;not null" json:"TitleId"`
	WorkPhoneID                     int32     `gorm:"column:WorkPhoneId" json:"WorkPhoneId"`
	HomePhoneID                     int32     `gorm:"column:HomePhoneId" json:"HomePhoneId"`
	OccupationID                    int32     `gorm:"column:OccupationId;not null" json:"OccupationId"`
	DateOfBirth                     time.Time `gorm:"column:DateOfBirth" json:"DateOfBirth"`
	Sex                             string    `gorm:"column:Sex;not null" json:"Sex"`
	StartDate                       time.Time `gorm:"column:StartDate" json:"StartDate"`
	EndDate                         time.Time `gorm:"column:EndDate" json:"EndDate"`
	Email                           string    `gorm:"column:Email" json:"Email"`
	EmailVerified                   bool      `gorm:"column:EmailVerified;not null" json:"EmailVerified"`
	EmailVerificationToken          string    `gorm:"column:EmailVerificationToken" json:"EmailVerificationToken"`
	EmailVerificationTokenCreatedAt time.Time `gorm:"column:EmailVerificationTokenCreatedAt" json:"EmailVerificationTokenCreatedAt"`
	PrivateEmail                    string    `gorm:"column:PrivateEmail" json:"PrivateEmail"`
	LabourRateID                    int32     `gorm:"column:LabourRateId" json:"LabourRateId"`
	IdentificationTag               string    `gorm:"column:IdentificationTag" json:"IdentificationTag"`
	Circa                           time.Time `gorm:"column:Circa;not null" json:"Circa"`
	Picture                         string    `gorm:"column:Picture" json:"Picture"`
	DivisionID                      int32     `gorm:"column:DivisionId" json:"DivisionId"`
	Status                          string    `gorm:"column:Status;not null" json:"Status"`
	PortableLeaveNo                 string    `gorm:"column:PortableLeaveNo" json:"PortableLeaveNo"`
	BloodType                       string    `gorm:"column:BloodType" json:"BloodType"`
	CheckLicenceExpiry              bool      `gorm:"column:CheckLicenceExpiry;not null" json:"CheckLicenceExpiry"`
	Apprentice                      bool      `gorm:"column:Apprentice;not null" json:"Apprentice"`
	Subcontractor                   bool      `gorm:"column:Subcontractor;not null" json:"Subcontractor"`
	ExcludeFromSchedule             bool      `gorm:"column:ExcludeFromSchedule;not null" json:"ExcludeFromSchedule"`
	VehicleID                       int32     `gorm:"column:VehicleId" json:"VehicleId"`
	DepartmentID                    int32     `gorm:"column:DepartmentId" json:"DepartmentId"`
	PositionID                      int32     `gorm:"column:PositionId" json:"PositionId"`
	ReportsToID                     int32     `gorm:"column:ReportsToId" json:"ReportsToId"`
	WorkSiteID                      int32     `gorm:"column:WorkSiteId" json:"WorkSiteId"`
	CalendarRegionID                int32     `gorm:"column:CalendarRegionId" json:"CalendarRegionId"`
	RosterPayrollTimeTypeID         int32     `gorm:"column:RosterPayrollTimeTypeId" json:"RosterPayrollTimeTypeId"`
	RosterStartDate                 time.Time `gorm:"column:RosterStartDate" json:"RosterStartDate"`
	JobID                           int32     `gorm:"column:JobId" json:"JobId"`
	CostCentreID                    int32     `gorm:"column:CostCentreId" json:"CostCentreId"`
	UseCalendarWorkHours            bool      `gorm:"column:UseCalendarWorkHours;not null;default:1" json:"UseCalendarWorkHours"`
	EraID                           int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	PayrollHours                    float64   `gorm:"column:PayrollHours;default:0.0000" json:"PayrollHours"`
	DataVersion                     int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	AddressID                       int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	Expatriate                      bool      `gorm:"column:Expatriate;not null" json:"Expatriate"`
	Attributes                      string    `gorm:"column:Attributes" json:"Attributes"`
	UncommittedID                   int32     `gorm:"column:UncommittedId" json:"UncommittedId"`
	SystemPublished                 bool      `gorm:"column:SystemPublished" json:"SystemPublished"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
