// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmployeeChecklist = "EmployeeChecklists"

// EmployeeChecklist mapped from table <EmployeeChecklists>
type EmployeeChecklist struct {
	EmployeeChecklistID int32     `gorm:"column:EmployeeChecklistId;primaryKey;autoIncrement:true" json:"EmployeeChecklistId"`
	EmployeeID          int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	ChecklistID         int32     `gorm:"column:ChecklistId;not null" json:"ChecklistId"`
	Reference           string    `gorm:"column:Reference;not null" json:"Reference"`
	Details             string    `gorm:"column:Details;not null" json:"Details"`
	Complete            time.Time `gorm:"column:Complete" json:"Complete"`
}

// TableName EmployeeChecklist's table name
func (*EmployeeChecklist) TableName() string {
	return TableNameEmployeeChecklist
}
