// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeesCostofEmployment = "EmployeesCostofEmployment"

// EmployeesCostofEmployment mapped from table <EmployeesCostofEmployment>
type EmployeesCostofEmployment struct {
	EmployeesCostofEmploymentID int32   `gorm:"column:EmployeesCostofEmploymentId;primaryKey" json:"EmployeesCostofEmploymentId"`
	AnnualWage                  float64 `gorm:"column:AnnualWage;not null;default:0.00" json:"AnnualWage"`
	AnnualAllowances            float64 `gorm:"column:AnnualAllowances;not null;default:0.00" json:"AnnualAllowances"`
	AnnualOvertime              float64 `gorm:"column:AnnualOvertime;not null;default:0.00" json:"AnnualOvertime"`
	PayrollTax                  float64 `gorm:"column:PayrollTax;not null;default:0.00" json:"PayrollTax"`
	HolidayLoading              float64 `gorm:"column:HolidayLoading;not null;default:0.00" json:"HolidayLoading"`
	WorkersComp                 float64 `gorm:"column:WorkersComp;not null;default:0.00" json:"WorkersComp"`
	BaseSuper                   float64 `gorm:"column:BaseSuper;not null;default:0.00" json:"BaseSuper"`
	LongServiceProvision        float64 `gorm:"column:LongServiceProvision;not null;default:0.00" json:"LongServiceProvision"`
	OtherProvisions             float64 `gorm:"column:OtherProvisions;not null;default:0.00" json:"OtherProvisions"`
	HoursWorked                 float64 `gorm:"column:HoursWorked;not null;default:0.00" json:"HoursWorked"`
	AnnualLeave                 float64 `gorm:"column:AnnualLeave;not null;default:0.00" json:"AnnualLeave"`
	PublicHolidays              float64 `gorm:"column:PublicHolidays;not null;default:0.00" json:"PublicHolidays"`
	SickLeave                   float64 `gorm:"column:SickLeave;not null;default:0.00" json:"SickLeave"`
	OtherLeave                  float64 `gorm:"column:OtherLeave;not null;default:0.00" json:"OtherLeave"`
	ActualLabourCostRate        float64 `gorm:"column:ActualLabourCostRate;not null;default:0.00" json:"ActualLabourCostRate"`
	ChargeableHours             float64 `gorm:"column:ChargeableHours;not null;default:0.00" json:"ChargeableHours"`
	BaseLabourRate              float64 `gorm:"column:BaseLabourRate;not null;default:0.00" json:"BaseLabourRate"`
	WagesSource                 string  `gorm:"column:WagesSource;not null" json:"WagesSource"`
	WagesCycle                  string  `gorm:"column:WagesCycle;not null" json:"WagesCycle"`
}

// TableName EmployeesCostofEmployment's table name
func (*EmployeesCostofEmployment) TableName() string {
	return TableNameEmployeesCostofEmployment
}
