// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmployeeTimesheetItem = "EmployeeTimesheetItems"

// EmployeeTimesheetItem mapped from table <EmployeeTimesheetItems>
type EmployeeTimesheetItem struct {
	EmployeeTimesheetItemID int32   `gorm:"column:EmployeeTimesheetItemId;primaryKey;autoIncrement:true" json:"EmployeeTimesheetItemId"`
	EmployeeTimesheetID     int32   `gorm:"column:EmployeeTimesheetId;not null" json:"EmployeeTimesheetId"`
	LabourRateID            int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	Details                 string  `gorm:"column:Details;not null" json:"Details"`
	JobID                   int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID            int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	StartTime               string  `gorm:"column:StartTime;not null" json:"StartTime"`
	FinishTime              string  `gorm:"column:FinishTime;not null" json:"FinishTime"`
	Hours                   float64 `gorm:"column:Hours;not null;default:0.0000" json:"Hours"`
}

// TableName EmployeeTimesheetItem's table name
func (*EmployeeTimesheetItem) TableName() string {
	return TableNameEmployeeTimesheetItem
}
