// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEmployeeEmploymentHistory = "EmployeeEmploymentHistories"

// EmployeeEmploymentHistory mapped from table <EmployeeEmploymentHistories>
type EmployeeEmploymentHistory struct {
	ID                int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	EmployeeID        int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	EmploymentStatus  string    `gorm:"column:EmploymentStatus;not null" json:"EmploymentStatus"`
	IsApprentice      bool      `gorm:"column:IsApprentice;not null" json:"IsApprentice"`
	IsSubcontractor   bool      `gorm:"column:IsSubcontractor;not null" json:"IsSubcontractor"`
	EffectiveAt       time.Time `gorm:"column:EffectiveAt;not null" json:"EffectiveAt"`
	LastDay           time.Time `gorm:"column:LastDay" json:"LastDay"`
	TerminatedAt      time.Time `gorm:"column:TerminatedAt" json:"TerminatedAt"`
	TerminationReason string    `gorm:"column:TerminationReason" json:"TerminationReason"`
	NoticeGivenAt     time.Time `gorm:"column:NoticeGivenAt" json:"NoticeGivenAt"`
	NoticeAuthorised  bool      `gorm:"column:NoticeAuthorised" json:"NoticeAuthorised"`
	YearsOfService    int32     `gorm:"column:YearsOfService" json:"YearsOfService"`
	AgeOnLastDay      int32     `gorm:"column:AgeOnLastDay" json:"AgeOnLastDay"`
	Note              string    `gorm:"column:Note" json:"Note"`
}

// TableName EmployeeEmploymentHistory's table name
func (*EmployeeEmploymentHistory) TableName() string {
	return TableNameEmployeeEmploymentHistory
}
