// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEntitySetting = "EntitySettings"

// EntitySetting mapped from table <EntitySettings>
type EntitySetting struct {
	EntitySettingID           int32     `gorm:"column:EntitySettingId;primaryKey" json:"EntitySettingId"`
	PayerBankID               int32     `gorm:"column:PayerBankId" json:"PayerBankId"`
	PayerUserNo               string    `gorm:"column:PayerUserNo;not null" json:"PayerUserNo"`
	PayerUserName             string    `gorm:"column:PayerUserName;not null" json:"PayerUserName"`
	TraceBankID               int32     `gorm:"column:TraceBankId" json:"TraceBankId"`
	TraceAccountNo            string    `gorm:"column:TraceAccountNo;not null" json:"TraceAccountNo"`
	TraceAccountName          string    `gorm:"column:TraceAccountName;not null" json:"TraceAccountName"`
	TraceRemitterName         string    `gorm:"column:TraceRemitterName;not null" json:"TraceRemitterName"`
	EFTPath                   string    `gorm:"column:EFTPath;not null" json:"EFTPath"`
	EFTSelfBalance            string    `gorm:"column:EFTSelfBalance;not null" json:"EFTSelfBalance"`
	PaygwSupplierName         string    `gorm:"column:PaygwSupplierName;not null" json:"PaygwSupplierName"`
	PaygwContact              string    `gorm:"column:PaygwContact;not null" json:"PaygwContact"`
	GSTTypeDebtors            string    `gorm:"column:GSTTypeDebtors;not null" json:"GSTTypeDebtors"`
	GSTTypeCreditors          string    `gorm:"column:GSTTypeCreditors;not null" json:"GSTTypeCreditors"`
	GSTTypeReceipts           string    `gorm:"column:GSTTypeReceipts;not null" json:"GSTTypeReceipts"`
	GSTTypePayments           string    `gorm:"column:GSTTypePayments;not null" json:"GSTTypePayments"`
	BASFormType               string    `gorm:"column:BASFormType;not null" json:"BASFormType"`
	BASGSTOption              string    `gorm:"column:BASGSTOption;not null" json:"BASGSTOption"`
	BASPAYGOption             string    `gorm:"column:BASPAYGOption;not null" json:"BASPAYGOption"`
	BASMethod                 string    `gorm:"column:BASMethod;not null" json:"BASMethod"`
	BASFrequency              string    `gorm:"column:BASFrequency;not null" json:"BASFrequency"`
	BAST2                     float64   `gorm:"column:BAST2" json:"BAST2"`
	BASLastStatementDate      time.Time `gorm:"column:BASLastStatementDate" json:"BASLastStatementDate"`
	BASMonthlyPAYGWithholding bool      `gorm:"column:BASMonthlyPAYGWithholding;not null" json:"BASMonthlyPAYGWithholding"`
	BASWithholdingW1Only      bool      `gorm:"column:BASWithholdingW1Only;not null" json:"BASWithholdingW1Only"`
	IASFormType               string    `gorm:"column:IASFormType;not null" json:"IASFormType"`
	NextIASDate               time.Time `gorm:"column:NextIASDate" json:"NextIASDate"`
	HourUnitID                int32     `gorm:"column:HourUnitId" json:"HourUnitId"`
	IASPeriodClosed           time.Time `gorm:"column:IASPeriodClosed" json:"IASPeriodClosed"`
}

// TableName EntitySetting's table name
func (*EntitySetting) TableName() string {
	return TableNameEntitySetting
}
