// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEntity = "Entity"

// Entity mapped from table <Entity>
type Entity struct {
	EntityID                  int32     `gorm:"column:EntityId;primaryKey;autoIncrement:true" json:"EntityId"`
	Code                      string    `gorm:"column:Code;not null" json:"Code"`
	TradingName               string    `gorm:"column:TradingName;not null" json:"TradingName"`
	SubscriptionID            int32     `gorm:"column:SubscriptionId;not null" json:"SubscriptionId"`
	SubscriptionKey           string    `gorm:"column:SubscriptionKey" json:"SubscriptionKey"`
	SubscriptionUsers         int32     `gorm:"column:SubscriptionUsers" json:"SubscriptionUsers"`
	SubscriptionEmployees     int32     `gorm:"column:SubscriptionEmployees" json:"SubscriptionEmployees"`
	SubscriptionEdition       string    `gorm:"column:SubscriptionEdition" json:"SubscriptionEdition"`
	SubscriptionType          string    `gorm:"column:SubscriptionType" json:"SubscriptionType"`
	SubscriptionExpiry        time.Time `gorm:"column:SubscriptionExpiry" json:"SubscriptionExpiry"`
	PhoneID                   int32     `gorm:"column:PhoneId" json:"PhoneId"`
	FaxID                     int32     `gorm:"column:FaxId" json:"FaxId"`
	FiscalYearEnding          int32     `gorm:"column:FiscalYearEnding;not null" json:"FiscalYearEnding"`
	FiscalCloseOff            time.Time `gorm:"column:FiscalCloseOff;not null" json:"FiscalCloseOff"`
	CurrentMonth              string    `gorm:"column:CurrentMonth;not null" json:"CurrentMonth"`
	CurrentYear               int32     `gorm:"column:CurrentYear" json:"CurrentYear"`
	AcnNumber                 string    `gorm:"column:AcnNumber;not null" json:"AcnNumber"`
	LicenseNumber             string    `gorm:"column:LicenseNumber;not null" json:"LicenseNumber"`
	Email                     string    `gorm:"column:Email;not null" json:"Email"`
	WebSite                   string    `gorm:"column:WebSite;not null" json:"WebSite"`
	Theme                     string    `gorm:"column:Theme;not null" json:"Theme"`
	AccountCloseoffDate       time.Time `gorm:"column:AccountCloseoffDate" json:"AccountCloseoffDate"`
	ForceCurrentMonth         bool      `gorm:"column:ForceCurrentMonth;not null" json:"ForceCurrentMonth"`
	ABN                       string    `gorm:"column:ABN;not null" json:"ABN"`
	ArchiveYear               int32     `gorm:"column:ArchiveYear" json:"ArchiveYear"`
	CloseJobCosts             time.Time `gorm:"column:CloseJobCosts" json:"CloseJobCosts"`
	ReadOnly                  bool      `gorm:"column:ReadOnly" json:"ReadOnly"`
	CreditorCloseOff          time.Time `gorm:"column:CreditorCloseOff" json:"CreditorCloseOff"`
	DebtorCloseOff            time.Time `gorm:"column:DebtorCloseOff" json:"DebtorCloseOff"`
	SubDomain                 string    `gorm:"column:SubDomain;not null" json:"SubDomain"`
	PayrollCloseOff           time.Time `gorm:"column:PayrollCloseOff;not null" json:"PayrollCloseOff"`
	PayrollRegisteredEmployer string    `gorm:"column:PayrollRegisteredEmployer;not null" json:"PayrollRegisteredEmployer"`
	Colour                    string    `gorm:"column:Colour;not null" json:"Colour"`
	BackgroundColour          string    `gorm:"column:BackgroundColour;not null" json:"BackgroundColour"`
	CustomerID                int32     `gorm:"column:CustomerId;not null" json:"CustomerId"`
	DropMenuResolutionWidth   int32     `gorm:"column:DropMenuResolutionWidth" json:"DropMenuResolutionWidth"`
	RecentReportDays          int32     `gorm:"column:RecentReportDays;not null;default:7" json:"RecentReportDays"`
	PageLeftJustified         bool      `gorm:"column:PageLeftJustified;not null" json:"PageLeftJustified"`
	ESSStartUpBusiness        bool      `gorm:"column:ESSStartUpBusiness;not null" json:"ESSStartUpBusiness"`
	GoogleEmailAddress        string    `gorm:"column:GoogleEmailAddress" json:"GoogleEmailAddress"`
	DisableGridEditMessage    bool      `gorm:"column:DisableGridEditMessage;not null" json:"DisableGridEditMessage"`
	AddressID                 int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	PostalAddressID           int32     `gorm:"column:PostalAddressId;not null" json:"PostalAddressId"`
	CalendarRegionID          int32     `gorm:"column:CalendarRegionId;not null" json:"CalendarRegionId"`
}

// TableName Entity's table name
func (*Entity) TableName() string {
	return TableNameEntity
}
