// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEstimate = "Estimates"

// Estimate mapped from table <Estimates>
type Estimate struct {
	EstimateID                int32     `gorm:"column:EstimateId;primaryKey;autoIncrement:true" json:"EstimateId"`
	Code                      string    `gorm:"column:Code;not null" json:"Code"`
	Description               string    `gorm:"column:Description;not null" json:"Description"`
	Date                      time.Time `gorm:"column:Date;not null" json:"Date"`
	ClientID                  int32     `gorm:"column:ClientId" json:"ClientId"`
	PhoneID                   int32     `gorm:"column:PhoneId" json:"PhoneId"`
	Email                     string    `gorm:"column:Email;not null" json:"Email"`
	FaxID                     int32     `gorm:"column:FaxId" json:"FaxId"`
	RequiredDate              time.Time `gorm:"column:RequiredDate" json:"RequiredDate"`
	FinishDate                time.Time `gorm:"column:FinishDate" json:"FinishDate"`
	Active                    bool      `gorm:"column:Active;not null" json:"Active"`
	LayoutID                  int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	Updated                   time.Time `gorm:"column:Updated;not null" json:"Updated"`
	CostCentreRounding        float64   `gorm:"column:CostCentreRounding;not null" json:"CostCentreRounding"`
	QuoteStatusID             int32     `gorm:"column:QuoteStatusId" json:"QuoteStatusId"`
	EstimatorID               int32     `gorm:"column:EstimatorId" json:"EstimatorId"`
	EraID                     int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Reference                 string    `gorm:"column:Reference;not null" json:"Reference"`
	JobTypeID                 int32     `gorm:"column:JobTypeId" json:"JobTypeId"`
	Retail                    float64   `gorm:"column:Retail;not null" json:"Retail"`
	CostCentreDepth           int32     `gorm:"column:CostCentreDepth;not null;default:1" json:"CostCentreDepth"`
	CostCentresFromEstimateID int32     `gorm:"column:CostCentresFromEstimateId" json:"CostCentresFromEstimateId"`
	CostCentresFromTemplateID int32     `gorm:"column:CostCentresFromTemplateId" json:"CostCentresFromTemplateId"`
	DataVersion               int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	Circa                     time.Time `gorm:"column:Circa;not null" json:"Circa"`
	AddressID                 int32     `gorm:"column:AddressId" json:"AddressId"`
	XContactID                int32     `gorm:"column:XContactId" json:"XContactId"`
	Attributes                string    `gorm:"column:Attributes" json:"Attributes"`
	QuoteID                   int32     `gorm:"column:QuoteId" json:"QuoteId"`
}

// TableName Estimate's table name
func (*Estimate) TableName() string {
	return TableNameEstimate
}
