// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateCostCentreItemPricebook = "EstimateCostCentreItemPricebook"

// EstimateCostCentreItemPricebook mapped from table <EstimateCostCentreItemPricebook>
type EstimateCostCentreItemPricebook struct {
	EstimateCostCentreItemPricebookID int32   `gorm:"column:EstimateCostCentreItemPricebookId;primaryKey;autoIncrement:true" json:"EstimateCostCentreItemPricebookId"`
	EstimateCostCentreItemID          int32   `gorm:"column:EstimateCostCentreItemId;not null" json:"EstimateCostCentreItemId"`
	PricebookID                       int32   `gorm:"column:PricebookId" json:"PricebookId"`
	Quantity                          float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                              float64 `gorm:"column:Cost;not null" json:"Cost"`
	Retail                            float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName EstimateCostCentreItemPricebook's table name
func (*EstimateCostCentreItemPricebook) TableName() string {
	return TableNameEstimateCostCentreItemPricebook
}
