// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateCostCentre = "EstimateCostCentres"

// EstimateCostCentre mapped from table <EstimateCostCentres>
type EstimateCostCentre struct {
	EstimateCostCentreID int32   `gorm:"column:EstimateCostCentreId;primaryKey" json:"EstimateCostCentreId"`
	EstimateID           int32   `gorm:"column:EstimateId;not null" json:"EstimateId"`
	Cost                 float64 `gorm:"column:Cost;not null;default:0.0000" json:"Cost"`
	Price                float64 `gorm:"column:Price;not null;default:0.0000" json:"Price"`
	Hours                float64 `gorm:"column:Hours;not null;default:0.0000" json:"Hours"`
}

// TableName EstimateCostCentre's table name
func (*EstimateCostCentre) TableName() string {
	return TableNameEstimateCostCentre
}
