// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateCostCentreItem = "EstimateCostCentreItems"

// EstimateCostCentreItem mapped from table <EstimateCostCentreItems>
type EstimateCostCentreItem struct {
	EstimateCostCentreItemID int32   `gorm:"column:EstimateCostCentreItemId;primaryKey;autoIncrement:true" json:"EstimateCostCentreItemId"`
	EstimateCostCentreID     int32   `gorm:"column:EstimateCostCentreId;not null" json:"EstimateCostCentreId"`
	RowID                    int32   `gorm:"column:RowId;not null" json:"RowId"`
	Reference                string  `gorm:"column:Reference;not null" json:"Reference"`
	Description              string  `gorm:"column:Description;not null" json:"Description"`
	Quantity                 float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	UnitID                   int32   `gorm:"column:UnitId" json:"UnitId"`
	Brand                    string  `gorm:"column:Brand;not null" json:"Brand"`
	AssemblyID               int32   `gorm:"column:AssemblyId" json:"AssemblyId"`
	SupplierID               int32   `gorm:"column:SupplierId" json:"SupplierId"`
	MaterialUnitCost         float64 `gorm:"column:MaterialUnitCost;not null;default:0.0000" json:"MaterialUnitCost"`
	MaterialCost             float64 `gorm:"column:MaterialCost;not null;default:0.0000" json:"MaterialCost"`
	MaterialRetail           float64 `gorm:"column:MaterialRetail;not null;default:0.0000" json:"MaterialRetail"`
	LabourUnitCost           float64 `gorm:"column:LabourUnitCost;not null;default:0.0000" json:"LabourUnitCost"`
	LabourQuantity           float64 `gorm:"column:LabourQuantity;not null;default:0.0000" json:"LabourQuantity"`
	LabourCost               float64 `gorm:"column:LabourCost;not null;default:0.0000" json:"LabourCost"`
	LabourRetail             float64 `gorm:"column:LabourRetail;not null;default:0.0000" json:"LabourRetail"`
	Type                     string  `gorm:"column:Type;not null" json:"Type"`
}

// TableName EstimateCostCentreItem's table name
func (*EstimateCostCentreItem) TableName() string {
	return TableNameEstimateCostCentreItem
}
