// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimatesText = "EstimatesText"

// EstimatesText mapped from table <EstimatesText>
type EstimatesText struct {
	EstimatesTextID int32  `gorm:"column:EstimatesTextId;primaryKey" json:"EstimatesTextId"`
	Details         string `gorm:"column:Details" json:"Details"`
	Clause1         string `gorm:"column:Clause1" json:"Clause1"`
	Clause2         string `gorm:"column:Clause2" json:"Clause2"`
	Clause3         string `gorm:"column:Clause3" json:"Clause3"`
}

// TableName EstimatesText's table name
func (*EstimatesText) TableName() string {
	return TableNameEstimatesText
}
