// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateType = "EstimateTypes"

// EstimateType mapped from table <EstimateTypes>
type EstimateType struct {
	EstimateTypeID int32  `gorm:"column:EstimateTypeId;primaryKey;autoIncrement:true" json:"EstimateTypeId"`
	Code           string `gorm:"column:Code;not null" json:"Code"`
	Description    string `gorm:"column:Description;not null" json:"Description"`
	Obsolete       bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName EstimateType's table name
func (*EstimateType) TableName() string {
	return TableNameEstimateType
}
