// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateTakeoff = "EstimateTakeoff"

// EstimateTakeoff mapped from table <EstimateTakeoff>
type EstimateTakeoff struct {
	EstimateTakeOffID int32   `gorm:"column:EstimateTakeOffId;primaryKey;autoIncrement:true" json:"EstimateTakeOffId"`
	EstimateID        int32   `gorm:"column:EstimateId;not null" json:"EstimateId"`
	AssemblyID        int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	Quantity          float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
}

// TableName EstimateTakeoff's table name
func (*EstimateTakeoff) TableName() string {
	return TableNameEstimateTakeoff
}
