// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateCostCentreItemLabourRate = "EstimateCostCentreItemLabourRates"

// EstimateCostCentreItemLabourRate mapped from table <EstimateCostCentreItemLabourRates>
type EstimateCostCentreItemLabourRate struct {
	EstimateCostCentreItemLabourRateID int32   `gorm:"column:EstimateCostCentreItemLabourRateId;primaryKey;autoIncrement:true" json:"EstimateCostCentreItemLabourRateId"`
	EstimateCostCentreItemID           int32   `gorm:"column:EstimateCostCentreItemId;not null" json:"EstimateCostCentreItemId"`
	LabourRateID                       int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	Hours                              float64 `gorm:"column:Hours;not null" json:"Hours"`
	Cost                               float64 `gorm:"column:Cost;not null" json:"Cost"`
	Retail                             float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName EstimateCostCentreItemLabourRate's table name
func (*EstimateCostCentreItemLabourRate) TableName() string {
	return TableNameEstimateCostCentreItemLabourRate
}
