// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEstimateSetting = "EstimateSettings"

// EstimateSetting mapped from table <EstimateSettings>
type EstimateSetting struct {
	EstimateSettingID  int32 `gorm:"column:EstimateSettingId;primaryKey" json:"EstimateSettingId"`
	LayoutID           int32 `gorm:"column:LayoutId" json:"LayoutId"`
	FromEmailAccountID int32 `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	MessageTemplateID  int32 `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
}

// TableName EstimateSetting's table name
func (*EstimateSetting) TableName() string {
	return TableNameEstimateSetting
}
