// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameExchangeEntity = "ExchangeEntity"

// ExchangeEntity mapped from table <ExchangeEntity>
type ExchangeEntity struct {
	ID         int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	AxiapacID  string `gorm:"column:AxiapacId;not null" json:"AxiapacId"`
	ClientID   int32  `gorm:"column:ClientId" json:"ClientId"`
	SupplierID int32  `gorm:"column:SupplierId" json:"SupplierId"`
}

// TableName ExchangeEntity's table name
func (*ExchangeEntity) TableName() string {
	return TableNameExchangeEntity
}
