// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameExpenseItem = "ExpenseItems"

// ExpenseItem mapped from table <ExpenseItems>
type ExpenseItem struct {
	ExpenseItemID int32   `gorm:"column:ExpenseItemId;primaryKey;autoIncrement:true" json:"ExpenseItemId"`
	Code          string  `gorm:"column:Code;not null" json:"Code"`
	Description   string  `gorm:"column:Description;not null" json:"Description"`
	Cost          float64 `gorm:"column:Cost;not null;default:0.00" json:"Cost"`
	AccountID     int32   `gorm:"column:AccountId" json:"AccountId"`
	DivisionID    int32   `gorm:"column:DivisionId" json:"DivisionId"`
	Obsolete      bool    `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName ExpenseItem's table name
func (*ExpenseItem) TableName() string {
	return TableNameExpenseItem
}
