// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameExportSetting = "ExportSettings"

// ExportSetting mapped from table <ExportSettings>
type ExportSetting struct {
	ExportSettingID int32  `gorm:"column:ExportSettingId;primaryKey;autoIncrement:true" json:"ExportSettingId"`
	Submenu         string `gorm:"column:Submenu;not null" json:"Submenu"`
	Entity          string `gorm:"column:Entity;not null" json:"Entity"`
	ExportName      string `gorm:"column:ExportName;not null" json:"ExportName"`
	SqlQuery        string `gorm:"column:SqlQuery;not null" json:"SqlQuery"`
}

// TableName ExportSetting's table name
func (*ExportSetting) TableName() string {
	return TableNameExportSetting
}
