// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFastGet = "FastGet"

// FastGet mapped from table <FastGet>
type FastGet struct {
	FastGetID   int32     `gorm:"column:FastGetId;primaryKey;autoIncrement:true" json:"FastGetId"`
	HotKey      string    `gorm:"column:HotKey;not null;default:0" json:"HotKey"`
	UserID      int32     `gorm:"column:UserId;not null" json:"UserId"`
	Params      string    `gorm:"column:Params;not null;default:{}" json:"Params"`
	Description string    `gorm:"column:Description;not null" json:"Description"`
	CreatedAt   time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
}

// TableName FastGet's table name
func (*FastGet) TableName() string {
	return TableNameFastGet
}
