// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFile = "Files"

// File mapped from table <Files>
type File struct {
	FileID    int32     `gorm:"column:FileId;primaryKey;autoIncrement:true" json:"FileId"`
	Path      string    `gorm:"column:Path;not null" json:"Path"`
	Directory string    `gorm:"column:Directory;not null" json:"Directory"`
	Filename  string    `gorm:"column:Filename;not null" json:"Filename"`
	Extension string    `gorm:"column:Extension;not null" json:"Extension"`
	CreatedAt time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
