// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameFinancialReportSummary = "FinancialReportSummary"

// FinancialReportSummary mapped from table <FinancialReportSummary>
type FinancialReportSummary struct {
	ID              int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Scope           string  `gorm:"column:Scope;not null" json:"Scope"`
	Owner           string  `gorm:"column:Owner" json:"Owner"`
	AccountID       int32   `gorm:"column:AccountId;not null" json:"AccountId"`
	MasterAccountID int32   `gorm:"column:MasterAccountId;not null" json:"MasterAccountId"`
	MasterAccountNo int32   `gorm:"column:MasterAccountNo;not null" json:"MasterAccountNo"`
	PriorBalance    float64 `gorm:"column:PriorBalance;not null" json:"PriorBalance"`
	Debit           float64 `gorm:"column:Debit;not null" json:"Debit"`
	Credit          float64 `gorm:"column:Credit;not null" json:"Credit"`
	CurrentBalance  float64 `gorm:"column:CurrentBalance;not null" json:"CurrentBalance"`
}

// TableName FinancialReportSummary's table name
func (*FinancialReportSummary) TableName() string {
	return TableNameFinancialReportSummary
}
