// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFormWatcher = "FormWatchers"

// FormWatcher mapped from table <FormWatchers>
type FormWatcher struct {
	FormWatcherID int32     `gorm:"column:FormWatcherId;primaryKey;autoIncrement:true" json:"FormWatcherId"`
	UserID        int32     `gorm:"column:UserId;not null" json:"UserId"`
	CreatedAt     time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	TableName_    string    `gorm:"column:TableName;not null" json:"TableName"`
	TableKey      int32     `gorm:"column:TableKey;not null" json:"TableKey"`
	BatchKey      int32     `gorm:"column:BatchKey" json:"BatchKey"`
	Title         string    `gorm:"column:Title;not null" json:"Title"`
	FromUserID    int32     `gorm:"column:FromUserId;not null" json:"FromUserId"`
	Type          string    `gorm:"column:Type;not null" json:"Type"`
}

// TableName FormWatcher's table name
func (*FormWatcher) TableName() string {
	return TableNameFormWatcher
}
