// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFormLock = "FormLocks"

// FormLock mapped from table <FormLocks>
type FormLock struct {
	FormLockID int32     `gorm:"column:FormLockId;primaryKey;autoIncrement:true" json:"FormLockId"`
	TableName_ string    `gorm:"column:TableName;not null" json:"TableName"`
	TableKey   int32     `gorm:"column:TableKey;not null" json:"TableKey"`
	UserID     int32     `gorm:"column:UserId;not null" json:"UserId"`
	LockedAt   time.Time `gorm:"column:LockedAt;not null" json:"LockedAt"`
}

// TableName FormLock's table name
func (*FormLock) TableName() string {
	return TableNameFormLock
}
