// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFormS1Employee = "FormS1Employee"

// FormS1Employee mapped from table <FormS1Employee>
type FormS1Employee struct {
	ID                           int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	FormS1ID                     int32     `gorm:"column:FormS1Id;not null" json:"FormS1Id"`
	PayrollEmployeeID            int32     `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	StartDate                    time.Time `gorm:"column:StartDate;not null" json:"StartDate"`
	EndDate                      time.Time `gorm:"column:EndDate;not null" json:"EndDate"`
	LastPayrollID                int32     `gorm:"column:LastPayrollId;not null" json:"LastPayrollId"`
	FirstName                    string    `gorm:"column:FirstName;not null" json:"FirstName"`
	OtherName                    string    `gorm:"column:OtherName;not null" json:"OtherName"`
	Surname                      string    `gorm:"column:Surname;not null" json:"Surname"`
	Birthday                     time.Time `gorm:"column:Birthday" json:"Birthday"`
	EmployeeTIN                  string    `gorm:"column:EmployeeTIN;not null" json:"EmployeeTIN"`
	EmployeePostalAddress        string    `gorm:"column:EmployeePostalAddress;not null" json:"EmployeePostalAddress"`
	NumberOfDependants           int32     `gorm:"column:NumberOfDependants;not null" json:"NumberOfDependants"`
	IsResident                   bool      `gorm:"column:IsResident;not null" json:"IsResident"`
	TerminatedOn                 time.Time `gorm:"column:TerminatedOn" json:"TerminatedOn"`
	PayrollGross                 float64   `gorm:"column:PayrollGross;not null" json:"PayrollGross"`
	TaxableAllowances            float64   `gorm:"column:TaxableAllowances;not null" json:"TaxableAllowances"`
	TaxableBenefitsAccommodation float64   `gorm:"column:TaxableBenefitsAccommodation;not null" json:"TaxableBenefitsAccommodation"`
	TaxableBenefitsMVA           float64   `gorm:"column:TaxableBenefitsMVA;not null" json:"TaxableBenefitsMVA"`
	NonTaxableAllowances         float64   `gorm:"column:NonTaxableAllowances;not null" json:"NonTaxableAllowances"`
	LumpSumA                     float64   `gorm:"column:LumpSumA;not null" json:"LumpSumA"`
	LumpSumB                     float64   `gorm:"column:LumpSumB;not null" json:"LumpSumB"`
	GrossSalary                  float64   `gorm:"column:GrossSalary;not null" json:"GrossSalary"`
	TaxDeducted                  float64   `gorm:"column:TaxDeducted;not null" json:"TaxDeducted"`
	PartYearFromDate             time.Time `gorm:"column:PartYearFromDate" json:"PartYearFromDate"`
	PartYearToDate               time.Time `gorm:"column:PartYearToDate" json:"PartYearToDate"`
	CalculatedAt                 time.Time `gorm:"column:CalculatedAt;not null" json:"CalculatedAt"`
	ReconciledAt                 time.Time `gorm:"column:ReconciledAt" json:"ReconciledAt"`
	FormS1FileCreatedAt          time.Time `gorm:"column:FormS1FileCreatedAt" json:"FormS1FileCreatedAt"`
	FormS1FileID                 int32     `gorm:"column:FormS1FileId" json:"FormS1FileId"`
	FormS1EmailedAt              time.Time `gorm:"column:FormS1EmailedAt" json:"FormS1EmailedAt"`
	FinalisedAt                  time.Time `gorm:"column:FinalisedAt" json:"FinalisedAt"`
}

// TableName FormS1Employee's table name
func (*FormS1Employee) TableName() string {
	return TableNameFormS1Employee
}
