// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFormS1 = "FormS1"

// FormS1 mapped from table <FormS1>
type FormS1 struct {
	ID                   int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Date                 time.Time `gorm:"column:Date;not null" json:"Date"`
	EmployerTIN          string    `gorm:"column:EmployerTIN;not null" json:"EmployerTIN"`
	EmployerName         string    `gorm:"column:EmployerName;not null" json:"EmployerName"`
	EmployerContactName  string    `gorm:"column:EmployerContactName;not null" json:"EmployerContactName"`
	EmployerContactPhone string    `gorm:"column:EmployerContactPhone;not null" json:"EmployerContactPhone"`
	Signatory            string    `gorm:"column:Signatory;not null" json:"Signatory"`
	SignatureDate        time.Time `gorm:"column:SignatureDate;not null" json:"SignatureDate"`
	DeletedAt            time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
}

// TableName FormS1's table name
func (*FormS1) TableName() string {
	return TableNameFormS1
}
