// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHistoryTask = "HistoryTasks"

// HistoryTask mapped from table <HistoryTasks>
type HistoryTask struct {
	HistoryTaskID    int32     `gorm:"column:HistoryTaskId;primaryKey" json:"HistoryTaskId"`
	Code             string    `gorm:"column:Code;not null" json:"Code"`
	Description      string    `gorm:"column:Description;not null" json:"Description"`
	DueDate          time.Time `gorm:"column:DueDate" json:"DueDate"`
	AssigneeID       int32     `gorm:"column:AssigneeId;not null" json:"AssigneeId"`
	AssignerID       int32     `gorm:"column:AssignerId;not null" json:"AssignerId"`
	Circa            time.Time `gorm:"column:Circa;not null" json:"Circa"`
	CreateAt         time.Time `gorm:"column:CreateAt;not null" json:"CreateAt"`
	Status           int32     `gorm:"column:Status;not null" json:"Status"`
	Category         string    `gorm:"column:Category;not null" json:"Category"`
	Start            time.Time `gorm:"column:Start" json:"Start"`
	End              time.Time `gorm:"column:End" json:"End"`
	NotificationTime string    `gorm:"column:NotificationTime" json:"NotificationTime"`
	EmailTime        string    `gorm:"column:EmailTime" json:"EmailTime"`
	Frequency        string    `gorm:"column:Frequency;not null" json:"Frequency"`
	Occurence        int32     `gorm:"column:Occurence" json:"Occurence"`
}

// TableName HistoryTask's table name
func (*HistoryTask) TableName() string {
	return TableNameHistoryTask
}
