// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameHistory = "History"

// History mapped from table <History>
type History struct {
	HistoryID   int32     `gorm:"column:HistoryId;primaryKey;autoIncrement:true" json:"HistoryId"`
	UserID      int32     `gorm:"column:UserId;not null" json:"UserId"`
	CreatedAt   time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	TableName_  string    `gorm:"column:TableName;not null" json:"TableName"`
	TableKey    int32     `gorm:"column:TableKey;not null" json:"TableKey"`
	BatchKey    int32     `gorm:"column:BatchKey" json:"BatchKey"`
	Action      int32     `gorm:"column:Action;not null" json:"Action"`
	IPAddress   string    `gorm:"column:IpAddress;not null" json:"IpAddress"`
	GeoCode     string    `gorm:"column:GeoCode;not null" json:"GeoCode"`
	Title       string    `gorm:"column:Title;not null" json:"Title"`
	Description string    `gorm:"column:Description;not null" json:"Description"`
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
