// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameInsurance = "Insurances"

// Insurance mapped from table <Insurances>
type Insurance struct {
	InsuranceID int32  `gorm:"column:InsuranceId;primaryKey;autoIncrement:true" json:"InsuranceId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Insurance's table name
func (*Insurance) TableName() string {
	return TableNameInsurance
}
