// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameInvoiceItem = "InvoiceItems"

// InvoiceItem mapped from table <InvoiceItems>
type InvoiceItem struct {
	InvoiceItemID      int32   `gorm:"column:InvoiceItemId;primaryKey;autoIncrement:true" json:"InvoiceItemId"`
	InvoiceID          int32   `gorm:"column:InvoiceId;not null" json:"InvoiceId"`
	RowID              int32   `gorm:"column:RowId;not null" json:"RowId"`
	Reference          string  `gorm:"column:Reference;not null" json:"Reference"`
	Description        string  `gorm:"column:Description;not null" json:"Description"`
	Quantity           float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Amount             float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID     int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID    int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	GSTType            string  `gorm:"column:GSTType;not null" json:"GSTType"`
	GSTAmount          float64 `gorm:"column:GSTAmount;not null" json:"GSTAmount"`
	PricebookID        int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID       int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	AssemblyID         int32   `gorm:"column:AssemblyId" json:"AssemblyId"`
	StockID            int32   `gorm:"column:StockId" json:"StockId"`
	CostCentreID       int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	DebitDivisionID    int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID   int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	GstCreditAccountID int32   `gorm:"column:GstCreditAccountId" json:"GstCreditAccountId"`
	TransactionID      int32   `gorm:"column:TransactionId" json:"TransactionId"`
	Tags               string  `gorm:"column:Tags" json:"Tags"`
}

// TableName InvoiceItem's table name
func (*InvoiceItem) TableName() string {
	return TableNameInvoiceItem
}
