// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameInvoiceSetting = "InvoiceSettings"

// InvoiceSetting mapped from table <InvoiceSettings>
type InvoiceSetting struct {
	InvoiceSettingID             int32   `gorm:"column:InvoiceSettingId;primaryKey" json:"InvoiceSettingId"`
	LayoutID                     int32   `gorm:"column:LayoutId;not null" json:"LayoutId"`
	ItemSource                   string  `gorm:"column:ItemSource;not null" json:"ItemSource"`
	TotalRounding                float64 `gorm:"column:TotalRounding" json:"TotalRounding"`
	LoadJobItemsIndividually     bool    `gorm:"column:LoadJobItemsIndividually;not null" json:"LoadJobItemsIndividually"`
	LoadJobItemsWorkInProgress   bool    `gorm:"column:LoadJobItemsWorkInProgress;not null" json:"LoadJobItemsWorkInProgress"`
	LoadLabourItemsIndividually  bool    `gorm:"column:LoadLabourItemsIndividually;not null" json:"LoadLabourItemsIndividually"`
	LoadJobWorkRequired          bool    `gorm:"column:LoadJobWorkRequired;not null" json:"LoadJobWorkRequired"`
	JobPreviouslyInvoicedWarning int32   `gorm:"column:JobPreviouslyInvoicedWarning;not null" json:"JobPreviouslyInvoicedWarning"`
	UpdateJobFinishDate          int32   `gorm:"column:UpdateJobFinishDate;not null" json:"UpdateJobFinishDate"`
	FromEmailAccountID           int32   `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	MessageTemplateID            int32   `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	QuoteClauseID                int32   `gorm:"column:QuoteClauseId" json:"QuoteClauseId"`
}

// TableName InvoiceSetting's table name
func (*InvoiceSetting) TableName() string {
	return TableNameInvoiceSetting
}
