// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInvoicePointOfSale = "InvoicePointOfSale"

// InvoicePointOfSale mapped from table <InvoicePointOfSale>
type InvoicePointOfSale struct {
	ID                         int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	InvoiceID                  int32     `gorm:"column:InvoiceId;not null" json:"InvoiceId"`
	PaymentMethodType          string    `gorm:"column:PaymentMethodType;not null" json:"PaymentMethodType"`
	PaymentReference           string    `gorm:"column:PaymentReference;not null" json:"PaymentReference"`
	TransactionReceiptDetailID int32     `gorm:"column:TransactionReceiptDetailId" json:"TransactionReceiptDetailId"`
	Details                    string    `gorm:"column:Details;not null" json:"Details"`
	ReceiptID                  int32     `gorm:"column:ReceiptId;not null" json:"ReceiptId"`
	InvoiceAmount              float64   `gorm:"column:InvoiceAmount;not null" json:"InvoiceAmount"`
	InvoiceGst                 float64   `gorm:"column:InvoiceGst;not null" json:"InvoiceGst"`
	AmountDue                  float64   `gorm:"column:AmountDue;not null" json:"AmountDue"`
	OwingAmount                float64   `gorm:"column:OwingAmount;not null" json:"OwingAmount"`
	PaidAmount                 float64   `gorm:"column:PaidAmount;not null" json:"PaidAmount"`
	ChangeAmount               float64   `gorm:"column:ChangeAmount;not null" json:"ChangeAmount"`
	FileID                     int32     `gorm:"column:FileId" json:"FileId"`
	CreatedAt                  time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
}

// TableName InvoicePointOfSale's table name
func (*InvoicePointOfSale) TableName() string {
	return TableNameInvoicePointOfSale
}
