// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInvoice = "Invoices"

// Invoice mapped from table <Invoices>
type Invoice struct {
	InvoiceID         int32     `gorm:"column:InvoiceId;primaryKey;autoIncrement:true" json:"InvoiceId"`
	InvoiceNo         string    `gorm:"column:InvoiceNo;not null" json:"InvoiceNo"`
	ClientID          int32     `gorm:"column:ClientId;not null" json:"ClientId"`
	Date              time.Time `gorm:"column:Date;not null" json:"Date"`
	DueDate           time.Time `gorm:"column:DueDate;not null" json:"DueDate"`
	LayoutID          int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	Amount            float64   `gorm:"column:Amount;not null" json:"Amount"`
	GST               float64   `gorm:"column:GST;not null" json:"GST"`
	OrderNo           string    `gorm:"column:OrderNo;not null" json:"OrderNo"`
	ServiceReportNo   string    `gorm:"column:ServiceReportNo;not null" json:"ServiceReportNo"`
	Quoted            float64   `gorm:"column:Quoted" json:"Quoted"`
	LastPrinted       time.Time `gorm:"column:LastPrinted" json:"LastPrinted"`
	InDispute         bool      `gorm:"column:InDispute;not null" json:"InDispute"`
	InputTaxInclusive bool      `gorm:"column:InputTaxInclusive;not null" json:"InputTaxInclusive"`
	ServiceDate       time.Time `gorm:"column:ServiceDate" json:"ServiceDate"`
	JobID             int32     `gorm:"column:JobId" json:"JobId"`
	Owing             float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	Start             time.Time `gorm:"column:Start" json:"Start"`
	End               time.Time `gorm:"column:End" json:"End"`
	Emailed           time.Time `gorm:"column:Emailed" json:"Emailed"`
	EraID             int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa             time.Time `gorm:"column:Circa;not null" json:"Circa"`
	ClosedDate        time.Time `gorm:"column:ClosedDate" json:"ClosedDate"`
	DataVersion       int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	XContactID        int32     `gorm:"column:XContactId" json:"XContactId"`
	PdfFileID         int32     `gorm:"column:PdfFileId" json:"PdfFileId"`
	PdfCreatedAt      time.Time `gorm:"column:PdfCreatedAt" json:"PdfCreatedAt"`
	Attributes        string    `gorm:"column:Attributes" json:"Attributes"`
	UncommittedID     int32     `gorm:"column:UncommittedId" json:"UncommittedId"`
	SystemPublished   bool      `gorm:"column:SystemPublished" json:"SystemPublished"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
