// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameInvoiceItemStockLocation = "InvoiceItemStockLocations"

// InvoiceItemStockLocation mapped from table <InvoiceItemStockLocations>
type InvoiceItemStockLocation struct {
	InvoiceItemStockLocationID int32   `gorm:"column:InvoiceItemStockLocationId;primaryKey;autoIncrement:true" json:"InvoiceItemStockLocationId"`
	InvoiceItemID              int32   `gorm:"column:InvoiceItemId;not null" json:"InvoiceItemId"`
	StockLocationID            int32   `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Quantity                   float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	DebitAccountID             int32   `gorm:"column:DebitAccountId" json:"DebitAccountId"`
	DebitDivisionID            int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditAccountID            int32   `gorm:"column:CreditAccountId" json:"CreditAccountId"`
	CreditDivisionID           int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	Cost                       float64 `gorm:"column:Cost" json:"Cost"`
}

// TableName InvoiceItemStockLocation's table name
func (*InvoiceItemStockLocation) TableName() string {
	return TableNameInvoiceItemStockLocation
}
