// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameInvoicesText = "InvoicesText"

// InvoicesText mapped from table <InvoicesText>
type InvoicesText struct {
	InvoicesTextID  int32  `gorm:"column:InvoicesTextId;primaryKey" json:"InvoicesTextId"`
	Details         string `gorm:"column:Details;not null" json:"Details"`
	Clause1         string `gorm:"column:Clause1;not null" json:"Clause1"`
	Clause2         string `gorm:"column:Clause2;not null" json:"Clause2"`
	Clause3         string `gorm:"column:Clause3;not null" json:"Clause3"`
	GSTAccruedItems string `gorm:"column:GSTAccruedItems;not null" json:"GSTAccruedItems"`
	GSTReceiptItems string `gorm:"column:GSTReceiptItems;not null" json:"GSTReceiptItems"`
}

// TableName InvoicesText's table name
func (*InvoicesText) TableName() string {
	return TableNameInvoicesText
}
