// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobAlternativeClient = "JobAlternativeClients"

// JobAlternativeClient mapped from table <JobAlternativeClients>
type JobAlternativeClient struct {
	JobAlternativeClientsID int32 `gorm:"column:JobAlternativeClientsId;primaryKey;autoIncrement:true" json:"JobAlternativeClientsId"`
	JobID                   int32 `gorm:"column:JobId;not null" json:"JobId"`
	ClientID                int32 `gorm:"column:ClientId;not null" json:"ClientId"`
}

// TableName JobAlternativeClient's table name
func (*JobAlternativeClient) TableName() string {
	return TableNameJobAlternativeClient
}
