// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameJobCostAdjustment = "JobCostAdjustments"

// JobCostAdjustment mapped from table <JobCostAdjustments>
type JobCostAdjustment struct {
	JobCostAdjustmentID int32     `gorm:"column:JobCostAdjustmentId;primaryKey;autoIncrement:true" json:"JobCostAdjustmentId"`
	AdjustmentNo        int32     `gorm:"column:AdjustmentNo;not null" json:"AdjustmentNo"`
	Date                time.Time `gorm:"column:Date;not null" json:"Date"`
	Reference           string    `gorm:"column:Reference;not null" json:"Reference"`
	Type                string    `gorm:"column:Type;not null" json:"Type"`
	EraID               int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa               time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DataVersion         int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName JobCostAdjustment's table name
func (*JobCostAdjustment) TableName() string {
	return TableNameJobCostAdjustment
}
