// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobCostCentre = "JobCostCentres"

// JobCostCentre mapped from table <JobCostCentres>
type JobCostCentre struct {
	CostCentreID  int32   `gorm:"column:CostCentreId;primaryKey" json:"CostCentreId"`
	JobID         int32   `gorm:"column:JobId;not null" json:"JobId"`
	Cost          float64 `gorm:"column:Cost;not null" json:"Cost"`
	LabourCost    float64 `gorm:"column:LabourCost;not null" json:"LabourCost"`
	MaterialCost  float64 `gorm:"column:MaterialCost;not null" json:"MaterialCost"`
	Sum           float64 `gorm:"column:Sum;not null" json:"Sum"`
	Claimed       float64 `gorm:"column:Claimed;not null" json:"Claimed"`
	Hours         float64 `gorm:"column:Hours;not null" json:"Hours"`
	FromVariation bool    `gorm:"column:FromVariation;not null" json:"FromVariation"`
}

// TableName JobCostCentre's table name
func (*JobCostCentre) TableName() string {
	return TableNameJobCostCentre
}
