// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameJobCashFlowReport = "JobCashFlowReport"

// JobCashFlowReport mapped from table <JobCashFlowReport>
type JobCashFlowReport struct {
	ID                    int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	JobID                 int32     `gorm:"column:JobId;not null" json:"JobId"`
	JobNo                 string    `gorm:"column:JobNo;not null" json:"JobNo"`
	JobTitle              string    `gorm:"column:JobTitle;not null" json:"JobTitle"`
	ClientCode            string    `gorm:"column:ClientCode;not null" json:"ClientCode"`
	ReportJobHours        float64   `gorm:"column:ReportJobHours;default:0.0000" json:"ReportJobHours"`
	ReportJobLabour       float64   `gorm:"column:ReportJobLabour;default:0.00" json:"ReportJobLabour"`
	ReportJobMaterials    float64   `gorm:"column:ReportJobMaterials;default:0.00" json:"ReportJobMaterials"`
	ReportJobStock        float64   `gorm:"column:ReportJobStock;default:0.0000" json:"ReportJobStock"`
	ReportJobOnOrder      float64   `gorm:"column:ReportJobOnOrder;default:0.0000" json:"ReportJobOnOrder"`
	ReportJobCost         float64   `gorm:"column:ReportJobCost;default:0.0000" json:"ReportJobCost"`
	ReportSales           float64   `gorm:"column:ReportSales;default:0.0000" json:"ReportSales"`
	ReportJobCashflow     float64   `gorm:"column:ReportJobCashflow;default:0.0000" json:"ReportJobCashflow"`
	ReportLastInvoiceDate time.Time `gorm:"column:ReportLastInvoiceDate" json:"ReportLastInvoiceDate"`
	JobFinish             time.Time `gorm:"column:JobFinish" json:"JobFinish"`
	JobTypeCode           string    `gorm:"column:JobTypeCode" json:"JobTypeCode"`
	EmployeeCode          string    `gorm:"column:EmployeeCode" json:"EmployeeCode"`
	JobStatusCode         string    `gorm:"column:JobStatusCode" json:"JobStatusCode"`
	UserID                int32     `gorm:"column:UserId;not null" json:"UserId"`
}

// TableName JobCashFlowReport's table name
func (*JobCashFlowReport) TableName() string {
	return TableNameJobCashFlowReport
}
