// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobCostAdjustmentItem = "JobCostAdjustmentItems"

// JobCostAdjustmentItem mapped from table <JobCostAdjustmentItems>
type JobCostAdjustmentItem struct {
	JobCostAdjustmentItemID int32   `gorm:"column:JobCostAdjustmentItemId;primaryKey;autoIncrement:true" json:"JobCostAdjustmentItemId"`
	JobCostAdjustmentID     int32   `gorm:"column:JobCostAdjustmentId;not null" json:"JobCostAdjustmentId"`
	RowID                   int32   `gorm:"column:RowId;not null" json:"RowId"`
	TaskDetails             string  `gorm:"column:TaskDetails;not null" json:"TaskDetails"`
	Quantity                float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                    float64 `gorm:"column:Cost;not null" json:"Cost"`
	Description             string  `gorm:"column:Description;not null" json:"Description"`
	Reference               string  `gorm:"column:Reference;not null" json:"Reference"`
	PricebookID             int32   `gorm:"column:PricebookId" json:"PricebookId"`
	StockID                 int32   `gorm:"column:StockId" json:"StockId"`
	EmployeeID              int32   `gorm:"column:EmployeeId" json:"EmployeeId"`
	PayrollTimeTypeID       int32   `gorm:"column:PayrollTimeTypeId" json:"PayrollTimeTypeId"`
	LabourRateID            int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	UnitID                  int32   `gorm:"column:UnitId" json:"UnitId"`
	JobID                   int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID            int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	StockLocationID         int32   `gorm:"column:StockLocationId" json:"StockLocationId"`
}

// TableName JobCostAdjustmentItem's table name
func (*JobCostAdjustmentItem) TableName() string {
	return TableNameJobCostAdjustmentItem
}
