// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobCostAdjustmentText = "JobCostAdjustmentTexts"

// JobCostAdjustmentText mapped from table <JobCostAdjustmentTexts>
type JobCostAdjustmentText struct {
	JobCostAdjustmentID int32  `gorm:"column:JobCostAdjustmentId;primaryKey" json:"JobCostAdjustmentId"`
	JobsList            string `gorm:"column:JobsList;not null" json:"JobsList"`
	StockLocationsList  string `gorm:"column:StockLocationsList;not null" json:"StockLocationsList"`
}

// TableName JobCostAdjustmentText's table name
func (*JobCostAdjustmentText) TableName() string {
	return TableNameJobCostAdjustmentText
}
