// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameJobItem = "JobItems"

// JobItem mapped from table <JobItems>
type JobItem struct {
	JobItemID    int32     `gorm:"column:JobItemId;primaryKey;autoIncrement:true" json:"JobItemId"`
	JobID        int32     `gorm:"column:JobId;not null" json:"JobId"`
	RowID        int32     `gorm:"column:RowId;not null" json:"RowId"`
	Date         time.Time `gorm:"column:Date;not null" json:"Date"`
	Description  string    `gorm:"column:Description;not null" json:"Description"`
	Cost         float64   `gorm:"column:Cost;not null" json:"Cost"`
	Quantity     float64   `gorm:"column:Quantity;not null" json:"Quantity"`
	Reference    string    `gorm:"column:Reference;not null" json:"Reference"`
	PricebookID  int32     `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID int32     `gorm:"column:LabourRateId" json:"LabourRateId"`
	AssemblyID   int32     `gorm:"column:AssemblyId" json:"AssemblyId"`
	StockID      int32     `gorm:"column:StockId" json:"StockId"`
	CostCentreID int32     `gorm:"column:CostCentreId" json:"CostCentreId"`
}

// TableName JobItem's table name
func (*JobItem) TableName() string {
	return TableNameJobItem
}
