// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobInstruction = "JobInstructions"

// JobInstruction mapped from table <JobInstructions>
type JobInstruction struct {
	JobInstructionID int32  `gorm:"column:JobInstructionId;primaryKey;autoIncrement:true" json:"JobInstructionId"`
	Code             string `gorm:"column:Code;not null" json:"Code"`
	Description      string `gorm:"column:Description;not null" json:"Description"`
	Obsolete         bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName JobInstruction's table name
func (*JobInstruction) TableName() string {
	return TableNameJobInstruction
}
