// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobItemStockLocation = "JobItemStockLocations"

// JobItemStockLocation mapped from table <JobItemStockLocations>
type JobItemStockLocation struct {
	JobItemStockLocationsID int32   `gorm:"column:JobItemStockLocationsId;primaryKey;autoIncrement:true" json:"JobItemStockLocationsId"`
	JobItemID               int32   `gorm:"column:JobItemId;not null" json:"JobItemId"`
	StockLocationID         int32   `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Quantity                float64 `gorm:"column:Quantity;not null" json:"Quantity"`
}

// TableName JobItemStockLocation's table name
func (*JobItemStockLocation) TableName() string {
	return TableNameJobItemStockLocation
}
