// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobRequiredPricebook = "JobRequiredPricebooks"

// JobRequiredPricebook mapped from table <JobRequiredPricebooks>
type JobRequiredPricebook struct {
	JobRequiredPricebookID int32   `gorm:"column:JobRequiredPricebookId;primaryKey;autoIncrement:true" json:"JobRequiredPricebookId"`
	JobID                  int32   `gorm:"column:JobId;not null" json:"JobId"`
	RowID                  int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity               float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	PricebookID            int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
}

// TableName JobRequiredPricebook's table name
func (*JobRequiredPricebook) TableName() string {
	return TableNameJobRequiredPricebook
}
