// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobRequiredLabour = "JobRequiredLabours"

// JobRequiredLabour mapped from table <JobRequiredLabours>
type JobRequiredLabour struct {
	JobRequiredLabourID int32   `gorm:"column:JobRequiredLabourId;primaryKey;autoIncrement:true" json:"JobRequiredLabourId"`
	JobID               int32   `gorm:"column:JobId;not null" json:"JobId"`
	RowID               int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity            float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	LabourRateID        int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
}

// TableName JobRequiredLabour's table name
func (*JobRequiredLabour) TableName() string {
	return TableNameJobRequiredLabour
}
