// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobsLedgerAdjustment = "JobsLedgerAdjustments"

// JobsLedgerAdjustment mapped from table <JobsLedgerAdjustments>
type JobsLedgerAdjustment struct {
	ID             int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	JobsLedgerID   int32   `gorm:"column:JobsLedgerId;not null" json:"JobsLedgerId"`
	SourceType     string  `gorm:"column:SourceType;not null" json:"SourceType"`
	SourceID       int32   `gorm:"column:SourceId;not null" json:"SourceId"`
	SourceItemType string  `gorm:"column:SourceItemType;not null" json:"SourceItemType"`
	SourceItemID   int32   `gorm:"column:SourceItemId;not null" json:"SourceItemId"`
	Quantity       float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Amount         float64 `gorm:"column:Amount;not null" json:"Amount"`
}

// TableName JobsLedgerAdjustment's table name
func (*JobsLedgerAdjustment) TableName() string {
	return TableNameJobsLedgerAdjustment
}
