// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobSetting = "JobSettings"

// JobSetting mapped from table <JobSettings>
type JobSetting struct {
	JobSettingID       int32   `gorm:"column:JobSettingId;primaryKey" json:"JobSettingId"`
	LayoutID           int32   `gorm:"column:LayoutId;not null" json:"LayoutId"`
	JobTypeID          int32   `gorm:"column:JobTypeId" json:"JobTypeId"`
	JobStatusID        int32   `gorm:"column:JobStatusId" json:"JobStatusId"`
	FromEmailAccountID int32   `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	MessageTemplateID  int32   `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	LabourMarkup       float64 `gorm:"column:LabourMarkup;not null" json:"LabourMarkup"`
	PricebookMarkup    float64 `gorm:"column:PricebookMarkup;not null" json:"PricebookMarkup"`
	OtherMarkup        float64 `gorm:"column:OtherMarkup;not null" json:"OtherMarkup"`
	JobTypeRequired    bool    `gorm:"column:JobTypeRequired;not null" json:"JobTypeRequired"`
	JobStatusRequired  bool    `gorm:"column:JobStatusRequired;not null" json:"JobStatusRequired"`
	CollectPaymentFlag bool    `gorm:"column:CollectPaymentFlag;not null" json:"CollectPaymentFlag"`
	UseClientAddress   bool    `gorm:"column:UseClientAddress;not null" json:"UseClientAddress"`
	JobBookNumberLabel string  `gorm:"column:JobBookNumberLabel;not null" json:"JobBookNumberLabel"`
	JobPrefixEnabled   bool    `gorm:"column:JobPrefixEnabled;not null" json:"JobPrefixEnabled"`
}

// TableName JobSetting's table name
func (*JobSetting) TableName() string {
	return TableNameJobSetting
}
