// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameJob = "Jobs"

// Job mapped from table <Jobs>
type Job struct {
	JobID                 int32     `gorm:"column:JobId;primaryKey;autoIncrement:true" json:"JobId"`
	JobNo                 string    `gorm:"column:JobNo;not null" json:"JobNo"`
	JobNoFixedLen         string    `gorm:"column:JobNoFixedLen;not null" json:"JobNoFixedLen"`
	Description           string    `gorm:"column:Description;not null" json:"Description"`
	ClientID              int32     `gorm:"column:ClientId;not null" json:"ClientId"`
	LayoutID              int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	JobTypeID             int32     `gorm:"column:JobTypeId" json:"JobTypeId"`
	EstimateID            int32     `gorm:"column:EstimateId" json:"EstimateId"`
	JobStatusID           int32     `gorm:"column:JobStatusId" json:"JobStatusId"`
	Received              time.Time `gorm:"column:Received" json:"Received"`
	Start                 time.Time `gorm:"column:Start" json:"Start"`
	Finish                time.Time `gorm:"column:Finish" json:"Finish"`
	QuotedPrice           float64   `gorm:"column:QuotedPrice" json:"QuotedPrice"`
	CustomerOrderNo       string    `gorm:"column:CustomerOrderNo" json:"CustomerOrderNo"`
	JobBookNumber         string    `gorm:"column:JobBookNumber" json:"JobBookNumber"`
	CollectPayment        bool      `gorm:"column:CollectPayment;not null" json:"CollectPayment"`
	PaymentMethodID       int32     `gorm:"column:PaymentMethodId" json:"PaymentMethodId"`
	WarrantyFlag          bool      `gorm:"column:WarrantyFlag;not null" json:"WarrantyFlag"`
	LabourMarkupOption    string    `gorm:"column:LabourMarkupOption;not null;default:Retail" json:"LabourMarkupOption"`
	LabourMarkup          float64   `gorm:"column:LabourMarkup" json:"LabourMarkup"`
	PricebookMarkupOption string    `gorm:"column:PricebookMarkupOption;not null;default:Retail" json:"PricebookMarkupOption"`
	PricebookMarkup       float64   `gorm:"column:PricebookMarkup" json:"PricebookMarkup"`
	OtherMarkup           float64   `gorm:"column:OtherMarkup;not null;default:0.0000" json:"OtherMarkup"`
	TimeAllowed           float64   `gorm:"column:TimeAllowed;not null;default:0.0000" json:"TimeAllowed"`
	TechniciansRequired   int32     `gorm:"column:TechniciansRequired;not null" json:"TechniciansRequired"`
	ApprenticesRequired   int32     `gorm:"column:ApprenticesRequired;not null" json:"ApprenticesRequired"`
	SupervisorID          int32     `gorm:"column:SupervisorId" json:"SupervisorId"`
	QuoteID               int32     `gorm:"column:QuoteId" json:"QuoteId"`
	CostCentreEnabled     bool      `gorm:"column:CostCentreEnabled;not null" json:"CostCentreEnabled"`
	EraID                 int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa                 time.Time `gorm:"column:Circa;not null" json:"Circa"`
	WorkStarted           time.Time `gorm:"column:WorkStarted" json:"WorkStarted"`
	CreatedAt             time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	UpdatedAt             time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt             time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	AddressID             int32     `gorm:"column:AddressId;not null" json:"AddressId"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
