// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameJobsLedger = "JobsLedger"

// JobsLedger mapped from table <JobsLedger>
type JobsLedger struct {
	ID                   int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	JobID                int32     `gorm:"column:JobId;not null" json:"JobId"`
	SourceType           string    `gorm:"column:SourceType;not null" json:"SourceType"`
	SourceID             int32     `gorm:"column:SourceId;not null" json:"SourceId"`
	SourceItemType       string    `gorm:"column:SourceItemType;not null" json:"SourceItemType"`
	SourceItemID         int32     `gorm:"column:SourceItemId;not null" json:"SourceItemId"`
	Date                 time.Time `gorm:"column:Date;not null" json:"Date"`
	ReferenceType        string    `gorm:"column:ReferenceType;not null" json:"ReferenceType"`
	ReferenceID          int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	ReferenceCode        string    `gorm:"column:ReferenceCode;not null" json:"ReferenceCode"`
	ReferenceDescription string    `gorm:"column:ReferenceDescription;not null" json:"ReferenceDescription"`
	UnitPrice            float64   `gorm:"column:UnitPrice;not null" json:"UnitPrice"`
	Unit                 string    `gorm:"column:Unit;not null" json:"Unit"`
	Quantity             float64   `gorm:"column:Quantity;not null" json:"Quantity"`
	ChargedHours         float64   `gorm:"column:ChargedHours" json:"ChargedHours"`
	CostCentreID         int32     `gorm:"column:CostCentreId" json:"CostCentreId"`
	CostCentreCode       string    `gorm:"column:CostCentreCode" json:"CostCentreCode"`
	CostCentreFullCode   string    `gorm:"column:CostCentreFullCode" json:"CostCentreFullCode"`
	Amount               float64   `gorm:"column:Amount;not null" json:"Amount"`
	EmployeeID           int32     `gorm:"column:EmployeeId" json:"EmployeeId"`
	EmployeeCode         string    `gorm:"column:EmployeeCode" json:"EmployeeCode"`
	SupplierID           int32     `gorm:"column:SupplierId" json:"SupplierId"`
	SupplierCode         string    `gorm:"column:SupplierCode" json:"SupplierCode"`
	InvoiceNo            string    `gorm:"column:InvoiceNo" json:"InvoiceNo"`
	OrderID              int32     `gorm:"column:OrderId" json:"OrderId"`
	OrderNo              string    `gorm:"column:OrderNo" json:"OrderNo"`
	StockMovementNo      string    `gorm:"column:StockMovementNo" json:"StockMovementNo"`
	JobCostAdjustmentNo  string    `gorm:"column:JobCostAdjustmentNo" json:"JobCostAdjustmentNo"`
	TransactionNo        int32     `gorm:"column:TransactionNo" json:"TransactionNo"`
	QuantityBased        bool      `gorm:"column:QuantityBased;not null" json:"QuantityBased"`
}

// TableName JobsLedger's table name
func (*JobsLedger) TableName() string {
	return TableNameJobsLedger
}
