// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobStatus = "JobStatus"

// JobStatus mapped from table <JobStatus>
type JobStatus struct {
	JobStatusID   int32  `gorm:"column:JobStatusId;primaryKey;autoIncrement:true" json:"JobStatusId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
	TimeclockFlag bool   `gorm:"column:TimeclockFlag;not null" json:"TimeclockFlag"`
	Obsolete      bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName JobStatus's table name
func (*JobStatus) TableName() string {
	return TableNameJobStatus
}
