// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobStatusTrigger = "JobStatusTriggers"

// JobStatusTrigger mapped from table <JobStatusTriggers>
type JobStatusTrigger struct {
	JobStatusTriggerID int32  `gorm:"column:JobStatusTriggerId;primaryKey;autoIncrement:true" json:"JobStatusTriggerId"`
	Event              string `gorm:"column:Event;not null" json:"Event"`
	SetJobStatusID     int32  `gorm:"column:SetJobStatusId;not null" json:"SetJobStatusId"`
	JobStatusID        int32  `gorm:"column:JobStatusId" json:"JobStatusId"`
	JobTypeID          int32  `gorm:"column:JobTypeId" json:"JobTypeId"`
}

// TableName JobStatusTrigger's table name
func (*JobStatusTrigger) TableName() string {
	return TableNameJobStatusTrigger
}
