// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobTypeSkill = "JobTypeSkills"

// JobTypeSkill mapped from table <JobTypeSkills>
type JobTypeSkill struct {
	JobTypeSkillID int32 `gorm:"column:JobTypeSkillId;primaryKey;autoIncrement:true" json:"JobTypeSkillId"`
	JobTypeID      int32 `gorm:"column:JobTypeId;not null" json:"JobTypeId"`
	SkillID        int32 `gorm:"column:SkillId;not null" json:"SkillId"`
}

// TableName JobTypeSkill's table name
func (*JobTypeSkill) TableName() string {
	return TableNameJobTypeSkill
}
