// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobType = "JobTypes"

// JobType mapped from table <JobTypes>
type JobType struct {
	JobTypeID           int32  `gorm:"column:JobTypeId;primaryKey;autoIncrement:true" json:"JobTypeId"`
	Code                string `gorm:"column:Code;not null" json:"Code"`
	Description         string `gorm:"column:Description;not null" json:"Description"`
	JobLayoutID         int32  `gorm:"column:JobLayoutId" json:"JobLayoutId"`
	InvoiceLayoutID     int32  `gorm:"column:InvoiceLayoutId" json:"InvoiceLayoutId"`
	ShowWarrantyOptions bool   `gorm:"column:ShowWarrantyOptions;not null" json:"ShowWarrantyOptions"`
	DebtorAccountID     int32  `gorm:"column:DebtorAccountId" json:"DebtorAccountId"`
	CreditorAccountID   int32  `gorm:"column:CreditorAccountId" json:"CreditorAccountId"`
	DebtorDivisionID    int32  `gorm:"column:DebtorDivisionId" json:"DebtorDivisionId"`
	CreditorDivisionID  int32  `gorm:"column:CreditorDivisionId" json:"CreditorDivisionId"`
	JobPrefix           string `gorm:"column:JobPrefix;not null" json:"JobPrefix"`
	SetJobFinish        bool   `gorm:"column:SetJobFinish;not null" json:"SetJobFinish"`
	Obsolete            bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName JobType's table name
func (*JobType) TableName() string {
	return TableNameJobType
}
