// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobText = "JobTexts"

// JobText mapped from table <JobTexts>
type JobText struct {
	JobID        int32  `gorm:"column:JobId;primaryKey" json:"JobId"`
	WorkRequired string `gorm:"column:WorkRequired;not null" json:"WorkRequired"`
	Instructions string `gorm:"column:Instructions;not null" json:"Instructions"`
	InvoiceList  string `gorm:"column:InvoiceList;not null" json:"InvoiceList"`
	Clause1      string `gorm:"column:Clause1;not null" json:"Clause1"`
	Clause2      string `gorm:"column:Clause2;not null" json:"Clause2"`
	Clause3      string `gorm:"column:Clause3;not null" json:"Clause3"`
}

// TableName JobText's table name
func (*JobText) TableName() string {
	return TableNameJobText
}
