// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobTypeSupervisor = "JobTypeSupervisors"

// JobTypeSupervisor mapped from table <JobTypeSupervisors>
type JobTypeSupervisor struct {
	JobTypeSupervisorID int32 `gorm:"column:JobTypeSupervisorId;primaryKey;autoIncrement:true" json:"JobTypeSupervisorId"`
	JobTypeID           int32 `gorm:"column:JobTypeId;not null" json:"JobTypeId"`
	EmployeeID          int32 `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
}

// TableName JobTypeSupervisor's table name
func (*JobTypeSupervisor) TableName() string {
	return TableNameJobTypeSupervisor
}
