// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobTypePricebook = "JobTypePricebooks"

// JobTypePricebook mapped from table <JobTypePricebooks>
type JobTypePricebook struct {
	JobTypePricebookID int32   `gorm:"column:JobTypePricebookId;primaryKey;autoIncrement:true" json:"JobTypePricebookId"`
	JobTypeID          int32   `gorm:"column:JobTypeId;not null" json:"JobTypeId"`
	PricebookID        int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	Quantity           float64 `gorm:"column:Quantity;not null;default:1.0000" json:"Quantity"`
}

// TableName JobTypePricebook's table name
func (*JobTypePricebook) TableName() string {
	return TableNameJobTypePricebook
}
