// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobTypeText = "JobTypeTexts"

// JobTypeText mapped from table <JobTypeTexts>
type JobTypeText struct {
	JobTypeID           int32  `gorm:"column:JobTypeId;primaryKey" json:"JobTypeId"`
	PrefillInstructions string `gorm:"column:PrefillInstructions;not null" json:"PrefillInstructions"`
	PrefillWorkRequired string `gorm:"column:PrefillWorkRequired;not null" json:"PrefillWorkRequired"`
}

// TableName JobTypeText's table name
func (*JobTypeText) TableName() string {
	return TableNameJobTypeText
}
