// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobWarranty = "JobWarranty"

// JobWarranty mapped from table <JobWarranty>
type JobWarranty struct {
	JobWarrantyID      int32  `gorm:"column:JobWarrantyId;primaryKey;autoIncrement:true" json:"JobWarrantyId"`
	JobID              int32  `gorm:"column:JobId;not null" json:"JobId"`
	RowID              int32  `gorm:"column:RowId;not null" json:"RowId"`
	PricebookID        int32  `gorm:"column:PricebookId" json:"PricebookId"`
	WarrantyID         int32  `gorm:"column:WarrantyId;not null" json:"WarrantyId"`
	LocationOnSite     string `gorm:"column:LocationOnSite;not null" json:"LocationOnSite"`
	FaultCode          string `gorm:"column:FaultCode;not null" json:"FaultCode"`
	FaultNotes         string `gorm:"column:FaultNotes;not null" json:"FaultNotes"`
	SerialNoTrackingID int32  `gorm:"column:SerialNoTrackingId" json:"SerialNoTrackingId"`
}

// TableName JobWarranty's table name
func (*JobWarranty) TableName() string {
	return TableNameJobWarranty
}
