// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLabourRate = "LabourRates"

// LabourRate mapped from table <LabourRates>
type LabourRate struct {
	LabourRateID             int32     `gorm:"column:LabourRateId;primaryKey;autoIncrement:true" json:"LabourRateId"`
	Code                     string    `gorm:"column:Code;not null" json:"Code"`
	Description              string    `gorm:"column:Description;not null" json:"Description"`
	Cost                     float64   `gorm:"column:Cost;not null" json:"Cost"`
	Retail                   float64   `gorm:"column:Retail;not null" json:"Retail"`
	LastUpdated              time.Time `gorm:"column:LastUpdated;not null" json:"LastUpdated"`
	NonWorking               bool      `gorm:"column:NonWorking;not null" json:"NonWorking"`
	PriceCategoryID          int32     `gorm:"column:PriceCategoryId" json:"PriceCategoryId"`
	DebtorAccountID          int32     `gorm:"column:DebtorAccountId" json:"DebtorAccountId"`
	CreditorAccountID        int32     `gorm:"column:CreditorAccountId" json:"CreditorAccountId"`
	PayrollAwardID           int32     `gorm:"column:PayrollAwardId" json:"PayrollAwardId"`
	PayrollTimeTypeID        int32     `gorm:"column:PayrollTimeTypeId" json:"PayrollTimeTypeId"`
	EmploymentOverhead       float64   `gorm:"column:EmploymentOverhead" json:"EmploymentOverhead"`
	PricebookID              int32     `gorm:"column:PricebookId" json:"PricebookId"`
	IncludeHours             float64   `gorm:"column:IncludeHours" json:"IncludeHours"`
	OnCostsPayrollTimeTypeID int32     `gorm:"column:OnCostsPayrollTimeTypeId" json:"OnCostsPayrollTimeTypeId"`
	OnCost                   float64   `gorm:"column:OnCost" json:"OnCost"`
	DebtorDivisionID         int32     `gorm:"column:DebtorDivisionId" json:"DebtorDivisionId"`
	CreditorDivisionID       int32     `gorm:"column:CreditorDivisionId" json:"CreditorDivisionId"`
	Restricted               bool      `gorm:"column:Restricted;not null" json:"Restricted"`
	PostToJob                string    `gorm:"column:PostToJob;not null" json:"PostToJob"`
	EraID                    int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa                    time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DataVersion              int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName LabourRate's table name
func (*LabourRate) TableName() string {
	return TableNameLabourRate
}
