// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLabourRateEffectiveRetailRate = "LabourRateEffectiveRetailRate"

// LabourRateEffectiveRetailRate mapped from table <LabourRateEffectiveRetailRate>
type LabourRateEffectiveRetailRate struct {
	LabourRateEffectiveRetailRateID int32     `gorm:"column:LabourRateEffectiveRetailRateId;primaryKey;autoIncrement:true" json:"LabourRateEffectiveRetailRateId"`
	LabourRateID                    int32     `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	EffectiveDate                   time.Time `gorm:"column:EffectiveDate;not null" json:"EffectiveDate"`
	Retail                          float64   `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName LabourRateEffectiveRetailRate's table name
func (*LabourRateEffectiveRetailRate) TableName() string {
	return TableNameLabourRateEffectiveRetailRate
}
