// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLabourRatePrice = "LabourRatePrices"

// LabourRatePrice mapped from table <LabourRatePrices>
type LabourRatePrice struct {
	LabourRatePriceID      int32   `gorm:"column:LabourRatePriceId;primaryKey;autoIncrement:true" json:"LabourRatePriceId"`
	LabourRateID           int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	ClientID               int32   `gorm:"column:ClientId" json:"ClientId"`
	ClientClassificationID int32   `gorm:"column:ClientClassificationId" json:"ClientClassificationId"`
	JobTypeID              int32   `gorm:"column:JobTypeId" json:"JobTypeId"`
	BasedOn                string  `gorm:"column:BasedOn;not null" json:"BasedOn"`
	Retail                 float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName LabourRatePrice's table name
func (*LabourRatePrice) TableName() string {
	return TableNameLabourRatePrice
}
