// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeaveRequest = "LeaveRequests"

// LeaveRequest mapped from table <LeaveRequests>
type LeaveRequest struct {
	LeaveRequestID      int32     `gorm:"column:LeaveRequestId;primaryKey;autoIncrement:true" json:"LeaveRequestId"`
	RequestNo           string    `gorm:"column:RequestNo;not null" json:"RequestNo"`
	EmployeeID          int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	LeaveTimeTypeID     int32     `gorm:"column:LeaveTimeTypeId;not null" json:"LeaveTimeTypeId"`
	RequestReceivedDate time.Time `gorm:"column:RequestReceivedDate;not null" json:"RequestReceivedDate"`
	LeaveFirstDate      time.Time `gorm:"column:LeaveFirstDate" json:"LeaveFirstDate"`
	LeaveFinalDate      time.Time `gorm:"column:LeaveFinalDate" json:"LeaveFinalDate"`
	Details             string    `gorm:"column:Details;not null" json:"Details"`
	Duration            string    `gorm:"column:Duration;not null" json:"Duration"`
	EraID               int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa               time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DataVersion         int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName LeaveRequest's table name
func (*LeaveRequest) TableName() string {
	return TableNameLeaveRequest
}
