// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeaveRequestBreakDown = "LeaveRequestBreakDowns"

// LeaveRequestBreakDown mapped from table <LeaveRequestBreakDowns>
type LeaveRequestBreakDown struct {
	LeaveRequestBreakDownID int32     `gorm:"column:LeaveRequestBreakDownId;primaryKey;autoIncrement:true" json:"LeaveRequestBreakDownId"`
	LeaveRequestID          int32     `gorm:"column:LeaveRequestId;not null" json:"LeaveRequestId"`
	LeaveTimeTypeID         int32     `gorm:"column:LeaveTimeTypeId;not null" json:"LeaveTimeTypeId"`
	Category                string    `gorm:"column:Category;not null" json:"Category"`
	RowID                   int32     `gorm:"column:RowId;not null" json:"RowId"`
	StartDateTime           time.Time `gorm:"column:StartDateTime;not null" json:"StartDateTime"`
	FinishDateTime          time.Time `gorm:"column:FinishDateTime;not null" json:"FinishDateTime"`
}

// TableName LeaveRequestBreakDown's table name
func (*LeaveRequestBreakDown) TableName() string {
	return TableNameLeaveRequestBreakDown
}
