// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLicence = "Licences"

// Licence mapped from table <Licences>
type Licence struct {
	LicenceID   int32  `gorm:"column:LicenceId;primaryKey;autoIncrement:true" json:"LicenceId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	Master      bool   `gorm:"column:Master;not null" json:"Master"`
}

// TableName Licence's table name
func (*Licence) TableName() string {
	return TableNameLicence
}
