// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMessageTemplate = "MessageTemplates"

// MessageTemplate mapped from table <MessageTemplates>
type MessageTemplate struct {
	MessageTemplateID int32  `gorm:"column:MessageTemplateId;primaryKey;autoIncrement:true" json:"MessageTemplateId"`
	Code              string `gorm:"column:Code;not null" json:"Code"`
	Description       string `gorm:"column:Description;not null" json:"Description"`
	Message           string `gorm:"column:Message;not null" json:"Message"`
	Form              string `gorm:"column:Form;not null" json:"Form"`
	Subject           string `gorm:"column:Subject" json:"Subject"`
	FormPreviewKey    string `gorm:"column:FormPreviewKey" json:"FormPreviewKey"`
	Master            bool   `gorm:"column:Master;not null" json:"Master"`
	Obsolete          bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName MessageTemplate's table name
func (*MessageTemplate) TableName() string {
	return TableNameMessageTemplate
}
