// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameNotification = "Notifications"

// Notification mapped from table <Notifications>
type Notification struct {
	NotificationsID int32     `gorm:"column:NotificationsId;primaryKey" json:"NotificationsId"`
	FromUserID      int32     `gorm:"column:FromUserId;not null" json:"FromUserId"`
	ToUserID        int32     `gorm:"column:ToUserId;not null" json:"ToUserId"`
	Subject         string    `gorm:"column:Subject;not null" json:"Subject"`
	Message         string    `gorm:"column:Message;not null" json:"Message"`
	MessageRead     bool      `gorm:"column:MessageRead;not null" json:"MessageRead"`
	CreatedAt       time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	Linkage         string    `gorm:"column:Linkage" json:"Linkage"`
	Module          string    `gorm:"column:Module" json:"Module"`
	Key             int32     `gorm:"column:Key" json:"Key"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
