// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOccupation = "Occupations"

// Occupation mapped from table <Occupations>
type Occupation struct {
	OccupationID int32  `gorm:"column:OccupationId;primaryKey;autoIncrement:true" json:"OccupationId"`
	Code         string `gorm:"column:Code;not null" json:"Code"`
	Description  string `gorm:"column:Description;not null" json:"Description"`
	Obsolete     bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Occupation's table name
func (*Occupation) TableName() string {
	return TableNameOccupation
}
