// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrderItemsQuantity = "OrderItemsQuantity"

// OrderItemsQuantity mapped from table <OrderItemsQuantity>
type OrderItemsQuantity struct {
	OrderItemsQuantityID int32   `gorm:"column:OrderItemsQuantityId;primaryKey;autoIncrement:true" json:"OrderItemsQuantityId"`
	OrderItemID          int32   `gorm:"column:OrderItemId;not null" json:"OrderItemId"`
	RowID                int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity             float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	JobID                int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID         int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	StockLocationID      int32   `gorm:"column:StockLocationId" json:"StockLocationId"`
	DeliveredQuantity    float64 `gorm:"column:DeliveredQuantity" json:"DeliveredQuantity"`
	InvoicedQuantity     float64 `gorm:"column:InvoicedQuantity" json:"InvoicedQuantity"`
	PurchaseAmount       float64 `gorm:"column:PurchaseAmount;not null" json:"PurchaseAmount"`
}

// TableName OrderItemsQuantity's table name
func (*OrderItemsQuantity) TableName() string {
	return TableNameOrderItemsQuantity
}
