// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrderItem = "OrderItems"

// OrderItem mapped from table <OrderItems>
type OrderItem struct {
	OrderItemID     int32   `gorm:"column:OrderItemId;primaryKey;autoIncrement:true" json:"OrderItemId"`
	OrderID         int32   `gorm:"column:OrderId;not null" json:"OrderId"`
	RowID           int32   `gorm:"column:RowId;not null" json:"RowId"`
	Description     string  `gorm:"column:Description;not null" json:"Description"`
	UnitID          int32   `gorm:"column:UnitId" json:"UnitId"`
	UnitCost        float64 `gorm:"column:UnitCost;not null" json:"UnitCost"`
	Cost            float64 `gorm:"column:Cost;not null" json:"Cost"`
	GSTType         string  `gorm:"column:GSTType;not null" json:"GSTType"`
	GSTAmount       float64 `gorm:"column:GSTAmount;not null" json:"GSTAmount"`
	ProductCode     string  `gorm:"column:ProductCode;not null" json:"ProductCode"`
	Reference       string  `gorm:"column:Reference;not null" json:"Reference"`
	PricebookID     int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID    int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	PackageID       int32   `gorm:"column:PackageId" json:"PackageId"`
	PackageQuantity float64 `gorm:"column:PackageQuantity" json:"PackageQuantity"`
	Quantity        float64 `gorm:"column:Quantity" json:"Quantity"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
