// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrderSetting = "OrderSettings"

// OrderSetting mapped from table <OrderSettings>
type OrderSetting struct {
	OrderSettingID                     int32  `gorm:"column:OrderSettingId;primaryKey" json:"OrderSettingId"`
	LayoutID                           int32  `gorm:"column:LayoutId;not null" json:"LayoutId"`
	StockLocationID                    int32  `gorm:"column:StockLocationId" json:"StockLocationId"`
	AssemblyStockLocationID            int32  `gorm:"column:AssemblyStockLocationId" json:"AssemblyStockLocationId"`
	ProductCodeRequired                bool   `gorm:"column:ProductCodeRequired;not null" json:"ProductCodeRequired"`
	UnitID                             int32  `gorm:"column:UnitId;not null" json:"UnitId"`
	FromEmailAccountID                 int32  `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	MessageTemplateID                  int32  `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	DeliveryAddressUseStockLocation    int32  `gorm:"column:DeliveryAddressUseStockLocation;not null" json:"DeliveryAddressUseStockLocation"`
	DefaultItemSource                  string `gorm:"column:DefaultItemSource;not null" json:"DefaultItemSource"`
	SetUserAsIssuedBy                  bool   `gorm:"column:SetUserAsIssuedBy;not null" json:"SetUserAsIssuedBy"`
	IssuedByRequired                   bool   `gorm:"column:IssuedByRequired;not null" json:"IssuedByRequired"`
	DisableInStockWarning              bool   `gorm:"column:DisableInStockWarning;not null" json:"DisableInStockWarning"`
	AllowPostingToCompletedJobs        bool   `gorm:"column:AllowPostingToCompletedJobs;not null" json:"AllowPostingToCompletedJobs"`
	CostCentreRequired                 bool   `gorm:"column:CostCentreRequired;not null" json:"CostCentreRequired"`
	ValidProjectCostCentre             bool   `gorm:"column:ValidProjectCostCentre;not null" json:"ValidProjectCostCentre"`
	CheckOrderExceedsBudget            bool   `gorm:"column:CheckOrderExceedsBudget;not null" json:"CheckOrderExceedsBudget"`
	AllowPricebookNoJobNoStockLocation bool   `gorm:"column:AllowPricebookNoJobNoStockLocation;not null" json:"AllowPricebookNoJobNoStockLocation"`
	OtherItemsJobRequired              bool   `gorm:"column:OtherItemsJobRequired;not null" json:"OtherItemsJobRequired"`
}

// TableName OrderSetting's table name
func (*OrderSetting) TableName() string {
	return TableNameOrderSetting
}
