// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrderInstruction = "OrderInstructions"

// OrderInstruction mapped from table <OrderInstructions>
type OrderInstruction struct {
	OrderInstructionID int32  `gorm:"column:OrderInstructionId;primaryKey;autoIncrement:true" json:"OrderInstructionId"`
	Code               string `gorm:"column:Code;not null" json:"Code"`
	Description        string `gorm:"column:Description;not null" json:"Description"`
}

// TableName OrderInstruction's table name
func (*OrderInstruction) TableName() string {
	return TableNameOrderInstruction
}
