// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOrdersText = "OrdersText"

// OrdersText mapped from table <OrdersText>
type OrdersText struct {
	OrdersTextID         int32  `gorm:"column:OrdersTextId;primaryKey" json:"OrdersTextId"`
	DeliveryInstructions string `gorm:"column:DeliveryInstructions;not null" json:"DeliveryInstructions"`
	Clause               string `gorm:"column:Clause;not null" json:"Clause"`
	JobsList             string `gorm:"column:JobsList;not null" json:"JobsList"`
	PurchasesList        string `gorm:"column:PurchasesList;not null" json:"PurchasesList"`
}

// TableName OrdersText's table name
func (*OrdersText) TableName() string {
	return TableNameOrdersText
}
