// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameOrder = "Orders"

// Order mapped from table <Orders>
type Order struct {
	OrderID           int32     `gorm:"column:OrderId;primaryKey;autoIncrement:true" json:"OrderId"`
	OrderNo           string    `gorm:"column:OrderNo;not null" json:"OrderNo"`
	OrderNoFixedLen   string    `gorm:"column:OrderNoFixedLen;not null" json:"OrderNoFixedLen"`
	Type              string    `gorm:"column:Type;not null" json:"Type"`
	SupplierID        int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	Date              time.Time `gorm:"column:Date;not null" json:"Date"`
	LayoutID          int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	IssuedByID        int32     `gorm:"column:IssuedById" json:"IssuedById"`
	IssuedByName      string    `gorm:"column:IssuedByName;not null" json:"IssuedByName"`
	Reference         string    `gorm:"column:Reference;not null" json:"Reference"`
	Email             string    `gorm:"column:Email;not null" json:"Email"`
	FaxID             int32     `gorm:"column:FaxId" json:"FaxId"`
	EraID             int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa             time.Time `gorm:"column:Circa;not null" json:"Circa"`
	Amount            float64   `gorm:"column:Amount;not null;default:0.00" json:"Amount"`
	Jobs              string    `gorm:"column:Jobs" json:"Jobs"`
	Invoices          string    `gorm:"column:Invoices" json:"Invoices"`
	TransmitMethod    int32     `gorm:"column:TransmitMethod;not null" json:"TransmitMethod"`
	DeliverTo         int32     `gorm:"column:DeliverTo;not null" json:"DeliverTo"`
	DeliveryDue       time.Time `gorm:"column:DeliveryDue;not null" json:"DeliveryDue"`
	Status            string    `gorm:"column:Status;not null" json:"Status"`
	DataVersion       int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	DeliveryAddressID int32     `gorm:"column:DeliveryAddressId" json:"DeliveryAddressId"`
	XContactID        int32     `gorm:"column:XContactId" json:"XContactId"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
