// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePackage = "Packages"

// Package mapped from table <Packages>
type Package struct {
	PackageID   int32  `gorm:"column:PackageId;primaryKey;autoIncrement:true" json:"PackageId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Package's table name
func (*Package) TableName() string {
	return TableNamePackage
}
