// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayEventEmployeeItem = "PayEventEmployeeItems"

// PayEventEmployeeItem mapped from table <PayEventEmployeeItems>
type PayEventEmployeeItem struct {
	ID                 int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	PayEventEmployeeID int32   `gorm:"column:PayEventEmployeeId;not null" json:"PayEventEmployeeId"`
	Category           string  `gorm:"column:Category;not null" json:"Category"`
	Code               string  `gorm:"column:Code;not null" json:"Code"`
	Amount             float64 `gorm:"column:Amount;not null" json:"Amount"`
	Description        string  `gorm:"column:Description" json:"Description"`
}

// TableName PayEventEmployeeItem's table name
func (*PayEventEmployeeItem) TableName() string {
	return TableNamePayEventEmployeeItem
}
