// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayEventEmployee = "PayEventEmployees"

// PayEventEmployee mapped from table <PayEventEmployees>
type PayEventEmployee struct {
	ID                             int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	PayEventID                     int32     `gorm:"column:PayEventId;not null" json:"PayEventId"`
	TFN                            string    `gorm:"column:TFN;not null" json:"TFN"`
	FirstName                      string    `gorm:"column:FirstName;not null" json:"FirstName"`
	OtherName                      string    `gorm:"column:OtherName;not null" json:"OtherName"`
	Surname                        string    `gorm:"column:Surname;not null" json:"Surname"`
	Birthday                       time.Time `gorm:"column:Birthday" json:"Birthday"`
	EmploymentStart                time.Time `gorm:"column:EmploymentStart;not null" json:"EmploymentStart"`
	EmploymentEnd                  time.Time `gorm:"column:EmploymentEnd" json:"EmploymentEnd"`
	PaymentBasisCode               string    `gorm:"column:PaymentBasisCode;not null" json:"PaymentBasisCode"`
	TaxTreatmentCode               string    `gorm:"column:TaxTreatmentCode;not null" json:"TaxTreatmentCode"`
	CessationTypeCode              string    `gorm:"column:CessationTypeCode" json:"CessationTypeCode"`
	TaxOffset                      float64   `gorm:"column:TaxOffset" json:"TaxOffset"`
	OvertimeAmount                 float64   `gorm:"column:OvertimeAmount;not null" json:"OvertimeAmount"`
	BonusesAndCommissionsAmount    float64   `gorm:"column:BonusesAndCommissionsAmount;not null" json:"BonusesAndCommissionsAmount"`
	DirectorsFeesAmount            float64   `gorm:"column:DirectorsFeesAmount;not null" json:"DirectorsFeesAmount"`
	CDEPAmount                     float64   `gorm:"column:CDEPAmount" json:"CDEPAmount"`
	AddressID                      int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	PayrollEmployeeID              int32     `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	StartDate                      time.Time `gorm:"column:StartDate;not null" json:"StartDate"`
	EndDate                        time.Time `gorm:"column:EndDate;not null" json:"EndDate"`
	IsFinal                        bool      `gorm:"column:IsFinal;not null" json:"IsFinal"`
	IsTerminated                   bool      `gorm:"column:IsTerminated;not null" json:"IsTerminated"`
	PayrollGross                   float64   `gorm:"column:PayrollGross;not null;default:0.00" json:"PayrollGross"`
	PayrollNett                    float64   `gorm:"column:PayrollNett;not null;default:0.00" json:"PayrollNett"`
	Gross                          float64   `gorm:"column:Gross;not null;default:0.00" json:"Gross"`
	Tax                            float64   `gorm:"column:Tax;not null;default:0.00" json:"Tax"`
	Super                          float64   `gorm:"column:Super;not null;default:0.00" json:"Super"`
	ExcludedAllowances             float64   `gorm:"column:ExcludedAllowances;not null;default:0.00" json:"ExcludedAllowances"`
	DeductableAllowances           float64   `gorm:"column:DeductableAllowances;not null;default:0.00" json:"DeductableAllowances"`
	ReportableSuper                float64   `gorm:"column:ReportableSuper;not null;default:0.00" json:"ReportableSuper"`
	SalarySacrificeSuper           float64   `gorm:"column:SalarySacrificeSuper;not null;default:0.00" json:"SalarySacrificeSuper"`
	UnionFees                      float64   `gorm:"column:UnionFees;not null;default:0.00" json:"UnionFees"`
	WorkplaceGiving                float64   `gorm:"column:WorkplaceGiving;not null;default:0.00" json:"WorkplaceGiving"`
	OtherDeductions                float64   `gorm:"column:OtherDeductions;not null;default:0.00" json:"OtherDeductions"`
	LumpSumA                       float64   `gorm:"column:LumpSumA;not null;default:0.00" json:"LumpSumA"`
	LumpSumACode                   string    `gorm:"column:LumpSumACode" json:"LumpSumACode"`
	LumpSumB                       float64   `gorm:"column:LumpSumB;not null;default:0.00" json:"LumpSumB"`
	LumpSumD                       float64   `gorm:"column:LumpSumD;not null;default:0.00" json:"LumpSumD"`
	LumpSumE                       float64   `gorm:"column:LumpSumE;not null;default:0.00" json:"LumpSumE"`
	EtpCode                        string    `gorm:"column:EtpCode" json:"EtpCode"`
	EtpDate                        time.Time `gorm:"column:EtpDate" json:"EtpDate"`
	EtpTaxFreeComponent            float64   `gorm:"column:EtpTaxFreeComponent;not null;default:0.00" json:"EtpTaxFreeComponent"`
	EtpTaxableComponent            float64   `gorm:"column:EtpTaxableComponent;not null;default:0.00" json:"EtpTaxableComponent"`
	EtpTaxWithheld                 float64   `gorm:"column:EtpTaxWithheld;not null;default:0.00" json:"EtpTaxWithheld"`
	ReportableFringeBenefits       float64   `gorm:"column:ReportableFringeBenefits;not null;default:0.00" json:"ReportableFringeBenefits"`
	ReportableFringeBenefitsExempt float64   `gorm:"column:ReportableFringeBenefitsExempt;not null;default:0.00" json:"ReportableFringeBenefitsExempt"`
	ReconciledAt                   time.Time `gorm:"column:ReconciledAt" json:"ReconciledAt"`
	Status                         string    `gorm:"column:Status;not null" json:"Status"`
	StpLodged                      bool      `gorm:"column:StpLodged;not null" json:"StpLodged"`
	LastPayrollID                  int32     `gorm:"column:LastPayrollId;not null" json:"LastPayrollId"`
	CreatedAt                      time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	UpdatedAt                      time.Time `gorm:"column:UpdatedAt;not null" json:"UpdatedAt"`
	DeletedAt                      time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Version                        int32     `gorm:"column:Version;not null;default:1" json:"Version"`
}

// TableName PayEventEmployee's table name
func (*PayEventEmployee) TableName() string {
	return TableNamePayEventEmployee
}
