// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayEvent = "PayEvents"

// PayEvent mapped from table <PayEvents>
type PayEvent struct {
	ID                   int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Date                 time.Time `gorm:"column:Date;not null" json:"Date"`
	EmployerName         string    `gorm:"column:EmployerName;not null" json:"EmployerName"`
	EmployerAbn          string    `gorm:"column:EmployerAbn;not null" json:"EmployerAbn"`
	EmployerAddressID    int32     `gorm:"column:EmployerAddressId;not null" json:"EmployerAddressId"`
	EmployerContactName  string    `gorm:"column:EmployerContactName;not null" json:"EmployerContactName"`
	EmployerContactPhone string    `gorm:"column:EmployerContactPhone;not null" json:"EmployerContactPhone"`
	EmployerContactEmail string    `gorm:"column:EmployerContactEmail;not null" json:"EmployerContactEmail"`
	EmployeeCount        int32     `gorm:"column:EmployeeCount;not null" json:"EmployeeCount"`
	Gross                float64   `gorm:"column:Gross;not null;default:0.00" json:"Gross"`
	Tax                  float64   `gorm:"column:Tax;not null;default:0.00" json:"Tax"`
	IsFinal              bool      `gorm:"column:IsFinal;not null" json:"IsFinal"`
	AuthoriserID         int32     `gorm:"column:AuthoriserId" json:"AuthoriserId"`
	Status               string    `gorm:"column:Status;not null" json:"Status"`
	StpLodged            bool      `gorm:"column:StpLodged;not null" json:"StpLodged"`
	CreatedAt            time.Time `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	UpdatedAt            time.Time `gorm:"column:UpdatedAt;not null" json:"UpdatedAt"`
	DeletedAt            time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Version              int32     `gorm:"column:Version;not null;default:1" json:"Version"`
	PayrunID             int32     `gorm:"column:PayrunId" json:"PayrunId"`
}

// TableName PayEvent's table name
func (*PayEvent) TableName() string {
	return TableNamePayEvent
}
