// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePaymentMethod = "PaymentMethod"

// PaymentMethod mapped from table <PaymentMethod>
type PaymentMethod struct {
	PaymentMethodID int32  `gorm:"column:PaymentMethodId;primaryKey;autoIncrement:true" json:"PaymentMethodId"`
	Code            string `gorm:"column:Code;not null" json:"Code"`
	Description     string `gorm:"column:Description;not null" json:"Description"`
	Medium          string `gorm:"column:Medium;not null" json:"Medium"`
	Obsolete        bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PaymentMethod's table name
func (*PaymentMethod) TableName() string {
	return TableNamePaymentMethod
}
