// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsPaidAllowance = "PayrollsPaidAllowances"

// PayrollsPaidAllowance mapped from table <PayrollsPaidAllowances>
type PayrollsPaidAllowance struct {
	PayrollsPaidAllowanceID             int32   `gorm:"column:PayrollsPaidAllowanceId;primaryKey;autoIncrement:true" json:"PayrollsPaidAllowanceId"`
	PayrollID                           int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                               int32   `gorm:"column:RowId;not null" json:"RowId"`
	PayrollAllowanceID                  int32   `gorm:"column:PayrollAllowanceId;not null" json:"PayrollAllowanceId"`
	Reference                           string  `gorm:"column:Reference;not null" json:"Reference"`
	Quantity                            float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	PayrollUnitID                       int32   `gorm:"column:PayrollUnitId;not null" json:"PayrollUnitId"`
	Amount                              float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID                      int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID                     int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	DebitDivisionID                     int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID                    int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	AllowancesCode                      string  `gorm:"column:AllowancesCode;not null" json:"AllowancesCode"`
	AllowancesDescription               string  `gorm:"column:AllowancesDescription;not null" json:"AllowancesDescription"`
	AllowancesAmount                    float64 `gorm:"column:AllowancesAmount;not null" json:"AllowancesAmount"`
	AllowancesExcludeFromPaymentSummary bool    `gorm:"column:AllowancesExcludeFromPaymentSummary;not null" json:"AllowancesExcludeFromPaymentSummary"`
	AllowancesIncludeInSuper            bool    `gorm:"column:AllowancesIncludeInSuper;not null" json:"AllowancesIncludeInSuper"`
	AllowancesTaxable                   bool    `gorm:"column:AllowancesTaxable;not null" json:"AllowancesTaxable"`
}

// TableName PayrollsPaidAllowance's table name
func (*PayrollsPaidAllowance) TableName() string {
	return TableNamePayrollsPaidAllowance
}
