// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsLeavePayout = "PayrollsLeavePayout"

// PayrollsLeavePayout mapped from table <PayrollsLeavePayout>
type PayrollsLeavePayout struct {
	PayrollsLeavePayoutID int32   `gorm:"column:PayrollsLeavePayoutId;primaryKey;autoIncrement:true" json:"PayrollsLeavePayoutId"`
	PayrollID             int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                 int32   `gorm:"column:RowId;not null" json:"RowId"`
	PayrollTimeTypeID     int32   `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	Pre18Aug93            float64 `gorm:"column:Pre18Aug93;not null" json:"Pre18Aug93"`
	PriorThisPay          float64 `gorm:"column:PriorThisPay;not null" json:"PriorThisPay"`
	ThisPay               float64 `gorm:"column:ThisPay;not null" json:"ThisPay"`
}

// TableName PayrollsLeavePayout's table name
func (*PayrollsLeavePayout) TableName() string {
	return TableNamePayrollsLeavePayout
}
