// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollEmployeeStandardHour = "PayrollEmployeeStandardHours"

// PayrollEmployeeStandardHour mapped from table <PayrollEmployeeStandardHours>
type PayrollEmployeeStandardHour struct {
	PayrollEmployeeStandardHoursID int32   `gorm:"column:PayrollEmployeeStandardHoursId;primaryKey;autoIncrement:true" json:"PayrollEmployeeStandardHoursId"`
	PayrollEmployeeID              int32   `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	RowID                          int32   `gorm:"column:RowId;not null" json:"RowId"`
	PayrollTimeTypeID              int32   `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	PayrollAwardID                 int32   `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	Hours                          float64 `gorm:"column:Hours;not null" json:"Hours"`
	Amount                         float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID                 int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	DebitDivisionID                int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
}

// TableName PayrollEmployeeStandardHour's table name
func (*PayrollEmployeeStandardHour) TableName() string {
	return TableNamePayrollEmployeeStandardHour
}
