// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollPeriodRule = "PayrollPeriodRules"

// PayrollPeriodRule mapped from table <PayrollPeriodRules>
type PayrollPeriodRule struct {
	PayrollPeriodRuleID int32  `gorm:"column:PayrollPeriodRuleId;primaryKey;autoIncrement:true" json:"PayrollPeriodRuleId"`
	Code                string `gorm:"column:Code;not null" json:"Code"`
	Description         string `gorm:"column:Description;not null" json:"Description"`
}

// TableName PayrollPeriodRule's table name
func (*PayrollPeriodRule) TableName() string {
	return TableNamePayrollPeriodRule
}
