// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollUnit = "PayrollUnits"

// PayrollUnit mapped from table <PayrollUnits>
type PayrollUnit struct {
	PayrollUnitID int32  `gorm:"column:PayrollUnitId;primaryKey;autoIncrement:true" json:"PayrollUnitId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
	Obsolete      bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollUnit's table name
func (*PayrollUnit) TableName() string {
	return TableNamePayrollUnit
}
