// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollsNonWorkingHour = "PayrollsNonWorkingHours"

// PayrollsNonWorkingHour mapped from table <PayrollsNonWorkingHours>
type PayrollsNonWorkingHour struct {
	PayrollsNonWorkingHoursID int32     `gorm:"column:PayrollsNonWorkingHoursId;primaryKey;autoIncrement:true" json:"PayrollsNonWorkingHoursId"`
	PayrollID                 int32     `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                     int32     `gorm:"column:RowId;not null" json:"RowId"`
	PayrollTimeTypeID         int32     `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	StartDate                 time.Time `gorm:"column:StartDate;not null" json:"StartDate"`
	FinishDate                time.Time `gorm:"column:FinishDate;not null" json:"FinishDate"`
	Hours                     float64   `gorm:"column:Hours;not null" json:"Hours"`
	Granted                   bool      `gorm:"column:Granted;not null" json:"Granted"`
}

// TableName PayrollsNonWorkingHour's table name
func (*PayrollsNonWorkingHour) TableName() string {
	return TableNamePayrollsNonWorkingHour
}
