// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollEmployeeAllowance = "PayrollEmployeeAllowances"

// PayrollEmployeeAllowance mapped from table <PayrollEmployeeAllowances>
type PayrollEmployeeAllowance struct {
	PayrollEmployeeAllowanceID int32   `gorm:"column:PayrollEmployeeAllowanceId;primaryKey;autoIncrement:true" json:"PayrollEmployeeAllowanceId"`
	PayrollEmployeeID          int32   `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	PayrollAllowanceID         int32   `gorm:"column:PayrollAllowanceId;not null" json:"PayrollAllowanceId"`
	Reference                  string  `gorm:"column:Reference;not null" json:"Reference"`
	Quantity                   float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	PayrollUnitID              int32   `gorm:"column:PayrollUnitId;not null" json:"PayrollUnitId"`
	Amount                     float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID             int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	DebitDivisionID            int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	RowID                      int32   `gorm:"column:RowId;not null" json:"RowId"`
}

// TableName PayrollEmployeeAllowance's table name
func (*PayrollEmployeeAllowance) TableName() string {
	return TableNamePayrollEmployeeAllowance
}
