// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollAwardsDailyRule = "PayrollAwardsDailyRules"

// PayrollAwardsDailyRule mapped from table <PayrollAwardsDailyRules>
type PayrollAwardsDailyRule struct {
	PayrollAwardsDailyRuleID int32 `gorm:"column:PayrollAwardsDailyRuleId;primaryKey;autoIncrement:true" json:"PayrollAwardsDailyRuleId"`
	PayrollAwardID           int32 `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	PayrollDailyRuleID       int32 `gorm:"column:PayrollDailyRuleId;not null" json:"PayrollDailyRuleId"`
}

// TableName PayrollAwardsDailyRule's table name
func (*PayrollAwardsDailyRule) TableName() string {
	return TableNamePayrollAwardsDailyRule
}
