// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollEmployeeDeduction = "PayrollEmployeeDeductions"

// PayrollEmployeeDeduction mapped from table <PayrollEmployeeDeductions>
type PayrollEmployeeDeduction struct {
	PayrollEmployeeDeductionID int32   `gorm:"column:PayrollEmployeeDeductionId;primaryKey;autoIncrement:true" json:"PayrollEmployeeDeductionId"`
	PayrollEmployeeID          int32   `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	PayrollDeductionID         int32   `gorm:"column:PayrollDeductionId;not null" json:"PayrollDeductionId"`
	Reference                  string  `gorm:"column:Reference;not null" json:"Reference"`
	Quantity                   float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	PayrollUnitID              int32   `gorm:"column:PayrollUnitId" json:"PayrollUnitId"`
	Amount                     float64 `gorm:"column:Amount;not null" json:"Amount"`
	CreditAccountID            int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	CreditDivisionID           int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	RowID                      int32   `gorm:"column:RowId;not null" json:"RowId"`
}

// TableName PayrollEmployeeDeduction's table name
func (*PayrollEmployeeDeduction) TableName() string {
	return TableNamePayrollEmployeeDeduction
}
