// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollDailyRulesCoreHour = "PayrollDailyRulesCoreHours"

// PayrollDailyRulesCoreHour mapped from table <PayrollDailyRulesCoreHours>
type PayrollDailyRulesCoreHour struct {
	PayrollDailyRulesCoreHoursID int32  `gorm:"column:PayrollDailyRulesCoreHoursId;primaryKey;autoIncrement:true" json:"PayrollDailyRulesCoreHoursId"`
	PayRollDailyRuleID           int32  `gorm:"column:PayRollDailyRuleId;not null" json:"PayRollDailyRuleId"`
	BeforeTime                   string `gorm:"column:BeforeTime;not null" json:"BeforeTime"`
	PayrollTimeTypeID            int32  `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
}

// TableName PayrollDailyRulesCoreHour's table name
func (*PayrollDailyRulesCoreHour) TableName() string {
	return TableNamePayrollDailyRulesCoreHour
}
