// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollSetting = "PayrollSettings"

// PayrollSetting mapped from table <PayrollSettings>
type PayrollSetting struct {
	PayrollSettingID                 int32   `gorm:"column:PayrollSettingId;primaryKey" json:"PayrollSettingId"`
	SuperEmployerContributionPercent float64 `gorm:"column:SuperEmployerContributionPercent;not null;default:9.5000" json:"SuperEmployerContributionPercent"`
	PayrollTaxScaleID                int32   `gorm:"column:PayrollTaxScaleId;not null" json:"PayrollTaxScaleId"`
	PayrollSuperFundID               int32   `gorm:"column:PayrollSuperFundId" json:"PayrollSuperFundId"`
	DefaultWorkTimeTypeID            int32   `gorm:"column:DefaultWorkTimeTypeId" json:"DefaultWorkTimeTypeId"`
	DefaultHolidayTimeTypeID         int32   `gorm:"column:DefaultHolidayTimeTypeId" json:"DefaultHolidayTimeTypeId"`
	DefaultSickTimeTypeID            int32   `gorm:"column:DefaultSickTimeTypeId" json:"DefaultSickTimeTypeId"`
	DefaultPersonalTimeTypeID        int32   `gorm:"column:DefaultPersonalTimeTypeId" json:"DefaultPersonalTimeTypeId"`
	DefaultUnpaidTimeTypeID          int32   `gorm:"column:DefaultUnpaidTimeTypeId" json:"DefaultUnpaidTimeTypeId"`
	DefaultTILTimeTypeID             int32   `gorm:"column:DefaultTILTimeTypeId" json:"DefaultTILTimeTypeId"`
	DefaultPHTimeTypeID              int32   `gorm:"column:DefaultPHTimeTypeId" json:"DefaultPHTimeTypeId"`
	DataVersion                      int32   `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	BankingID                        int32   `gorm:"column:BankingId" json:"BankingId"`
	MessageTemplateID                int32   `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	HolidayTerminationTimeTypeID     int32   `gorm:"column:HolidayTerminationTimeTypeId" json:"HolidayTerminationTimeTypeId"`
	SickTerminationTimeTypeID        int32   `gorm:"column:SickTerminationTimeTypeId" json:"SickTerminationTimeTypeId"`
	TimeInLieuTerminationTimeTypeID  int32   `gorm:"column:TimeInLieuTerminationTimeTypeId" json:"TimeInLieuTerminationTimeTypeId"`
	ValidateEachPay                  bool    `gorm:"column:ValidateEachPay;not null;default:1" json:"ValidateEachPay"`
	LoadAllowancesFromTimesheets     string  `gorm:"column:LoadAllowancesFromTimesheets;not null" json:"LoadAllowancesFromTimesheets"`
}

// TableName PayrollSetting's table name
func (*PayrollSetting) TableName() string {
	return TableNamePayrollSetting
}
