// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollAllowance = "PayrollAllowances"

// PayrollAllowance mapped from table <PayrollAllowances>
type PayrollAllowance struct {
	PayrollAllowanceID        int32   `gorm:"column:PayrollAllowanceId;primaryKey;autoIncrement:true" json:"PayrollAllowanceId"`
	Code                      string  `gorm:"column:Code;not null" json:"Code"`
	Description               string  `gorm:"column:Description;not null" json:"Description"`
	Amount                    float64 `gorm:"column:Amount;not null" json:"Amount"`
	ExcludeFromPaymentSummary bool    `gorm:"column:ExcludeFromPaymentSummary;not null" json:"ExcludeFromPaymentSummary"`
	IncludeInSuper            bool    `gorm:"column:IncludeInSuper;not null" json:"IncludeInSuper"`
	Taxable                   bool    `gorm:"column:Taxable;not null" json:"Taxable"`
	PayrollUnitID             int32   `gorm:"column:PayrollUnitId" json:"PayrollUnitId"`
	DebitAccountID            int32   `gorm:"column:DebitAccountId" json:"DebitAccountId"`
	DebitDivisionID           int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	STPCategory               string  `gorm:"column:STPCategory;not null" json:"STPCategory"`
	Obsolete                  bool    `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollAllowance's table name
func (*PayrollAllowance) TableName() string {
	return TableNamePayrollAllowance
}
