// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollAwardsPeriodRule = "PayrollAwardsPeriodRules"

// PayrollAwardsPeriodRule mapped from table <PayrollAwardsPeriodRules>
type PayrollAwardsPeriodRule struct {
	PayrollAwardsPeriodRuleID int32 `gorm:"column:PayrollAwardsPeriodRuleId;primaryKey;autoIncrement:true" json:"PayrollAwardsPeriodRuleId"`
	PayrollAwardID            int32 `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	PayrollPeriodRuleID       int32 `gorm:"column:PayrollPeriodRuleId;not null" json:"PayrollPeriodRuleId"`
}

// TableName PayrollAwardsPeriodRule's table name
func (*PayrollAwardsPeriodRule) TableName() string {
	return TableNamePayrollAwardsPeriodRule
}
