// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollTaxScalesWeeklyWage = "PayrollTaxScalesWeeklyWages"

// PayrollTaxScalesWeeklyWage mapped from table <PayrollTaxScalesWeeklyWages>
type PayrollTaxScalesWeeklyWage struct {
	PayrollTaxScalesWeeklyWageID int32   `gorm:"column:PayrollTaxScalesWeeklyWageId;primaryKey;autoIncrement:true" json:"PayrollTaxScalesWeeklyWageId"`
	PayrollTaxScaleID            int32   `gorm:"column:PayrollTaxScaleId;not null" json:"PayrollTaxScaleId"`
	LessThan                     int32   `gorm:"column:LessThan;not null" json:"LessThan"`
	A                            float64 `gorm:"column:A;not null" json:"A"`
	B                            float64 `gorm:"column:B;not null" json:"B"`
}

// TableName PayrollTaxScalesWeeklyWage's table name
func (*PayrollTaxScalesWeeklyWage) TableName() string {
	return TableNamePayrollTaxScalesWeeklyWage
}
