// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayroll = "Payrolls"

// Payroll mapped from table <Payrolls>
type Payroll struct {
	PayrollID                 int32     `gorm:"column:PayrollId;primaryKey;autoIncrement:true" json:"PayrollId"`
	PayrollEmployeeID         int32     `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	Code                      string    `gorm:"column:Code;not null" json:"Code"`
	PreferredName             string    `gorm:"column:PreferredName;not null" json:"PreferredName"`
	FirstName                 string    `gorm:"column:FirstName;not null" json:"FirstName"`
	Surname                   string    `gorm:"column:Surname;not null" json:"Surname"`
	MiddleNames               string    `gorm:"column:MiddleNames;not null" json:"MiddleNames"`
	Occupation                string    `gorm:"column:Occupation;not null" json:"Occupation"`
	PayrollHours              float64   `gorm:"column:PayrollHours;default:0.0000" json:"PayrollHours"`
	PayCycle                  string    `gorm:"column:PayCycle;not null" json:"PayCycle"`
	StartPayPeriod            time.Time `gorm:"column:StartPayPeriod;not null" json:"StartPayPeriod"`
	PayPeriod                 time.Time `gorm:"column:PayPeriod;not null" json:"PayPeriod"`
	PaymentMethod             string    `gorm:"column:PaymentMethod;not null" json:"PaymentMethod"`
	Type                      string    `gorm:"column:Type;not null" json:"Type"`
	LumpSumA                  float64   `gorm:"column:LumpSumA;not null" json:"LumpSumA"`
	LumpSumB                  float64   `gorm:"column:LumpSumB;not null" json:"LumpSumB"`
	LumpSumC                  float64   `gorm:"column:LumpSumC;not null" json:"LumpSumC"`
	LumpSumD                  float64   `gorm:"column:LumpSumD;not null" json:"LumpSumD"`
	LumpSumE                  float64   `gorm:"column:LumpSumE;not null" json:"LumpSumE"`
	TaxAdjustment             float64   `gorm:"column:TaxAdjustment;not null" json:"TaxAdjustment"`
	NoOfPayCycles             int32     `gorm:"column:NoOfPayCycles;not null" json:"NoOfPayCycles"`
	Gross                     float64   `gorm:"column:Gross;not null" json:"Gross"`
	Nett                      float64   `gorm:"column:Nett;not null" json:"Nett"`
	CalculatedTax             float64   `gorm:"column:CalculatedTax;not null" json:"CalculatedTax"`
	Tax                       float64   `gorm:"column:Tax;not null" json:"Tax"`
	Allowances                float64   `gorm:"column:Allowances;not null" json:"Allowances"`
	Deductions                float64   `gorm:"column:Deductions;not null" json:"Deductions"`
	Super                     float64   `gorm:"column:Super;not null" json:"Super"`
	PayslipMemo               string    `gorm:"column:PayslipMemo" json:"PayslipMemo"`
	WorkedHours               float64   `gorm:"column:WorkedHours;not null" json:"WorkedHours"`
	TimeInLieuTaken           float64   `gorm:"column:TimeInLieuTaken;not null" json:"TimeInLieuTaken"`
	HolidayAccruedAdjustment  float64   `gorm:"column:HolidayAccruedAdjustment;not null;default:0.000000" json:"HolidayAccruedAdjustment"`
	HolidayAccrued            float64   `gorm:"column:HolidayAccrued;not null;default:0.000000" json:"HolidayAccrued"`
	HolidayTaken              float64   `gorm:"column:HolidayTaken;not null;default:0.000000" json:"HolidayTaken"`
	SickAccruedAdjustment     float64   `gorm:"column:SickAccruedAdjustment;not null;default:0.000000" json:"SickAccruedAdjustment"`
	SickAccrued               float64   `gorm:"column:SickAccrued;not null" json:"SickAccrued"`
	SickTaken                 float64   `gorm:"column:SickTaken;not null;default:0.000000" json:"SickTaken"`
	TaxDebitAccountID         int32     `gorm:"column:TaxDebitAccountId;not null" json:"TaxDebitAccountId"`
	TaxDebitDivisionID        int32     `gorm:"column:TaxDebitDivisionId" json:"TaxDebitDivisionId"`
	TaxCreditAccountID        int32     `gorm:"column:TaxCreditAccountId;not null" json:"TaxCreditAccountId"`
	TaxCreditDivisionID       int32     `gorm:"column:TaxCreditDivisionId" json:"TaxCreditDivisionId"`
	LumpSumCreditAccountID    int32     `gorm:"column:LumpSumCreditAccountId" json:"LumpSumCreditAccountId"`
	LumpSumCreditDivisionID   int32     `gorm:"column:LumpSumCreditDivisionId" json:"LumpSumCreditDivisionId"`
	LumpSumDebitAccountID     int32     `gorm:"column:LumpSumDebitAccountId" json:"LumpSumDebitAccountId"`
	LumpSumDebitDivisionID    int32     `gorm:"column:LumpSumDebitDivisionId" json:"LumpSumDebitDivisionId"`
	TimeInLieuAccrued         float64   `gorm:"column:TimeInLieuAccrued;not null" json:"TimeInLieuAccrued"`
	PersonalTaken             float64   `gorm:"column:PersonalTaken;not null" json:"PersonalTaken"`
	UnpaidTaken               float64   `gorm:"column:UnpaidTaken;not null" json:"UnpaidTaken"`
	PayrollsHeaderID          int32     `gorm:"column:PayrollsHeaderId" json:"PayrollsHeaderId"`
	Excluded                  bool      `gorm:"column:Excluded;not null" json:"Excluded"`
	Calculated                time.Time `gorm:"column:Calculated" json:"Calculated"`
	TimesheetsVerified        time.Time `gorm:"column:TimesheetsVerified" json:"TimesheetsVerified"`
	LeaveVerified             time.Time `gorm:"column:LeaveVerified" json:"LeaveVerified"`
	Validated                 time.Time `gorm:"column:Validated" json:"Validated"`
	PayslipCreated            time.Time `gorm:"column:PayslipCreated" json:"PayslipCreated"`
	EmailPayslipSent          time.Time `gorm:"column:EmailPayslipSent" json:"EmailPayslipSent"`
	ABAFileCreated            time.Time `gorm:"column:ABAFileCreated" json:"ABAFileCreated"`
	DatePaid                  time.Time `gorm:"column:DatePaid" json:"DatePaid"`
	Transactions              string    `gorm:"column:Transactions" json:"Transactions"`
	Finalised                 time.Time `gorm:"column:Finalised" json:"Finalised"`
	STPFinalEvent             time.Time `gorm:"column:STPFinalEvent" json:"STPFinalEvent"`
	EmailPayslip              string    `gorm:"column:EmailPayslip" json:"EmailPayslip"`
	TerminationDate           time.Time `gorm:"column:TerminationDate" json:"TerminationDate"`
	Status                    string    `gorm:"column:Status;not null" json:"Status"`
	AccrualBasedOnHoursWorked bool      `gorm:"column:AccrualBasedOnHoursWorked;not null" json:"AccrualBasedOnHoursWorked"`
	PayrollAwardID            int32     `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	AwardCode                 string    `gorm:"column:AwardCode;not null" json:"AwardCode"`
	AwardFixedAnnualLeave     float64   `gorm:"column:AwardFixedAnnualLeave;not null" json:"AwardFixedAnnualLeave"`
	AwardFixedSickLeave       float64   `gorm:"column:AwardFixedSickLeave;not null" json:"AwardFixedSickLeave"`
	AwardHoursPerWeek         float64   `gorm:"column:AwardHoursPerWeek;not null" json:"AwardHoursPerWeek"`
	EraID                     int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa                     time.Time `gorm:"column:Circa;not null;default:0000-00-00 00:00:00" json:"Circa"`
	Version                   int32     `gorm:"column:Version;not null" json:"Version"`
	EmailPayslipEnabled       bool      `gorm:"column:EmailPayslipEnabled;not null" json:"EmailPayslipEnabled"`
	AboveAwardRate            float64   `gorm:"column:AboveAwardRate" json:"AboveAwardRate"`
	WorkflowStatus            string    `gorm:"column:WorkflowStatus;not null" json:"WorkflowStatus"`
	WorkflowTimestamp         time.Time `gorm:"column:WorkflowTimestamp" json:"WorkflowTimestamp"`
	WorkflowMemo              string    `gorm:"column:WorkflowMemo;not null" json:"WorkflowMemo"`
	Manager                   string    `gorm:"column:Manager" json:"Manager"`
	NoticeGiven               time.Time `gorm:"column:NoticeGiven" json:"NoticeGiven"`
	NoticeAdvice              string    `gorm:"column:NoticeAdvice;not null" json:"NoticeAdvice"`
	NoticeAuthorised          bool      `gorm:"column:NoticeAuthorised;not null" json:"NoticeAuthorised"`
	TerminationReason         string    `gorm:"column:TerminationReason;not null" json:"TerminationReason"`
	TerminationDetails        string    `gorm:"column:TerminationDetails;not null" json:"TerminationDetails"`
	ETPRequired               bool      `gorm:"column:ETPRequired;not null" json:"ETPRequired"`
	ETPCode                   string    `gorm:"column:ETPCode;not null" json:"ETPCode"`
	ETPTaxable                float64   `gorm:"column:ETPTaxable;not null" json:"ETPTaxable"`
	ETPTaxFree                float64   `gorm:"column:ETPTaxFree;not null" json:"ETPTaxFree"`
	ETPTax                    float64   `gorm:"column:ETPTax;not null" json:"ETPTax"`
	PaymentAuthorised         bool      `gorm:"column:PaymentAuthorised;not null" json:"PaymentAuthorised"`
	PayslipFileID             int32     `gorm:"column:PayslipFileId" json:"PayslipFileId"`
	DataVersion               int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	TaxScaleNo                string    `gorm:"column:TaxScaleNo;not null" json:"TaxScaleNo"`
	Resident                  bool      `gorm:"column:Resident;not null" json:"Resident"`
	TaxFreeThreshold          bool      `gorm:"column:TaxFreeThreshold;not null" json:"TaxFreeThreshold"`
	HelpTSLDebt               bool      `gorm:"column:HelpTSLDebt;not null" json:"HelpTSLDebt"`
	FSDebt                    bool      `gorm:"column:FSDebt;not null" json:"FSDebt"`
	Dependant                 int32     `gorm:"column:Dependant;not null" json:"Dependant"`
	StpStatus                 string    `gorm:"column:StpStatus" json:"StpStatus"`
	StpResubmit               bool      `gorm:"column:StpResubmit;not null" json:"StpResubmit"`
}

// TableName Payroll's table name
func (*Payroll) TableName() string {
	return TableNamePayroll
}
