// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollAward = "PayrollAwards"

// PayrollAward mapped from table <PayrollAwards>
type PayrollAward struct {
	PayrollAwardID   int32     `gorm:"column:PayrollAwardId;primaryKey;autoIncrement:true" json:"PayrollAwardId"`
	Code             string    `gorm:"column:Code;not null" json:"Code"`
	Description      string    `gorm:"column:Description;not null" json:"Description"`
	Rate             float64   `gorm:"column:Rate" json:"Rate"`
	AnnualLeave      float64   `gorm:"column:AnnualLeave" json:"AnnualLeave"`
	SickLeave        float64   `gorm:"column:SickLeave" json:"SickLeave"`
	HoursPerWeek     float64   `gorm:"column:HoursPerWeek;not null" json:"HoursPerWeek"`
	LastModified     time.Time `gorm:"column:LastModified;not null" json:"LastModified"`
	MinutesRounding  int32     `gorm:"column:MinutesRounding;not null" json:"MinutesRounding"`
	FixedAnnualLeave float64   `gorm:"column:FixedAnnualLeave;not null" json:"FixedAnnualLeave"`
	FixedSickLeave   float64   `gorm:"column:FixedSickLeave;not null" json:"FixedSickLeave"`
	Obsolete         bool      `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollAward's table name
func (*PayrollAward) TableName() string {
	return TableNamePayrollAward
}
