// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollSchedule = "PayrollSchedules"

// PayrollSchedule mapped from table <PayrollSchedules>
type PayrollSchedule struct {
	PayrollScheduleID       int32     `gorm:"column:PayrollScheduleId;primaryKey;autoIncrement:true" json:"PayrollScheduleId"`
	RowID                   int32     `gorm:"column:RowId;not null" json:"RowId"`
	Description             string    `gorm:"column:Description;not null" json:"Description"`
	Frequency               string    `gorm:"column:Frequency;not null" json:"Frequency"`
	NextPayrollPeriodEnding time.Time `gorm:"column:NextPayrollPeriodEnding;not null" json:"NextPayrollPeriodEnding"`
	ButtonColour            string    `gorm:"column:ButtonColour;not null;default:#304978" json:"ButtonColour"`
}

// TableName PayrollSchedule's table name
func (*PayrollSchedule) TableName() string {
	return TableNamePayrollSchedule
}
