// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollDailyRule = "PayrollDailyRules"

// PayrollDailyRule mapped from table <PayrollDailyRules>
type PayrollDailyRule struct {
	PayRollDailyRuleID int32     `gorm:"column:PayRollDailyRuleId;primaryKey;autoIncrement:true" json:"PayRollDailyRuleId"`
	Code               string    `gorm:"column:Code;not null" json:"Code"`
	Description        string    `gorm:"column:Description;not null" json:"Description"`
	ApplyMon           bool      `gorm:"column:ApplyMon;not null" json:"ApplyMon"`
	ApplyTue           bool      `gorm:"column:ApplyTue;not null" json:"ApplyTue"`
	ApplyWed           bool      `gorm:"column:ApplyWed;not null" json:"ApplyWed"`
	ApplyThu           bool      `gorm:"column:ApplyThu;not null" json:"ApplyThu"`
	ApplyFri           bool      `gorm:"column:ApplyFri;not null" json:"ApplyFri"`
	ApplySat           bool      `gorm:"column:ApplySat;not null" json:"ApplySat"`
	ApplySun           bool      `gorm:"column:ApplySun;not null" json:"ApplySun"`
	ApplyPublicHoliday bool      `gorm:"column:ApplyPublicHoliday;not null" json:"ApplyPublicHoliday"`
	ApplyThisDate      time.Time `gorm:"column:ApplyThisDate" json:"ApplyThisDate"`
	InEarly            bool      `gorm:"column:InEarly;not null" json:"InEarly"`
	InEarlyTime        string    `gorm:"column:InEarlyTime" json:"InEarlyTime"`
	InEarlyFloat       bool      `gorm:"column:InEarlyFloat;not null" json:"InEarlyFloat"`
	InEarlyFloatTime   string    `gorm:"column:InEarlyFloatTime" json:"InEarlyFloatTime"`
	InLate             bool      `gorm:"column:InLate;not null" json:"InLate"`
	InLateTime         string    `gorm:"column:InLateTime" json:"InLateTime"`
	InLateFloat        bool      `gorm:"column:InLateFloat;not null" json:"InLateFloat"`
	InLateFloatTime    string    `gorm:"column:InLateFloatTime" json:"InLateFloatTime"`
	OutEarly           bool      `gorm:"column:OutEarly;not null" json:"OutEarly"`
	OutEarlyTime       string    `gorm:"column:OutEarlyTime" json:"OutEarlyTime"`
	OutEarlyFloat      bool      `gorm:"column:OutEarlyFloat;not null" json:"OutEarlyFloat"`
	OutEarlyFloatTime  string    `gorm:"column:OutEarlyFloatTime" json:"OutEarlyFloatTime"`
	OutLate            bool      `gorm:"column:OutLate;not null" json:"OutLate"`
	OutLateTime        string    `gorm:"column:OutLateTime" json:"OutLateTime"`
	OutLateFloat       bool      `gorm:"column:OutLateFloat;not null" json:"OutLateFloat"`
	OutLateFloatTime   string    `gorm:"column:OutLateFloatTime" json:"OutLateFloatTime"`
	Obsolete           bool      `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollDailyRule's table name
func (*PayrollDailyRule) TableName() string {
	return TableNamePayrollDailyRule
}
