// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollDeduction = "PayrollDeductions"

// PayrollDeduction mapped from table <PayrollDeductions>
type PayrollDeduction struct {
	PayrollDeductionID int32   `gorm:"column:PayrollDeductionId;primaryKey;autoIncrement:true" json:"PayrollDeductionId"`
	Code               string  `gorm:"column:Code;not null" json:"Code"`
	Description        string  `gorm:"column:Description;not null" json:"Description"`
	Amount             float64 `gorm:"column:Amount" json:"Amount"`
	BeforeTax          bool    `gorm:"column:BeforeTax;not null" json:"BeforeTax"`
	PayrollUnitID      int32   `gorm:"column:PayrollUnitId" json:"PayrollUnitId"`
	Type               int32   `gorm:"column:Type;not null" json:"Type"`
	PercentOption      string  `gorm:"column:PercentOption" json:"PercentOption"`
	CreditAccountID    int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	CreditDivisionID   int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	Obsolete           bool    `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollDeduction's table name
func (*PayrollDeduction) TableName() string {
	return TableNamePayrollDeduction
}
