// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollEmployeeSuperannuation = "PayrollEmployeeSuperannuation"

// PayrollEmployeeSuperannuation mapped from table <PayrollEmployeeSuperannuation>
type PayrollEmployeeSuperannuation struct {
	PayrollEmployeeSuperannuationID int32   `gorm:"column:PayrollEmployeeSuperannuationId;primaryKey;autoIncrement:true" json:"PayrollEmployeeSuperannuationId"`
	PayrollEmployeeID               int32   `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	PayrollSuperFundID              int32   `gorm:"column:PayrollSuperFundId;not null" json:"PayrollSuperFundId"`
	MemberNo                        string  `gorm:"column:MemberNo;not null" json:"MemberNo"`
	Reportable                      bool    `gorm:"column:Reportable;not null" json:"Reportable"`
	Percent                         float64 `gorm:"column:Percent;not null" json:"Percent"`
	Contribution                    float64 `gorm:"column:Contribution;not null" json:"Contribution"`
	DebitAccountID                  int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	DebitDivisionID                 int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	RowID                           int32   `gorm:"column:RowId;not null" json:"RowId"`
	BPAYReferenceCode               int32   `gorm:"column:BPAYReferenceCode" json:"BPAYReferenceCode"`
	PercentEnabled                  bool    `gorm:"column:PercentEnabled;not null;default:1" json:"PercentEnabled"`
}

// TableName PayrollEmployeeSuperannuation's table name
func (*PayrollEmployeeSuperannuation) TableName() string {
	return TableNamePayrollEmployeeSuperannuation
}
