// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollEmployeeBanking = "PayrollEmployeeBanking"

// PayrollEmployeeBanking mapped from table <PayrollEmployeeBanking>
type PayrollEmployeeBanking struct {
	PayrollEmployeeBankingID int32   `gorm:"column:PayrollEmployeeBankingId;primaryKey;autoIncrement:true" json:"PayrollEmployeeBankingId"`
	PayrollEmployeeID        int32   `gorm:"column:PayrollEmployeeId;not null" json:"PayrollEmployeeId"`
	RowID                    int32   `gorm:"column:RowId;not null" json:"RowId"`
	BankID                   int32   `gorm:"column:BankId;not null" json:"BankId"`
	AccountNo                string  `gorm:"column:AccountNo;not null" json:"AccountNo"`
	AccountTitle             string  `gorm:"column:AccountTitle;not null" json:"AccountTitle"`
	BankAllocation           float64 `gorm:"column:BankAllocation;not null" json:"BankAllocation"`
	NewAccountFlag           string  `gorm:"column:NewAccountFlag;not null" json:"NewAccountFlag"`
}

// TableName PayrollEmployeeBanking's table name
func (*PayrollEmployeeBanking) TableName() string {
	return TableNamePayrollEmployeeBanking
}
