// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollTerminationReason = "PayrollTerminationReasons"

// PayrollTerminationReason mapped from table <PayrollTerminationReasons>
type PayrollTerminationReason struct {
	PayrollTerminationReasonID int32  `gorm:"column:PayrollTerminationReasonId;primaryKey;autoIncrement:true" json:"PayrollTerminationReasonId"`
	Code                       string `gorm:"column:Code;not null" json:"Code"`
	Description                string `gorm:"column:Description;not null" json:"Description"`
}

// TableName PayrollTerminationReason's table name
func (*PayrollTerminationReason) TableName() string {
	return TableNamePayrollTerminationReason
}
