// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsHoursWorked = "PayrollsHoursWorked"

// PayrollsHoursWorked mapped from table <PayrollsHoursWorked>
type PayrollsHoursWorked struct {
	PayrollsHoursWorkedID           int32   `gorm:"column:PayrollsHoursWorkedId;primaryKey;autoIncrement:true" json:"PayrollsHoursWorkedId"`
	PayrollID                       int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                           int32   `gorm:"column:RowId;not null" json:"RowId"`
	PayrollTimeTypeID               int32   `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	PayrollAwardID                  int32   `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	Hours                           float64 `gorm:"column:Hours;not null" json:"Hours"`
	Amount                          float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID                  int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID                 int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	DebitDivisionID                 int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID                int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	TimeTypeCode                    string  `gorm:"column:TimeTypeCode;not null" json:"TimeTypeCode"`
	TimeTypeDescription             string  `gorm:"column:TimeTypeDescription;not null" json:"TimeTypeDescription"`
	TimeTypeStandardRateFactor      float64 `gorm:"column:TimeTypeStandardRateFactor;not null" json:"TimeTypeStandardRateFactor"`
	TimeTypeAdditionalRate          float64 `gorm:"column:TimeTypeAdditionalRate;not null" json:"TimeTypeAdditionalRate"`
	TimeTypeAccrueLeaveEntitlements bool    `gorm:"column:TimeTypeAccrueLeaveEntitlements;not null" json:"TimeTypeAccrueLeaveEntitlements"`
	TimeTypeCategory                string  `gorm:"column:TimeTypeCategory;not null" json:"TimeTypeCategory"`
	TimeTypeOvertime                bool    `gorm:"column:TimeTypeOvertime;not null" json:"TimeTypeOvertime"`
}

// TableName PayrollsHoursWorked's table name
func (*PayrollsHoursWorked) TableName() string {
	return TableNamePayrollsHoursWorked
}
