// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollEmployee = "PayrollEmployees"

// PayrollEmployee mapped from table <PayrollEmployees>
type PayrollEmployee struct {
	PayrollEmployeeID               int32     `gorm:"column:PayrollEmployeeId;primaryKey" json:"PayrollEmployeeId"`
	PayrollScheduleID               int32     `gorm:"column:PayrollScheduleId" json:"PayrollScheduleId"`
	Method                          string    `gorm:"column:Method;not null" json:"Method"`
	PayType                         string    `gorm:"column:PayType;not null" json:"PayType"`
	TaxAdjustment                   float64   `gorm:"column:TaxAdjustment;not null" json:"TaxAdjustment"`
	LastPayPeriodEnding             time.Time `gorm:"column:LastPayPeriodEnding" json:"LastPayPeriodEnding"`
	PayrollAwardID                  int32     `gorm:"column:PayrollAwardId;not null" json:"PayrollAwardId"`
	AccrualBasedOnHoursWorked       bool      `gorm:"column:AccrualBasedOnHoursWorked;not null" json:"AccrualBasedOnHoursWorked"`
	AboveAwardRate                  float64   `gorm:"column:AboveAwardRate" json:"AboveAwardRate"`
	PaymentSummaryPrinted           time.Time `gorm:"column:PaymentSummaryPrinted" json:"PaymentSummaryPrinted"`
	PaymentSummaryIssued            time.Time `gorm:"column:PaymentSummaryIssued" json:"PaymentSummaryIssued"`
	EmailPayslip                    string    `gorm:"column:EmailPayslip;not null" json:"EmailPayslip"`
	EmailVerified                   bool      `gorm:"column:EmailVerified;not null" json:"EmailVerified"`
	EmailVerificationToken          string    `gorm:"column:EmailVerificationToken" json:"EmailVerificationToken"`
	EmailVerificationTokenCreatedAt time.Time `gorm:"column:EmailVerificationTokenCreatedAt" json:"EmailVerificationTokenCreatedAt"`
	EraID                           int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa                           time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DeclarationDate                 time.Time `gorm:"column:DeclarationDate;not null" json:"DeclarationDate"`
	TaxFileNumber                   string    `gorm:"column:TaxFileNumber;not null" json:"TaxFileNumber"`
	Resident                        bool      `gorm:"column:Resident;not null" json:"Resident"`
	TaxFreeThreshold                bool      `gorm:"column:TaxFreeThreshold;not null" json:"TaxFreeThreshold"`
	CarriedOverAsAt                 time.Time `gorm:"column:CarriedOverAsAt" json:"CarriedOverAsAt"`
	CarriedOverHolidayLeave         float64   `gorm:"column:CarriedOverHolidayLeave;not null" json:"CarriedOverHolidayLeave"`
	CarriedOverSickLeave            float64   `gorm:"column:CarriedOverSickLeave;not null" json:"CarriedOverSickLeave"`
	CarriedOverTimeInLieu           float64   `gorm:"column:CarriedOverTimeInLieu;not null" json:"CarriedOverTimeInLieu"`
	EmailPayslipEnabled             bool      `gorm:"column:EmailPayslipEnabled;not null" json:"EmailPayslipEnabled"`
	TaxScaleNo                      string    `gorm:"column:TaxScaleNo;not null" json:"TaxScaleNo"`
	TaxFileNumberProvision          string    `gorm:"column:TaxFileNumberProvision;not null;default:0" json:"TaxFileNumberProvision"`
	HelpTSLDebt                     bool      `gorm:"column:HelpTSLDebt;not null" json:"HelpTSLDebt"`
	FSDebt                          bool      `gorm:"column:FSDebt;not null" json:"FSDebt"`
	ClaimTaxOffset                  bool      `gorm:"column:ClaimTaxOffset;not null" json:"ClaimTaxOffset"`
	TaxOffset                       float64   `gorm:"column:TaxOffset;not null" json:"TaxOffset"`
	TaxOffsetDetails                string    `gorm:"column:TaxOffsetDetails;not null" json:"TaxOffsetDetails"`
	MedicareLevy                    string    `gorm:"column:MedicareLevy;not null;default:0" json:"MedicareLevy"`
	MedicareSurcharge               string    `gorm:"column:MedicareSurcharge;not null;default:0" json:"MedicareSurcharge"`
	MedicareLevyReduction           bool      `gorm:"column:MedicareLevyReduction;not null" json:"MedicareLevyReduction"`
	Spouse                          bool      `gorm:"column:Spouse;not null" json:"Spouse"`
	Dependant                       int32     `gorm:"column:Dependant;not null" json:"Dependant"`
	DataVersion                     int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	WagesPostingAccountID           int32     `gorm:"column:WagesPostingAccountId" json:"WagesPostingAccountId"`
	WagesPostingDivisionID          int32     `gorm:"column:WagesPostingDivisionId" json:"WagesPostingDivisionId"`
	AllowancesPostingAccountID      int32     `gorm:"column:AllowancesPostingAccountId" json:"AllowancesPostingAccountId"`
	AllowancesPostingDivisionID     int32     `gorm:"column:AllowancesPostingDivisionId" json:"AllowancesPostingDivisionId"`
	SuperannuationPostingAccountID  int32     `gorm:"column:SuperannuationPostingAccountId" json:"SuperannuationPostingAccountId"`
	SuperannuationPostingDivisionID int32     `gorm:"column:SuperannuationPostingDivisionId" json:"SuperannuationPostingDivisionId"`
	DeductionsPostingAccountID      int32     `gorm:"column:DeductionsPostingAccountId" json:"DeductionsPostingAccountId"`
	DeductionsPostingDivisionID     int32     `gorm:"column:DeductionsPostingDivisionId" json:"DeductionsPostingDivisionId"`
	DivisionID                      int32     `gorm:"column:DivisionId" json:"DivisionId"`
	ExcludedFromPaymentSummary      bool      `gorm:"column:ExcludedFromPaymentSummary;not null" json:"ExcludedFromPaymentSummary"`
	TimeInLieuTimeTypeID            int32     `gorm:"column:TimeInLieuTimeTypeId" json:"TimeInLieuTimeTypeId"`
	TimeInLieuBankedHours           float64   `gorm:"column:TimeInLieuBankedHours" json:"TimeInLieuBankedHours"`
	PayslipMemo                     string    `gorm:"column:PayslipMemo" json:"PayslipMemo"`
}

// TableName PayrollEmployee's table name
func (*PayrollEmployee) TableName() string {
	return TableNamePayrollEmployee
}
