// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollTimeType = "PayrollTimeTypes"

// PayrollTimeType mapped from table <PayrollTimeTypes>
type PayrollTimeType struct {
	PayrollTimeTypeID       int32   `gorm:"column:PayrollTimeTypeId;primaryKey;autoIncrement:true" json:"PayrollTimeTypeId"`
	Code                    string  `gorm:"column:Code;not null" json:"Code"`
	Description             string  `gorm:"column:Description;not null" json:"Description"`
	StandardRateFactor      float64 `gorm:"column:StandardRateFactor;not null" json:"StandardRateFactor"`
	AdditionalRate          float64 `gorm:"column:AdditionalRate;not null" json:"AdditionalRate"`
	AccrueLeaveEntitlements bool    `gorm:"column:AccrueLeaveEntitlements;not null" json:"AccrueLeaveEntitlements"`
	LeavePayout             bool    `gorm:"column:LeavePayout;not null" json:"LeavePayout"`
	Category                string  `gorm:"column:Category;not null" json:"Category"`
	Overtime                bool    `gorm:"column:Overtime;not null" json:"Overtime"`
	RosteredDaysOn          int32   `gorm:"column:RosteredDaysOn" json:"RosteredDaysOn"`
	RosteredDaysOff         int32   `gorm:"column:RosteredDaysOff" json:"RosteredDaysOff"`
	DebitAccountID          int32   `gorm:"column:DebitAccountId" json:"DebitAccountId"`
	DebitDivisionID         int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	Obsolete                bool    `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName PayrollTimeType's table name
func (*PayrollTimeType) TableName() string {
	return TableNamePayrollTimeType
}
