// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollsHeader = "PayrollsHeader"

// PayrollsHeader mapped from table <PayrollsHeader>
type PayrollsHeader struct {
	PayrollsHeaderID              int32     `gorm:"column:PayrollsHeaderId;primaryKey;autoIncrement:true" json:"PayrollsHeaderId"`
	PayrollScheduleID             int32     `gorm:"column:PayrollScheduleId" json:"PayrollScheduleId"`
	PayCycle                      string    `gorm:"column:PayCycle;not null" json:"PayCycle"`
	PayPeriod                     time.Time `gorm:"column:PayPeriod;not null" json:"PayPeriod"`
	Employees                     int32     `gorm:"column:Employees" json:"Employees"`
	Nett                          float64   `gorm:"column:Nett" json:"Nett"`
	Tax                           float64   `gorm:"column:Tax" json:"Tax"`
	Super                         float64   `gorm:"column:Super" json:"Super"`
	Worked                        float64   `gorm:"column:Worked" json:"Worked"`
	Holiday                       float64   `gorm:"column:Holiday" json:"Holiday"`
	Sick                          float64   `gorm:"column:Sick" json:"Sick"`
	Unpaid                        float64   `gorm:"column:Unpaid" json:"Unpaid"`
	Gross                         float64   `gorm:"column:Gross;not null" json:"Gross"`
	WorkflowStatus                string    `gorm:"column:WorkflowStatus;not null" json:"WorkflowStatus"`
	WorkflowTimestamp             time.Time `gorm:"column:WorkflowTimestamp" json:"WorkflowTimestamp"`
	EraID                         int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	PayslipMemo                   string    `gorm:"column:PayslipMemo" json:"PayslipMemo"`
	ABAProcessDate                time.Time `gorm:"column:ABAProcessDate" json:"ABAProcessDate"`
	ABAFileCreatedTime            time.Time `gorm:"column:ABAFileCreatedTime" json:"ABAFileCreatedTime"`
	Circa                         time.Time `gorm:"column:Circa;not null" json:"Circa"`
	Version                       int32     `gorm:"column:Version;not null" json:"Version"`
	Calculated                    time.Time `gorm:"column:Calculated" json:"Calculated"`
	TimesheetVerified             time.Time `gorm:"column:TimesheetVerified" json:"TimesheetVerified"`
	LeaveAuthorised               time.Time `gorm:"column:LeaveAuthorised" json:"LeaveAuthorised"`
	Validated                     time.Time `gorm:"column:Validated" json:"Validated"`
	PayslipCreated                time.Time `gorm:"column:PayslipCreated" json:"PayslipCreated"`
	EmailPayslipSent              time.Time `gorm:"column:EmailPayslipSent" json:"EmailPayslipSent"`
	ABAFileProcessed              time.Time `gorm:"column:ABAFileProcessed" json:"ABAFileProcessed"`
	ABAPaid                       time.Time `gorm:"column:ABAPaid" json:"ABAPaid"`
	EmployeesPaid                 time.Time `gorm:"column:EmployeesPaid" json:"EmployeesPaid"`
	Finalised                     time.Time `gorm:"column:Finalised" json:"Finalised"`
	Superceded                    bool      `gorm:"column:Superceded;not null" json:"Superceded"`
	DataVersion                   int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	BankingID                     int32     `gorm:"column:BankingId" json:"BankingId"`
	ABAFileID                     int32     `gorm:"column:ABAFileId" json:"ABAFileId"`
	AuthoriseABA                  bool      `gorm:"column:AuthoriseABA;not null" json:"AuthoriseABA"`
	AuthoriseNonABA               bool      `gorm:"column:AuthoriseNonABA;not null" json:"AuthoriseNonABA"`
	PayslipMessageTemplateSubject string    `gorm:"column:PayslipMessageTemplateSubject;not null" json:"PayslipMessageTemplateSubject"`
	PayslipMessageTemplateBody    string    `gorm:"column:PayslipMessageTemplateBody;not null" json:"PayslipMessageTemplateBody"`
	PayslipFromEmailAccountID     int32     `gorm:"column:PayslipFromEmailAccountId" json:"PayslipFromEmailAccountId"`
	PayEventID                    int32     `gorm:"column:PayEventId" json:"PayEventId"`
}

// TableName PayrollsHeader's table name
func (*PayrollsHeader) TableName() string {
	return TableNamePayrollsHeader
}
