// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayrollTaxScale = "PayrollTaxScales"

// PayrollTaxScale mapped from table <PayrollTaxScales>
type PayrollTaxScale struct {
	PayrollTaxScaleID int32     `gorm:"column:PayrollTaxScaleId;primaryKey;autoIncrement:true" json:"PayrollTaxScaleId"`
	ScaleNo           string    `gorm:"column:ScaleNo;not null" json:"ScaleNo"`
	Description       string    `gorm:"column:Description;not null" json:"Description"`
	Effective         time.Time `gorm:"column:Effective;not null" json:"Effective"`
}

// TableName PayrollTaxScale's table name
func (*PayrollTaxScale) TableName() string {
	return TableNamePayrollTaxScale
}
