// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsPaidDeduction = "PayrollsPaidDeductions"

// PayrollsPaidDeduction mapped from table <PayrollsPaidDeductions>
type PayrollsPaidDeduction struct {
	PayrollsPaidDeductionID int32   `gorm:"column:PayrollsPaidDeductionId;primaryKey;autoIncrement:true" json:"PayrollsPaidDeductionId"`
	PayrollID               int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                   int32   `gorm:"column:RowId;not null" json:"RowId"`
	PayrollDeductionID      int32   `gorm:"column:PayrollDeductionId;not null" json:"PayrollDeductionId"`
	Reference               string  `gorm:"column:Reference;not null" json:"Reference"`
	Quantity                float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	PayrollUnitID           int32   `gorm:"column:PayrollUnitId" json:"PayrollUnitId"`
	Amount                  float64 `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID          int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID         int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	DebitDivisionID         int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID        int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	DeductionsCode          string  `gorm:"column:DeductionsCode;not null" json:"DeductionsCode"`
	DeductionsDescription   string  `gorm:"column:DeductionsDescription;not null" json:"DeductionsDescription"`
	DeductionsAmount        float64 `gorm:"column:DeductionsAmount;not null" json:"DeductionsAmount"`
	DeductionsBeforeTax     bool    `gorm:"column:DeductionsBeforeTax;not null" json:"DeductionsBeforeTax"`
	DeductionsType          int32   `gorm:"column:DeductionsType;not null" json:"DeductionsType"`
}

// TableName PayrollsPaidDeduction's table name
func (*PayrollsPaidDeduction) TableName() string {
	return TableNamePayrollsPaidDeduction
}
