// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollDailyRulesWorkHour = "PayrollDailyRulesWorkHours"

// PayrollDailyRulesWorkHour mapped from table <PayrollDailyRulesWorkHours>
type PayrollDailyRulesWorkHour struct {
	PayrollDailyRulesWorkHoursID int32  `gorm:"column:PayrollDailyRulesWorkHoursId;primaryKey;autoIncrement:true" json:"PayrollDailyRulesWorkHoursId"`
	PayRollDailyRuleID           int32  `gorm:"column:PayRollDailyRuleId;not null" json:"PayRollDailyRuleId"`
	PayrollTimeTypeID            int32  `gorm:"column:PayrollTimeTypeId;not null" json:"PayrollTimeTypeId"`
	Priority                     int32  `gorm:"column:Priority;not null" json:"Priority"`
	Threshold                    string `gorm:"column:Threshold;not null" json:"Threshold"`
	Minimum                      string `gorm:"column:Minimum;not null" json:"Minimum"`
}

// TableName PayrollDailyRulesWorkHour's table name
func (*PayrollDailyRulesWorkHour) TableName() string {
	return TableNamePayrollDailyRulesWorkHour
}
