// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsBanking = "PayrollsBanking"

// PayrollsBanking mapped from table <PayrollsBanking>
type PayrollsBanking struct {
	PayrollsBankingID int32   `gorm:"column:PayrollsBankingId;primaryKey;autoIncrement:true" json:"PayrollsBankingId"`
	PayrollID         int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID             int32   `gorm:"column:RowId;not null" json:"RowId"`
	BankID            int32   `gorm:"column:BankId;not null" json:"BankId"`
	AccountNo         string  `gorm:"column:AccountNo;not null" json:"AccountNo"`
	AccountName       string  `gorm:"column:AccountName;not null" json:"AccountName"`
	Preset            float64 `gorm:"column:Preset;not null" json:"Preset"`
	Deposit           float64 `gorm:"column:Deposit;not null" json:"Deposit"`
	NewAccountFlag    bool    `gorm:"column:NewAccountFlag;not null" json:"NewAccountFlag"`
}

// TableName PayrollsBanking's table name
func (*PayrollsBanking) TableName() string {
	return TableNamePayrollsBanking
}
