// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollAwardsText = "PayrollAwardsText"

// PayrollAwardsText mapped from table <PayrollAwardsText>
type PayrollAwardsText struct {
	PayrollAwardsTextID int32  `gorm:"column:PayrollAwardsTextId;primaryKey" json:"PayrollAwardsTextId"`
	Notes               string `gorm:"column:Notes;not null" json:"Notes"`
}

// TableName PayrollAwardsText's table name
func (*PayrollAwardsText) TableName() string {
	return TableNamePayrollAwardsText
}
