// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayrollsSuperContribution = "PayrollsSuperContribution"

// PayrollsSuperContribution mapped from table <PayrollsSuperContribution>
type PayrollsSuperContribution struct {
	PayrollsSuperContributionID int32   `gorm:"column:PayrollsSuperContributionId;primaryKey;autoIncrement:true" json:"PayrollsSuperContributionId"`
	PayrollID                   int32   `gorm:"column:PayrollId;not null" json:"PayrollId"`
	RowID                       int32   `gorm:"column:RowId;not null" json:"RowId"`
	MemberNo                    string  `gorm:"column:MemberNo;not null" json:"MemberNo"`
	PayrollSuperFundID          int32   `gorm:"column:PayrollSuperFundId;not null" json:"PayrollSuperFundId"`
	PercentContribution         float64 `gorm:"column:PercentContribution;not null" json:"PercentContribution"`
	Amount                      float64 `gorm:"column:Amount;not null" json:"Amount"`
	Reportable                  bool    `gorm:"column:Reportable;not null" json:"Reportable"`
	DebitAccountID              int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID             int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	DebitDivisionID             int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID            int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	BPAYReferenceCode           int32   `gorm:"column:BPAYReferenceCode" json:"BPAYReferenceCode"`
	PercentEnabled              bool    `gorm:"column:PercentEnabled;not null;default:1" json:"PercentEnabled"`
}

// TableName PayrollsSuperContribution's table name
func (*PayrollsSuperContribution) TableName() string {
	return TableNamePayrollsSuperContribution
}
