// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePhone = "Phones"

// Phone mapped from table <Phones>
type Phone struct {
	PhoneID int32  `gorm:"column:PhoneId;primaryKey;autoIncrement:true" json:"PhoneId"`
	Number  string `gorm:"column:Number;not null" json:"Number"`
	Type    int32  `gorm:"column:Type;not null" json:"Type"`
}

// TableName Phone's table name
func (*Phone) TableName() string {
	return TableNamePhone
}
