// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePickingSlip = "PickingSlips"

// PickingSlip mapped from table <PickingSlips>
type PickingSlip struct {
	PickingSlipID int32     `gorm:"column:PickingSlipId;primaryKey;autoIncrement:true" json:"PickingSlipId"`
	Code          string    `gorm:"column:Code;not null" json:"Code"`
	Description   string    `gorm:"column:Description;not null" json:"Description"`
	Date          time.Time `gorm:"column:Date;not null" json:"Date"`
	EraID         int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion   int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName PickingSlip's table name
func (*PickingSlip) TableName() string {
	return TableNamePickingSlip
}
