// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipAssembly = "PickingSlipAssembly"

// PickingSlipAssembly mapped from table <PickingSlipAssembly>
type PickingSlipAssembly struct {
	PickingSlipAssemblyID int32   `gorm:"column:PickingSlipAssemblyId;primaryKey;autoIncrement:true" json:"PickingSlipAssemblyId"`
	PickingSlipID         int32   `gorm:"column:PickingSlipId;not null" json:"PickingSlipId"`
	AssemblyID            int32   `gorm:"column:AssemblyId;not null" json:"AssemblyId"`
	Quantity              float64 `gorm:"column:Quantity" json:"Quantity"`
}

// TableName PickingSlipAssembly's table name
func (*PickingSlipAssembly) TableName() string {
	return TableNamePickingSlipAssembly
}
