// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipCostCentre = "PickingSlipCostCentres"

// PickingSlipCostCentre mapped from table <PickingSlipCostCentres>
type PickingSlipCostCentre struct {
	PickingSlipCostCentreID int32 `gorm:"column:PickingSlipCostCentreId;primaryKey;autoIncrement:true" json:"PickingSlipCostCentreId"`
	PickingSlipID           int32 `gorm:"column:PickingSlipId;not null" json:"PickingSlipId"`
	CostCentreID            int32 `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	RowID                   int32 `gorm:"column:RowId;not null" json:"RowId"`
}

// TableName PickingSlipCostCentre's table name
func (*PickingSlipCostCentre) TableName() string {
	return TableNamePickingSlipCostCentre
}
