// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipAssemblyCostCentreItem = "PickingSlipAssemblyCostCentreItems"

// PickingSlipAssemblyCostCentreItem mapped from table <PickingSlipAssemblyCostCentreItems>
type PickingSlipAssemblyCostCentreItem struct {
	PickingSlipAssemblyCostCentreItemsID int32   `gorm:"column:PickingSlipAssemblyCostCentreItemsId;primaryKey;autoIncrement:true" json:"PickingSlipAssemblyCostCentreItemsId"`
	CostCentreID                         int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	PricebookID                          int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	RowID                                int32   `gorm:"column:RowId;not null" json:"RowId"`
	SubRowID                             int32   `gorm:"column:SubRowId;not null" json:"SubRowId"`
	Quantity                             float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	Hours                                int32   `gorm:"column:Hours;not null" json:"Hours"`
	Cost                                 float64 `gorm:"column:Cost;not null;default:0.0000" json:"Cost"`
	Retail                               float64 `gorm:"column:Retail;not null;default:0.0000" json:"Retail"`
	Notes                                string  `gorm:"column:Notes;not null" json:"Notes"`
	Brand                                string  `gorm:"column:Brand;not null;default:0" json:"Brand"`
	PickingSlipAssemblyID                int32   `gorm:"column:PickingSlipAssemblyId;not null" json:"PickingSlipAssemblyId"`
}

// TableName PickingSlipAssemblyCostCentreItem's table name
func (*PickingSlipAssemblyCostCentreItem) TableName() string {
	return TableNamePickingSlipAssemblyCostCentreItem
}
