// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipSummary = "PickingSlipSummary"

// PickingSlipSummary mapped from table <PickingSlipSummary>
type PickingSlipSummary struct {
	PickingSlipSummaryID int32   `gorm:"column:PickingSlipSummaryId;primaryKey;autoIncrement:true" json:"PickingSlipSummaryId"`
	PickingSlipID        int32   `gorm:"column:PickingSlipId;not null" json:"PickingSlipId"`
	CostCentreID         int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	PricebookID          int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	RowID                int32   `gorm:"column:RowId;not null" json:"RowId"`
	SubRowID             int32   `gorm:"column:SubRowId;not null" json:"SubRowId"`
	Quantity             float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	Cost                 float64 `gorm:"column:Cost;not null;default:0.0000" json:"Cost"`
	Retail               float64 `gorm:"column:Retail;not null;default:0.0000" json:"Retail"`
	PickedQuantity       float64 `gorm:"column:PickedQuantity;not null;default:0.0000" json:"PickedQuantity"`
}

// TableName PickingSlipSummary's table name
func (*PickingSlipSummary) TableName() string {
	return TableNamePickingSlipSummary
}
