// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipLabourSummary = "PickingSlipLabourSummary"

// PickingSlipLabourSummary mapped from table <PickingSlipLabourSummary>
type PickingSlipLabourSummary struct {
	PickingSlipLabourSummaryID int32   `gorm:"column:PickingSlipLabourSummaryId;primaryKey;autoIncrement:true" json:"PickingSlipLabourSummaryId"`
	PickingSlipID              int32   `gorm:"column:PickingSlipId;not null" json:"PickingSlipId"`
	CostCentreID               int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	LabourRateID               int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	RowID                      int32   `gorm:"column:RowId;not null" json:"RowId"`
	SubRowID                   int32   `gorm:"column:SubRowId;not null" json:"SubRowId"`
	Quantity                   float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	Cost                       float64 `gorm:"column:Cost;not null;default:0.0000" json:"Cost"`
	Retail                     float64 `gorm:"column:Retail;not null;default:0.0000" json:"Retail"`
}

// TableName PickingSlipLabourSummary's table name
func (*PickingSlipLabourSummary) TableName() string {
	return TableNamePickingSlipLabourSummary
}
