// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePickingSlipCostCentreItem = "PickingSlipCostCentreItems"

// PickingSlipCostCentreItem mapped from table <PickingSlipCostCentreItems>
type PickingSlipCostCentreItem struct {
	PickingSlipCostCentreItemID int32   `gorm:"column:PickingSlipCostCentreItemId;primaryKey;autoIncrement:true" json:"PickingSlipCostCentreItemId"`
	PickingSlipID               int32   `gorm:"column:PickingSlipId;not null" json:"PickingSlipId"`
	CostCentreID                int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	PricebookID                 int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID                int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	RowID                       int32   `gorm:"column:RowId;not null" json:"RowId"`
	SubRowID                    int32   `gorm:"column:SubRowId;not null" json:"SubRowId"`
	Quantity                    float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	Hours                       int32   `gorm:"column:Hours;not null" json:"Hours"`
	Cost                        float64 `gorm:"column:Cost;not null;default:0.0000" json:"Cost"`
	Retail                      float64 `gorm:"column:Retail;not null;default:0.0000" json:"Retail"`
	Notes                       string  `gorm:"column:Notes;not null" json:"Notes"`
	Brand                       string  `gorm:"column:Brand;not null;default:0" json:"Brand"`
}

// TableName PickingSlipCostCentreItem's table name
func (*PickingSlipCostCentreItem) TableName() string {
	return TableNamePickingSlipCostCentreItem
}
