// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePosition = "Positions"

// Position mapped from table <Positions>
type Position struct {
	PositionID  int32  `gorm:"column:PositionId;primaryKey;autoIncrement:true" json:"PositionId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Title       string `gorm:"column:Title;not null" json:"Title"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Position's table name
func (*Position) TableName() string {
	return TableNamePosition
}
