// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookClientPrice = "PricebookClientPrices"

// PricebookClientPrice mapped from table <PricebookClientPrices>
type PricebookClientPrice struct {
	PricebookClientPriceID int32   `gorm:"column:PricebookClientPriceId;primaryKey;autoIncrement:true" json:"PricebookClientPriceId"`
	PricebookID            int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	ClientID               int32   `gorm:"column:ClientId;not null" json:"ClientId"`
	BasedOn                string  `gorm:"column:BasedOn;not null" json:"BasedOn"`
	Retail                 float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName PricebookClientPrice's table name
func (*PricebookClientPrice) TableName() string {
	return TableNamePricebookClientPrice
}
