// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookClassificationPrice = "PricebookClassificationPrices"

// PricebookClassificationPrice mapped from table <PricebookClassificationPrices>
type PricebookClassificationPrice struct {
	PricebookClassificationPriceID int32   `gorm:"column:PricebookClassificationPriceId;primaryKey;autoIncrement:true" json:"PricebookClassificationPriceId"`
	PricebookID                    int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	ClientClassificationID         int32   `gorm:"column:ClientClassificationId;not null" json:"ClientClassificationId"`
	BasedOn                        string  `gorm:"column:BasedOn;not null" json:"BasedOn"`
	Retail                         float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName PricebookClassificationPrice's table name
func (*PricebookClassificationPrice) TableName() string {
	return TableNamePricebookClassificationPrice
}
