// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePricebook = "Pricebook"

// Pricebook mapped from table <Pricebook>
type Pricebook struct {
	PricebookID        int32     `gorm:"column:PricebookId;primaryKey;autoIncrement:true" json:"PricebookId"`
	Code               string    `gorm:"column:Code;not null" json:"Code"`
	Description        string    `gorm:"column:Description;not null" json:"Description"`
	Trade              float64   `gorm:"column:Trade;not null" json:"Trade"`
	Cost               float64   `gorm:"column:Cost;not null" json:"Cost"`
	Retail             float64   `gorm:"column:Retail;not null" json:"Retail"`
	UnitID             int32     `gorm:"column:UnitId;not null" json:"UnitId"`
	PricePer           float64   `gorm:"column:PricePer;not null" json:"PricePer"`
	LastUpdated        time.Time `gorm:"column:LastUpdated;not null" json:"LastUpdated"`
	Manufacturer       string    `gorm:"column:Manufacturer" json:"Manufacturer"`
	ObsoleteFlag       bool      `gorm:"column:ObsoleteFlag;not null" json:"ObsoleteFlag"`
	ModelNo            string    `gorm:"column:ModelNo" json:"ModelNo"`
	DebtorAccountID    int32     `gorm:"column:DebtorAccountId" json:"DebtorAccountId"`
	DebtorGSTType      string    `gorm:"column:DebtorGSTType" json:"DebtorGSTType"`
	DebtorDivisionID   int32     `gorm:"column:DebtorDivisionId" json:"DebtorDivisionId"`
	CreditorAccountID  int32     `gorm:"column:CreditorAccountId" json:"CreditorAccountId"`
	CreditorGSTType    string    `gorm:"column:CreditorGSTType" json:"CreditorGSTType"`
	CreditorDivisionID int32     `gorm:"column:CreditorDivisionId" json:"CreditorDivisionId"`
	PriceCategoryID    int32     `gorm:"column:PriceCategoryId" json:"PriceCategoryId"`
	Circa              time.Time `gorm:"column:Circa;not null" json:"Circa"`
	PricebookTextID    int32     `gorm:"column:PricebookTextId" json:"PricebookTextId"`
	EraID              int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	LastPurchaseID     int32     `gorm:"column:LastPurchaseId" json:"LastPurchaseId"`
	ReplacementID      int32     `gorm:"column:ReplacementId" json:"ReplacementId"`
	DataVersion        int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Pricebook's table name
func (*Pricebook) TableName() string {
	return TableNamePricebook
}
