// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookText = "PricebookText"

// PricebookText mapped from table <PricebookText>
type PricebookText struct {
	PricebookTextID int32  `gorm:"column:PricebookTextId;primaryKey;autoIncrement:true" json:"PricebookTextId"`
	Details         string `gorm:"column:Details;not null" json:"Details"`
}

// TableName PricebookText's table name
func (*PricebookText) TableName() string {
	return TableNamePricebookText
}
