// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePriceCategory = "PriceCategory"

// PriceCategory mapped from table <PriceCategory>
type PriceCategory struct {
	PriceCategoryID int32  `gorm:"column:PriceCategoryId;primaryKey;autoIncrement:true" json:"PriceCategoryId"`
	Code            string `gorm:"column:Code;not null" json:"Code"`
	Description     string `gorm:"column:Description;not null" json:"Description"`
	Obsolete        bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	DataVersion     int32  `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName PriceCategory's table name
func (*PriceCategory) TableName() string {
	return TableNamePriceCategory
}
