// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookInstall = "PricebookInstall"

// PricebookInstall mapped from table <PricebookInstall>
type PricebookInstall struct {
	PricebookInstallID int32   `gorm:"column:PricebookInstallId;primaryKey;autoIncrement:true" json:"PricebookInstallId"`
	PricebookID        int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	LabourRateID       int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	Hours              float64 `gorm:"column:Hours;not null" json:"Hours"`
}

// TableName PricebookInstall's table name
func (*PricebookInstall) TableName() string {
	return TableNamePricebookInstall
}
