// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookSupplierProduct = "PricebookSupplierProducts"

// PricebookSupplierProduct mapped from table <PricebookSupplierProducts>
type PricebookSupplierProduct struct {
	PricebookSupplierProductID int32   `gorm:"column:PricebookSupplierProductId;primaryKey;autoIncrement:true" json:"PricebookSupplierProductId"`
	PricebookID                int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	SupplierID                 int32   `gorm:"column:SupplierId;not null" json:"SupplierId"`
	PurchaseID                 int32   `gorm:"column:PurchaseId" json:"PurchaseId"`
	RowID                      int32   `gorm:"column:RowId;not null" json:"RowId"`
	ProductCode                string  `gorm:"column:ProductCode;not null" json:"ProductCode"`
	Retail                     float64 `gorm:"column:Retail;not null" json:"Retail"`
	Cost                       float64 `gorm:"column:Cost;not null" json:"Cost"`
	Barcode                    string  `gorm:"column:Barcode;not null" json:"Barcode"`
}

// TableName PricebookSupplierProduct's table name
func (*PricebookSupplierProduct) TableName() string {
	return TableNamePricebookSupplierProduct
}
