// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePricebookAlternateCode = "PricebookAlternateCodes"

// PricebookAlternateCode mapped from table <PricebookAlternateCodes>
type PricebookAlternateCode struct {
	PricebookAlternativeCodeID int32  `gorm:"column:PricebookAlternativeCodeId;primaryKey;autoIncrement:true" json:"PricebookAlternativeCodeId"`
	PricebookID                int32  `gorm:"column:PricebookId;not null" json:"PricebookId"`
	Code                       string `gorm:"column:Code;not null" json:"Code"`
	DataVersion                int32  `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName PricebookAlternateCode's table name
func (*PricebookAlternateCode) TableName() string {
	return TableNamePricebookAlternateCode
}
