// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProfitLossReportSummary = "ProfitLossReportSummary"

// ProfitLossReportSummary mapped from table <ProfitLossReportSummary>
type ProfitLossReportSummary struct {
	Owner             string    `gorm:"column:Owner" json:"Owner"`
	DivisionID        int32     `gorm:"column:DivisionId" json:"DivisionId"`
	AccountID         int32     `gorm:"column:AccountId;not null" json:"AccountId"`
	MasterAccountID   int32     `gorm:"column:MasterAccountId;not null" json:"MasterAccountId"`
	MasterAccountNo   int32     `gorm:"column:MasterAccountNo;not null" json:"MasterAccountNo"`
	Date              time.Time `gorm:"column:Date;not null" json:"Date"`
	TransactionAmount float64   `gorm:"column:TransactionAmount" json:"TransactionAmount"`
	ID                int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
}

// TableName ProfitLossReportSummary's table name
func (*ProfitLossReportSummary) TableName() string {
	return TableNameProfitLossReportSummary
}
