// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProgressClaim = "ProgressClaims"

// ProgressClaim mapped from table <ProgressClaims>
type ProgressClaim struct {
	ProgressClaimID     int32     `gorm:"column:ProgressClaimId;primaryKey;autoIncrement:true" json:"ProgressClaimId"`
	ProjectID           int32     `gorm:"column:ProjectId;not null" json:"ProjectId"`
	ClientID            int32     `gorm:"column:ClientId;not null" json:"ClientId"`
	ClaimNo             int32     `gorm:"column:ClaimNo;not null" json:"ClaimNo"`
	Date                time.Time `gorm:"column:Date;not null" json:"Date"`
	DueDate             time.Time `gorm:"column:DueDate;not null" json:"DueDate"`
	FromDate            time.Time `gorm:"column:FromDate" json:"FromDate"`
	ToDate              time.Time `gorm:"column:ToDate" json:"ToDate"`
	InDispute           bool      `gorm:"column:InDispute;not null" json:"InDispute"`
	ContactPosition     string    `gorm:"column:ContactPosition" json:"ContactPosition"`
	ClaimInvoiceSetting string    `gorm:"column:ClaimInvoiceSetting" json:"ClaimInvoiceSetting"`
	LayoutID            int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	Claimed             float64   `gorm:"column:Claimed;not null" json:"Claimed"`
	GstType             string    `gorm:"column:GstType;not null" json:"GstType"`
	GstAmount           float64   `gorm:"column:GstAmount;not null" json:"GstAmount"`
	Retention           float64   `gorm:"column:Retention;not null" json:"Retention"`
	InvoiceFlag         string    `gorm:"column:InvoiceFlag" json:"InvoiceFlag"`
	OrderNo             string    `gorm:"column:OrderNo;not null" json:"OrderNo"`
	InvoiceID           int32     `gorm:"column:InvoiceId" json:"InvoiceId"`
	ProgressClaimTextID int32     `gorm:"column:ProgressClaimTextId" json:"ProgressClaimTextId"`
	EraID               int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion         int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	XContactID          int32     `gorm:"column:XContactId" json:"XContactId"`
}

// TableName ProgressClaim's table name
func (*ProgressClaim) TableName() string {
	return TableNameProgressClaim
}
