// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProgressClaimsVariation = "ProgressClaimsVariations"

// ProgressClaimsVariation mapped from table <ProgressClaimsVariations>
type ProgressClaimsVariation struct {
	ProgressClaimsVariationID int32   `gorm:"column:ProgressClaimsVariationId;primaryKey;autoIncrement:true" json:"ProgressClaimsVariationId"`
	ProgressClaimID           int32   `gorm:"column:ProgressClaimId;not null" json:"ProgressClaimId"`
	VariationID               int32   `gorm:"column:VariationId;not null" json:"VariationId"`
	RowID                     int32   `gorm:"column:RowId;not null" json:"RowId"`
	Sum                       float64 `gorm:"column:Sum;not null" json:"Sum"`
	Claimed                   float64 `gorm:"column:Claimed;not null" json:"Claimed"`
}

// TableName ProgressClaimsVariation's table name
func (*ProgressClaimsVariation) TableName() string {
	return TableNameProgressClaimsVariation
}
