// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProgressClaimsWorkCompleted = "ProgressClaimsWorkCompleted"

// ProgressClaimsWorkCompleted mapped from table <ProgressClaimsWorkCompleted>
type ProgressClaimsWorkCompleted struct {
	ProgressClaimsWorkCompletedID int32   `gorm:"column:ProgressClaimsWorkCompletedId;primaryKey;autoIncrement:true" json:"ProgressClaimsWorkCompletedId"`
	ProgressClaimID               int32   `gorm:"column:ProgressClaimId;not null" json:"ProgressClaimId"`
	RowID                         int32   `gorm:"column:RowId;not null" json:"RowId"`
	CostCentreID                  int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	ScopeOfWorkID                 int32   `gorm:"column:ScopeOfWorkId" json:"ScopeOfWorkId"`
	Description                   string  `gorm:"column:Description;not null" json:"Description"`
	Sum                           float64 `gorm:"column:Sum;not null" json:"Sum"`
	Claimed                       float64 `gorm:"column:Claimed;not null" json:"Claimed"`
}

// TableName ProgressClaimsWorkCompleted's table name
func (*ProgressClaimsWorkCompleted) TableName() string {
	return TableNameProgressClaimsWorkCompleted
}
