// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProgressClaimsText = "ProgressClaimsText"

// ProgressClaimsText mapped from table <ProgressClaimsText>
type ProgressClaimsText struct {
	ProgressClaimsTextID int32  `gorm:"column:ProgressClaimsTextId;primaryKey;autoIncrement:true" json:"ProgressClaimsTextId"`
	Clause1              string `gorm:"column:Clause1;not null" json:"Clause1"`
	Clause2              string `gorm:"column:Clause2;not null" json:"Clause2"`
	Clause3              string `gorm:"column:Clause3;not null" json:"Clause3"`
	Detail               string `gorm:"column:Detail;not null" json:"Detail"`
}

// TableName ProgressClaimsText's table name
func (*ProgressClaimsText) TableName() string {
	return TableNameProgressClaimsText
}
