// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProgressClaimItem = "ProgressClaimItems"

// ProgressClaimItem mapped from table <ProgressClaimItems>
type ProgressClaimItem struct {
	ID              int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	ProgressClaimID int32   `gorm:"column:ProgressClaimId;not null" json:"ProgressClaimId"`
	CostCentreID    int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	VariationID     int32   `gorm:"column:VariationId" json:"VariationId"`
	PricebookID     int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID    int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	Code            string  `gorm:"column:Code" json:"Code"`
	Description     string  `gorm:"column:Description" json:"Description"`
	Quantity        float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Amount          float64 `gorm:"column:Amount;not null" json:"Amount"`
}

// TableName ProgressClaimItem's table name
func (*ProgressClaimItem) TableName() string {
	return TableNameProgressClaimItem
}
