// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectCosting = "ProjectCostings"

// ProjectCosting mapped from table <ProjectCostings>
type ProjectCosting struct {
	ID                 int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	CostCentreID       int32   `gorm:"column:CostCentreId;not null" json:"CostCentreId"`
	CostCentreFullCode string  `gorm:"column:CostCentreFullCode;not null" json:"CostCentreFullCode"`
	CostCentreDesc     string  `gorm:"column:CostCentreDesc;not null" json:"CostCentreDesc"`
	JobID              int32   `gorm:"column:JobId;not null" json:"JobId"`
	BudgetHours        float64 `gorm:"column:BudgetHours" json:"BudgetHours"`
	BudgetCost         float64 `gorm:"column:BudgetCost" json:"BudgetCost"`
	CommittedHours     float64 `gorm:"column:CommittedHours" json:"CommittedHours"`
	CommittedCost      float64 `gorm:"column:CommittedCost" json:"CommittedCost"`
	ActualHours        float64 `gorm:"column:ActualHours" json:"ActualHours"`
	ActualCost         float64 `gorm:"column:ActualCost" json:"ActualCost"`
}

// TableName ProjectCosting's table name
func (*ProjectCosting) TableName() string {
	return TableNameProjectCosting
}
