// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectResourceGroup = "ProjectResourceGroup"

// ProjectResourceGroup mapped from table <ProjectResourceGroup>
type ProjectResourceGroup struct {
	ProjectResourceGroupID int32   `gorm:"column:ProjectResourceGroupId;primaryKey;autoIncrement:true" json:"ProjectResourceGroupId"`
	ProjectCostCentreID    int32   `gorm:"column:ProjectCostCentreId;not null" json:"ProjectCostCentreId"`
	RowID                  int32   `gorm:"column:RowId;not null" json:"RowId"`
	Type                   string  `gorm:"column:Type;not null" json:"Type"`
	Description            string  `gorm:"column:Description;not null" json:"Description"`
	Quantity               float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Reference              string  `gorm:"column:Reference;not null" json:"Reference"`
	UnitID                 int32   `gorm:"column:UnitId" json:"UnitId"`
	Brand                  string  `gorm:"column:Brand" json:"Brand"`
	AssemblyID             int32   `gorm:"column:AssemblyId" json:"AssemblyId"`
	SupplierID             int32   `gorm:"column:SupplierId" json:"SupplierId"`
	LabourHours            float64 `gorm:"column:LabourHours;not null" json:"LabourHours"`
	LabourCost             float64 `gorm:"column:LabourCost;not null" json:"LabourCost"`
	MaterialCost           float64 `gorm:"column:MaterialCost;not null" json:"MaterialCost"`
	LabourRetail           float64 `gorm:"column:LabourRetail;not null" json:"LabourRetail"`
	MaterialRetail         float64 `gorm:"column:MaterialRetail;not null" json:"MaterialRetail"`
}

// TableName ProjectResourceGroup's table name
func (*ProjectResourceGroup) TableName() string {
	return TableNameProjectResourceGroup
}
