// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectScopeOfWork = "ProjectScopeOfWorks"

// ProjectScopeOfWork mapped from table <ProjectScopeOfWorks>
type ProjectScopeOfWork struct {
	ProjectScopeOfWorkID int32  `gorm:"column:ProjectScopeOfWorkId;primaryKey;autoIncrement:true" json:"ProjectScopeOfWorkId"`
	Code                 string `gorm:"column:Code;not null" json:"Code"`
	Description          string `gorm:"column:Description;not null" json:"Description"`
	Obsolete             bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	ProjectID            int32  `gorm:"column:ProjectId;not null" json:"ProjectId"`
}

// TableName ProjectScopeOfWork's table name
func (*ProjectScopeOfWork) TableName() string {
	return TableNameProjectScopeOfWork
}
