// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectScopeOfWorkAllocation = "ProjectScopeOfWorkAllocations"

// ProjectScopeOfWorkAllocation mapped from table <ProjectScopeOfWorkAllocations>
type ProjectScopeOfWorkAllocation struct {
	ProjectScopeOfWorkAllocationID int32   `gorm:"column:ProjectScopeOfWorkAllocationId;primaryKey;autoIncrement:true" json:"ProjectScopeOfWorkAllocationId"`
	ProjectCostCentreID            int32   `gorm:"column:ProjectCostCentreId;not null" json:"ProjectCostCentreId"`
	ProjectScopeOfWorkID           int32   `gorm:"column:ProjectScopeOfWorkId;not null" json:"ProjectScopeOfWorkId"`
	Amount                         float64 `gorm:"column:Amount;not null" json:"Amount"`
}

// TableName ProjectScopeOfWorkAllocation's table name
func (*ProjectScopeOfWorkAllocation) TableName() string {
	return TableNameProjectScopeOfWorkAllocation
}
