// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectSubCosting = "ProjectSubCostings"

// ProjectSubCosting mapped from table <ProjectSubCostings>
type ProjectSubCosting struct {
	ID                    int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	ProjectCostingID      int32   `gorm:"column:ProjectCostingId;not null" json:"ProjectCostingId"`
	SubCostCentreID       int32   `gorm:"column:SubCostCentreId;not null" json:"SubCostCentreId"`
	SubCostCentreFullCode string  `gorm:"column:SubCostCentreFullCode;not null" json:"SubCostCentreFullCode"`
	Level                 int32   `gorm:"column:Level;not null" json:"Level"`
	Source                string  `gorm:"column:Source;not null" json:"Source"`
	Code                  string  `gorm:"column:Code;not null" json:"Code"`
	Description           string  `gorm:"column:Description;not null" json:"Description"`
	UOM                   string  `gorm:"column:UOM;not null" json:"UOM"`
	BudgetQuantity        float64 `gorm:"column:BudgetQuantity" json:"BudgetQuantity"`
	BudgetCost            float64 `gorm:"column:BudgetCost" json:"BudgetCost"`
	CommittedQuantity     float64 `gorm:"column:CommittedQuantity" json:"CommittedQuantity"`
	CommittedCost         float64 `gorm:"column:CommittedCost" json:"CommittedCost"`
	ActualQuantity        float64 `gorm:"column:ActualQuantity" json:"ActualQuantity"`
	ActualCost            float64 `gorm:"column:ActualCost" json:"ActualCost"`
}

// TableName ProjectSubCosting's table name
func (*ProjectSubCosting) TableName() string {
	return TableNameProjectSubCosting
}
