// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectSetting = "ProjectSettings"

// ProjectSetting mapped from table <ProjectSettings>
type ProjectSetting struct {
	ProjectSettingID            int32  `gorm:"column:ProjectSettingId;primaryKey;autoIncrement:true" json:"ProjectSettingId"`
	ClaimLayoutID               int32  `gorm:"column:ClaimLayoutId;not null" json:"ClaimLayoutId"`
	VariationLayoutID           int32  `gorm:"column:VariationLayoutId;not null" json:"VariationLayoutId"`
	ClaimFromEmailAccountID     int32  `gorm:"column:ClaimFromEmailAccountId" json:"ClaimFromEmailAccountId"`
	VariationFromEmailAccountID int32  `gorm:"column:VariationFromEmailAccountId" json:"VariationFromEmailAccountId"`
	ClaimMessageTemplateID      int32  `gorm:"column:ClaimMessageTemplateId" json:"ClaimMessageTemplateId"`
	VariationMessageTemplateID  int32  `gorm:"column:VariationMessageTemplateId" json:"VariationMessageTemplateId"`
	ClaimInvoiceFlag            string `gorm:"column:ClaimInvoiceFlag;not null" json:"ClaimInvoiceFlag"`
	InvoicePrefix               string `gorm:"column:InvoicePrefix;not null" json:"InvoicePrefix"`
}

// TableName ProjectSetting's table name
func (*ProjectSetting) TableName() string {
	return TableNameProjectSetting
}
