// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProject = "Projects"

// Project mapped from table <Projects>
type Project struct {
	ProjectID                 int32     `gorm:"column:ProjectId;primaryKey" json:"ProjectId"`
	LayoutID                  int32     `gorm:"column:LayoutId" json:"LayoutId"`
	ContractSum               float64   `gorm:"column:ContractSum;not null;default:0.00" json:"ContractSum"`
	ApprovedVariations        float64   `gorm:"column:ApprovedVariations;not null;default:0.00" json:"ApprovedVariations"`
	EstimatedCost             float64   `gorm:"column:EstimatedCost;not null;default:0.00" json:"EstimatedCost"`
	VariationsCost            float64   `gorm:"column:VariationsCost;not null;default:0.00" json:"VariationsCost"`
	TotalPayments             float64   `gorm:"column:TotalPayments;not null;default:0.00" json:"TotalPayments"`
	TotalReceipts             float64   `gorm:"column:TotalReceipts;not null;default:0.00" json:"TotalReceipts"`
	ClaimedToDate             float64   `gorm:"column:ClaimedToDate;not null;default:0.00" json:"ClaimedToDate"`
	RetentionHeld             float64   `gorm:"column:RetentionHeld;not null;default:0.00" json:"RetentionHeld"`
	RetentionRate             float64   `gorm:"column:RetentionRate;not null;default:0.0000" json:"RetentionRate"`
	RetentionMaximum          float64   `gorm:"column:RetentionMaximum;not null;default:0.0000" json:"RetentionMaximum"`
	RetentionPCRate           float64   `gorm:"column:RetentionPCRate;not null;default:0.0000" json:"RetentionPCRate"`
	RetentionCompleteRate     float64   `gorm:"column:RetentionCompleteRate;not null;default:0.0000" json:"RetentionCompleteRate"`
	PlannedStart              time.Time `gorm:"column:PlannedStart" json:"PlannedStart"`
	PlannedFinish             time.Time `gorm:"column:PlannedFinish" json:"PlannedFinish"`
	ActualStart               time.Time `gorm:"column:ActualStart" json:"ActualStart"`
	BankGuarantee             float64   `gorm:"column:BankGuarantee;not null;default:0.00" json:"BankGuarantee"`
	MaintenancePeriod         int32     `gorm:"column:MaintenancePeriod" json:"MaintenancePeriod"`
	PracticalCompletion       time.Time `gorm:"column:PracticalCompletion" json:"PracticalCompletion"`
	EstimateID                int32     `gorm:"column:EstimateId" json:"EstimateId"`
	CostCentreDepth           int32     `gorm:"column:CostCentreDepth;not null;default:1" json:"CostCentreDepth"`
	CostCentresFromProjectID  int32     `gorm:"column:CostCentresFromProjectId" json:"CostCentresFromProjectId"`
	CostCentresFromTemplateID int32     `gorm:"column:CostCentresFromTemplateId" json:"CostCentresFromTemplateId"`
	InsuranceBond             float64   `gorm:"column:InsuranceBond;not null;default:0.00" json:"InsuranceBond"`
	EraID                     int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion               int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	PlannedDuration           int32     `gorm:"column:PlannedDuration" json:"PlannedDuration"`
	PlannedMaintenancePeriod  int32     `gorm:"column:PlannedMaintenancePeriod" json:"PlannedMaintenancePeriod"`
	PlannedFinalisation       time.Time `gorm:"column:PlannedFinalisation" json:"PlannedFinalisation"`
	ForecastDuration          int32     `gorm:"column:ForecastDuration" json:"ForecastDuration"`
	ForecastMaintenancePeriod int32     `gorm:"column:ForecastMaintenancePeriod" json:"ForecastMaintenancePeriod"`
	ForecastStart             time.Time `gorm:"column:ForecastStart" json:"ForecastStart"`
	ForecastFinish            time.Time `gorm:"column:ForecastFinish" json:"ForecastFinish"`
	ForecastFinalisation      time.Time `gorm:"column:ForecastFinalisation" json:"ForecastFinalisation"`
	ActualDuration            int32     `gorm:"column:ActualDuration" json:"ActualDuration"`
	Status                    string    `gorm:"column:Status" json:"Status"`
	StatusDate                time.Time `gorm:"column:StatusDate" json:"StatusDate"`
	UseScopeOfWork            bool      `gorm:"column:UseScopeOfWork;not null" json:"UseScopeOfWork"`
	NextVariationNumber       int32     `gorm:"column:NextVariationNumber;not null;default:1" json:"NextVariationNumber"`
	ProgressClaimMethod       string    `gorm:"column:ProgressClaimMethod;not null" json:"ProgressClaimMethod"`
	UseSubcontractors         bool      `gorm:"column:UseSubcontractors;not null" json:"UseSubcontractors"`
	Attributes                string    `gorm:"column:Attributes" json:"Attributes"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
