// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProjectResource = "ProjectResource"

// ProjectResource mapped from table <ProjectResource>
type ProjectResource struct {
	ProjectResourceID      int32   `gorm:"column:ProjectResourceId;primaryKey;autoIncrement:true" json:"ProjectResourceId"`
	ProjectResourceGroupID int32   `gorm:"column:ProjectResourceGroupId;not null" json:"ProjectResourceGroupId"`
	Type                   string  `gorm:"column:Type;not null" json:"Type"`
	PricebookID            int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID           int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	Quantity               float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                   float64 `gorm:"column:Cost;not null" json:"Cost"`
	Retail                 float64 `gorm:"column:Retail;not null" json:"Retail"`
}

// TableName ProjectResource's table name
func (*ProjectResource) TableName() string {
	return TableNameProjectResource
}
