// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePurchasesText = "PurchasesText"

// PurchasesText mapped from table <PurchasesText>
type PurchasesText struct {
	PurchasesTextID int32  `gorm:"column:PurchasesTextId;primaryKey" json:"PurchasesTextId"`
	Details         string `gorm:"column:Details;not null" json:"Details"`
	GSTAccruedItems string `gorm:"column:GSTAccruedItems;not null" json:"GSTAccruedItems"`
	GSTPaidItems    string `gorm:"column:GSTPaidItems;not null" json:"GSTPaidItems"`
	JobsList        string `gorm:"column:JobsList;not null" json:"JobsList"`
}

// TableName PurchasesText's table name
func (*PurchasesText) TableName() string {
	return TableNamePurchasesText
}
