// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePurchaseSetting = "PurchaseSettings"

// PurchaseSetting mapped from table <PurchaseSettings>
type PurchaseSetting struct {
	PurchaseSettingID       int32 `gorm:"column:PurchaseSettingId;primaryKey" json:"PurchaseSettingId"`
	PostCostsToFinishedJobs bool  `gorm:"column:PostCostsToFinishedJobs;not null" json:"PostCostsToFinishedJobs"`
	UpdatePricebookCost     bool  `gorm:"column:UpdatePricebookCost;not null" json:"UpdatePricebookCost"`
	ItemsMustMatchOrder     bool  `gorm:"column:ItemsMustMatchOrder;not null" json:"ItemsMustMatchOrder"`
}

// TableName PurchaseSetting's table name
func (*PurchaseSetting) TableName() string {
	return TableNamePurchaseSetting
}
