// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePurchase = "Purchases"

// Purchase mapped from table <Purchases>
type Purchase struct {
	PurchaseID        int32     `gorm:"column:PurchaseId;primaryKey;autoIncrement:true" json:"PurchaseId"`
	SupplierID        int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	InvoiceNo         string    `gorm:"column:InvoiceNo;not null" json:"InvoiceNo"`
	Date              time.Time `gorm:"column:Date;not null" json:"Date"`
	DueDate           time.Time `gorm:"column:DueDate;not null" json:"DueDate"`
	Amount            float64   `gorm:"column:Amount;not null" json:"Amount"`
	OrderID           int32     `gorm:"column:OrderId" json:"OrderId"`
	DeliveryID        int32     `gorm:"column:DeliveryId" json:"DeliveryId"`
	InDispute         bool      `gorm:"column:InDispute;not null" json:"InDispute"`
	GST               float64   `gorm:"column:GST;not null" json:"GST"`
	InputTaxInclusive bool      `gorm:"column:InputTaxInclusive;not null" json:"InputTaxInclusive"`
	TaxInvoice        bool      `gorm:"column:TaxInvoice;not null" json:"TaxInvoice"`
	Owing             float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	EraID             int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	ClosedDate        time.Time `gorm:"column:ClosedDate" json:"ClosedDate"`
	TPARFlag          bool      `gorm:"column:TPARFlag;not null" json:"TPARFlag"`
	DataVersion       int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	IsFromEInvoice    bool      `gorm:"column:IsFromEInvoice;not null" json:"IsFromEInvoice"`
	BatchPayment      float64   `gorm:"column:BatchPayment;not null" json:"BatchPayment"`
	BatchPaymentID    int32     `gorm:"column:BatchPaymentId;not null" json:"BatchPaymentId"`
	Attributes        string    `gorm:"column:Attributes" json:"Attributes"`
}

// TableName Purchase's table name
func (*Purchase) TableName() string {
	return TableNamePurchase
}
