// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePurchaseItem = "PurchaseItems"

// PurchaseItem mapped from table <PurchaseItems>
type PurchaseItem struct {
	PurchaseItemID    int32   `gorm:"column:PurchaseItemId;primaryKey;autoIncrement:true" json:"PurchaseItemId"`
	PurchaseID        int32   `gorm:"column:PurchaseId;not null" json:"PurchaseId"`
	RowID             int32   `gorm:"column:RowId;not null" json:"RowId"`
	Description       string  `gorm:"column:Description;not null" json:"Description"`
	UnitCost          float64 `gorm:"column:UnitCost;not null" json:"UnitCost"`
	Amount            float64 `gorm:"column:Amount;not null" json:"Amount"`
	GSTType           string  `gorm:"column:GSTType;not null" json:"GSTType"`
	GSTAmount         float64 `gorm:"column:GSTAmount;not null" json:"GSTAmount"`
	CreditAccountID   int32   `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	DebitAccountID    int32   `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	PricebookID       int32   `gorm:"column:PricebookId" json:"PricebookId"`
	Reference         string  `gorm:"column:Reference;not null" json:"Reference"`
	LabourRateID      int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	CreditDivisionID  int32   `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	DebitDivisionID   int32   `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	Quantity          float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	GstDebitAccountID int32   `gorm:"column:GstDebitAccountId" json:"GstDebitAccountId"`
	WarrantyID        int32   `gorm:"column:WarrantyId" json:"WarrantyId"`
	Tags              string  `gorm:"column:Tags" json:"Tags"`
}

// TableName PurchaseItem's table name
func (*PurchaseItem) TableName() string {
	return TableNamePurchaseItem
}
