// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePurchaseItemsQuantity = "PurchaseItemsQuantity"

// PurchaseItemsQuantity mapped from table <PurchaseItemsQuantity>
type PurchaseItemsQuantity struct {
	PurchaseItemsQuantityID int32   `gorm:"column:PurchaseItemsQuantityId;primaryKey;autoIncrement:true" json:"PurchaseItemsQuantityId"`
	PurchaseItemID          int32   `gorm:"column:PurchaseItemId;not null" json:"PurchaseItemId"`
	RowID                   int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity                float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	JobID                   int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID            int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	StockLocationID         int32   `gorm:"column:StockLocationId" json:"StockLocationId"`
	OrderItemsQuantityID    int32   `gorm:"column:OrderItemsQuantityId" json:"OrderItemsQuantityId"`
}

// TableName PurchaseItemsQuantity's table name
func (*PurchaseItemsQuantity) TableName() string {
	return TableNamePurchaseItemsQuantity
}
