// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameQuotesText = "QuotesText"

// QuotesText mapped from table <QuotesText>
type QuotesText struct {
	QuoteID int32  `gorm:"column:QuoteId;primaryKey" json:"QuoteId"`
	Details string `gorm:"column:Details;not null" json:"Details"`
	Clause1 string `gorm:"column:Clause1;not null" json:"Clause1"`
	Clause2 string `gorm:"column:Clause2;not null" json:"Clause2"`
	Clause3 string `gorm:"column:Clause3;not null" json:"Clause3"`
}

// TableName QuotesText's table name
func (*QuotesText) TableName() string {
	return TableNameQuotesText
}
