// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameQuote = "Quotes"

// Quote mapped from table <Quotes>
type Quote struct {
	QuoteID       int32     `gorm:"column:QuoteId;primaryKey;autoIncrement:true" json:"QuoteId"`
	QuoteNo       string    `gorm:"column:QuoteNo;not null" json:"QuoteNo"`
	DateReceived  time.Time `gorm:"column:DateReceived;not null" json:"DateReceived"`
	Prospect      string    `gorm:"column:Prospect;not null" json:"Prospect"`
	ClientID      int32     `gorm:"column:ClientId" json:"ClientId"`
	PhoneID       int32     `gorm:"column:PhoneId" json:"PhoneId"`
	FaxID         int32     `gorm:"column:FaxId" json:"FaxId"`
	Email         string    `gorm:"column:Email;not null" json:"Email"`
	PricingBasis  string    `gorm:"column:PricingBasis;not null" json:"PricingBasis"`
	LayoutID      int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	Reference     string    `gorm:"column:Reference;not null" json:"Reference"`
	QuoteStatusID int32     `gorm:"column:QuoteStatusId" json:"QuoteStatusId"`
	JobTypeID     int32     `gorm:"column:JobTypeId" json:"JobTypeId"`
	EstimatorID   int32     `gorm:"column:EstimatorId" json:"EstimatorId"`
	DateRequired  time.Time `gorm:"column:DateRequired" json:"DateRequired"`
	DateCompleted time.Time `gorm:"column:DateCompleted" json:"DateCompleted"`
	EraID         int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion   int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	AddressID     int32     `gorm:"column:AddressId" json:"AddressId"`
	Contact       string    `gorm:"column:Contact" json:"Contact"`
	Tags          string    `gorm:"column:Tags" json:"Tags"`
	Attributes    string    `gorm:"column:Attributes" json:"Attributes"`
	XContactID    int32     `gorm:"column:XContactId" json:"XContactId"`
}

// TableName Quote's table name
func (*Quote) TableName() string {
	return TableNameQuote
}
