// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameQuoteSetting = "QuoteSettings"

// QuoteSetting mapped from table <QuoteSettings>
type QuoteSetting struct {
	QuoteSettingID     int32  `gorm:"column:QuoteSettingId;primaryKey" json:"QuoteSettingId"`
	LayoutID           int32  `gorm:"column:LayoutId" json:"LayoutId"`
	FromEmailAccountID int32  `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	MessageTemplateID  int32  `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	PricingBasis       string `gorm:"column:PricingBasis;not null" json:"PricingBasis"`
}

// TableName QuoteSetting's table name
func (*QuoteSetting) TableName() string {
	return TableNameQuoteSetting
}
