// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameQuoteClause = "QuoteClauses"

// QuoteClause mapped from table <QuoteClauses>
type QuoteClause struct {
	QuoteClauseID int32  `gorm:"column:QuoteClauseId;primaryKey;autoIncrement:true" json:"QuoteClauseId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
	Obsolete      bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName QuoteClause's table name
func (*QuoteClause) TableName() string {
	return TableNameQuoteClause
}
