// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameQuoteStatus = "QuoteStatus"

// QuoteStatus mapped from table <QuoteStatus>
type QuoteStatus struct {
	QuoteStatusID       int32  `gorm:"column:QuoteStatusId;primaryKey;autoIncrement:true" json:"QuoteStatusId"`
	Code                string `gorm:"column:Code;not null" json:"Code"`
	Description         string `gorm:"column:Description;not null" json:"Description"`
	Obsolete            bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	ShowAsFilterMenuTab bool   `gorm:"column:ShowAsFilterMenuTab;not null" json:"ShowAsFilterMenuTab"`
}

// TableName QuoteStatus's table name
func (*QuoteStatus) TableName() string {
	return TableNameQuoteStatus
}
