// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameQuoteItem = "QuoteItems"

// QuoteItem mapped from table <QuoteItems>
type QuoteItem struct {
	QuoteItemID   int32   `gorm:"column:QuoteItemId;primaryKey;autoIncrement:true" json:"QuoteItemId"`
	QuoteID       int32   `gorm:"column:QuoteId;not null" json:"QuoteId"`
	RowID         int32   `gorm:"column:RowId;not null" json:"RowId"`
	Description   string  `gorm:"column:Description;not null" json:"Description"`
	Quantity      float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost          float64 `gorm:"column:Cost;not null" json:"Cost"`
	MaterialsCost float64 `gorm:"column:MaterialsCost;not null" json:"MaterialsCost"`
	LabourCost    float64 `gorm:"column:LabourCost;not null" json:"LabourCost"`
	Hours         float64 `gorm:"column:Hours;not null" json:"Hours"`
	Retail        float64 `gorm:"column:Retail;not null" json:"Retail"`
	Reference     string  `gorm:"column:Reference;not null" json:"Reference"`
	UnitID        int32   `gorm:"column:UnitId" json:"UnitId"`
	PricebookID   int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID  int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	AssemblyID    int32   `gorm:"column:AssemblyId" json:"AssemblyId"`
}

// TableName QuoteItem's table name
func (*QuoteItem) TableName() string {
	return TableNameQuoteItem
}
