// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRecurring = "Recurrings"

// Recurring mapped from table <Recurrings>
type Recurring struct {
	RecurringID   int32     `gorm:"column:RecurringId;primaryKey;autoIncrement:true" json:"RecurringId"`
	ReferenceNo   int32     `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	Type          string    `gorm:"column:Type;not null" json:"Type"`
	Description   string    `gorm:"column:Description;not null" json:"Description"`
	TransactionID int32     `gorm:"column:TransactionId" json:"TransactionId"`
	InvoiceID     int32     `gorm:"column:InvoiceId" json:"InvoiceId"`
	JobID         int32     `gorm:"column:JobId" json:"JobId"`
	StartDate     time.Time `gorm:"column:StartDate;not null" json:"StartDate"`
	DueDate       time.Time `gorm:"column:DueDate;not null" json:"DueDate"`
	Frequency     string    `gorm:"column:Frequency;not null" json:"Frequency"`
	Instalments   int32     `gorm:"column:Instalments;not null" json:"Instalments"`
	EndDate       time.Time `gorm:"column:EndDate" json:"EndDate"`
	Status        string    `gorm:"column:Status" json:"Status"`
	Posting       string    `gorm:"column:Posting" json:"Posting"`
	EraID         int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa         time.Time `gorm:"column:Circa;not null" json:"Circa"`
	DataVersion   int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	Amount        float64   `gorm:"column:Amount;not null;default:0.0000" json:"Amount"`
	Count         int32     `gorm:"column:Count;not null" json:"Count"`
	FinalAmount   float64   `gorm:"column:FinalAmount" json:"FinalAmount"`
}

// TableName Recurring's table name
func (*Recurring) TableName() string {
	return TableNameRecurring
}
