// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRegionWorkHour = "RegionWorkHours"

// RegionWorkHour mapped from table <RegionWorkHours>
type RegionWorkHour struct {
	RegionWorkHourID int32  `gorm:"column:RegionWorkHourId;primaryKey;autoIncrement:true" json:"RegionWorkHourId"`
	CalendarRegionID int32  `gorm:"column:CalendarRegionId;not null" json:"CalendarRegionId"`
	DayOfWeek        int32  `gorm:"column:DayOfWeek;not null" json:"DayOfWeek"`
	Start            string `gorm:"column:Start;not null" json:"Start"`
	Finish           string `gorm:"column:Finish;not null" json:"Finish"`
	Break            int32  `gorm:"column:Break" json:"Break"`
}

// TableName RegionWorkHour's table name
func (*RegionWorkHour) TableName() string {
	return TableNameRegionWorkHour
}
