// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRegionNonWorkingDay = "RegionNonWorkingDays"

// RegionNonWorkingDay mapped from table <RegionNonWorkingDays>
type RegionNonWorkingDay struct {
	RegionNonWorkingDayID   int32     `gorm:"column:RegionNonWorkingDayId;primaryKey;autoIncrement:true" json:"RegionNonWorkingDayId"`
	CalendarRegionID        int32     `gorm:"column:CalendarRegionId;not null" json:"CalendarRegionId"`
	Date                    time.Time `gorm:"column:Date;not null" json:"Date"`
	Description             string    `gorm:"column:Description;not null" json:"Description"`
	PayrollTimeTypeCategory string    `gorm:"column:PayrollTimeTypeCategory;not null" json:"PayrollTimeTypeCategory"`
	Source                  string    `gorm:"column:Source;not null" json:"Source"`
}

// TableName RegionNonWorkingDay's table name
func (*RegionNonWorkingDay) TableName() string {
	return TableNameRegionNonWorkingDay
}
