// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRole = "Roles"

// Role mapped from table <Roles>
type Role struct {
	ID          int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Name        string `gorm:"column:Name;not null" json:"Name"`
	Description string `gorm:"column:Description;not null" json:"Description"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
