// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRolePermission = "RolePermissions"

// RolePermission mapped from table <RolePermissions>
type RolePermission struct {
	ID          int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Module      string `gorm:"column:Module;not null" json:"Module"`
	AccessLevel int32  `gorm:"column:AccessLevel;not null;default:1" json:"AccessLevel"`
	RoleID      int32  `gorm:"column:RoleId;not null" json:"RoleId"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
