// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSbrEventMessage = "SbrEventMessages"

// SbrEventMessage mapped from table <SbrEventMessages>
type SbrEventMessage struct {
	SbrEventMessageID   int32  `gorm:"column:SbrEventMessageId;primaryKey;autoIncrement:true" json:"SbrEventMessageId"`
	SbrEventID          int32  `gorm:"column:SbrEventId;not null" json:"SbrEventId"`
	MaximumSeverityCode string `gorm:"column:MaximumSeverityCode;not null" json:"MaximumSeverityCode"`
}

// TableName SbrEventMessage's table name
func (*SbrEventMessage) TableName() string {
	return TableNameSbrEventMessage
}
