// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSbrEventPayEventEmployee = "SbrEventPayEventEmployee"

// SbrEventPayEventEmployee mapped from table <SbrEventPayEventEmployee>
type SbrEventPayEventEmployee struct {
	SbrEventID         int32 `gorm:"column:SbrEventId;primaryKey" json:"SbrEventId"`
	PayEventEmployeeID int32 `gorm:"column:PayEventEmployeeId;primaryKey" json:"PayEventEmployeeId"`
}

// TableName SbrEventPayEventEmployee's table name
func (*SbrEventPayEventEmployee) TableName() string {
	return TableNameSbrEventPayEventEmployee
}
