// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSbrEvent = "SbrEvents"

// SbrEvent mapped from table <SbrEvents>
type SbrEvent struct {
	SbrEventID           int32     `gorm:"column:SbrEventId;primaryKey;autoIncrement:true" json:"SbrEventId"`
	PushMessageID        string    `gorm:"column:PushMessageId;not null" json:"PushMessageId"`
	PushReciptMessageID  string    `gorm:"column:PushReciptMessageId" json:"PushReciptMessageId"`
	PullMessageID        string    `gorm:"column:PullMessageId" json:"PullMessageId"`
	PullReceiptMessageID string    `gorm:"column:PullReceiptMessageId" json:"PullReceiptMessageId"`
	MessageAccepted      bool      `gorm:"column:MessageAccepted" json:"MessageAccepted"`
	PushedAt             time.Time `gorm:"column:PushedAt;not null" json:"PushedAt"`
	PulledAt             time.Time `gorm:"column:PulledAt" json:"PulledAt"`
	PayEventID           int32     `gorm:"column:PayEventId" json:"PayEventId"`
}

// TableName SbrEvent's table name
func (*SbrEvent) TableName() string {
	return TableNameSbrEvent
}
