// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSbrEventItemLocation = "SbrEventItemLocations"

// SbrEventItemLocation mapped from table <SbrEventItemLocations>
type SbrEventItemLocation struct {
	SbrEventItemLocationID int32  `gorm:"column:SbrEventItemLocationId;primaryKey;autoIncrement:true" json:"SbrEventItemLocationId"`
	SbrEventItemID         int32  `gorm:"column:SbrEventItemId;not null" json:"SbrEventItemId"`
	Identifier             string `gorm:"column:Identifier;not null" json:"Identifier"`
	Path                   string `gorm:"column:Path" json:"Path"`
}

// TableName SbrEventItemLocation's table name
func (*SbrEventItemLocation) TableName() string {
	return TableNameSbrEventItemLocation
}
