// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSbrEventItemParameter = "SbrEventItemParameters"

// SbrEventItemParameter mapped from table <SbrEventItemParameters>
type SbrEventItemParameter struct {
	SbrEventItemParameterID int32  `gorm:"column:SbrEventItemParameterId;primaryKey;autoIncrement:true" json:"SbrEventItemParameterId"`
	SbrEventItemID          int32  `gorm:"column:SbrEventItemId;not null" json:"SbrEventItemId"`
	Key                     string `gorm:"column:Key;not null" json:"Key"`
	Value                   string `gorm:"column:Value;not null" json:"Value"`
}

// TableName SbrEventItemParameter's table name
func (*SbrEventItemParameter) TableName() string {
	return TableNameSbrEventItemParameter
}
