// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSbrEventItem = "SbrEventItems"

// SbrEventItem mapped from table <SbrEventItems>
type SbrEventItem struct {
	SbrEventItemID      int32  `gorm:"column:SbrEventItemId;primaryKey;autoIncrement:true" json:"SbrEventItemId"`
	SbrEventMessageID   int32  `gorm:"column:SbrEventMessageId;not null" json:"SbrEventMessageId"`
	ErrorCode           string `gorm:"column:ErrorCode;not null" json:"ErrorCode"`
	SeverityCode        string `gorm:"column:SeverityCode;not null" json:"SeverityCode"`
	ShortDescription    string `gorm:"column:ShortDescription;not null" json:"ShortDescription"`
	DetailedDescription string `gorm:"column:DetailedDescription" json:"DetailedDescription"`
}

// TableName SbrEventItem's table name
func (*SbrEventItem) TableName() string {
	return TableNameSbrEventItem
}
