// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSecuritySetting = "SecuritySettings"

// SecuritySetting mapped from table <SecuritySettings>
type SecuritySetting struct {
	ID                                   int32 `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	PasswordMinLength                    int32 `gorm:"column:PasswordMinLength;not null" json:"PasswordMinLength"`
	PasswordAtLeastOneUppercaseLetter    bool  `gorm:"column:PasswordAtLeastOneUppercaseLetter;not null" json:"PasswordAtLeastOneUppercaseLetter"`
	PasswordAtLeastOneLowercaseLetter    bool  `gorm:"column:PasswordAtLeastOneLowercaseLetter;not null" json:"PasswordAtLeastOneLowercaseLetter"`
	PasswordAtLeastOneNumber             bool  `gorm:"column:PasswordAtLeastOneNumber;not null" json:"PasswordAtLeastOneNumber"`
	PasswordAtLeastOneNonAlphanumeric    bool  `gorm:"column:PasswordAtLeastOneNonAlphanumeric;not null" json:"PasswordAtLeastOneNonAlphanumeric"`
	PasswordExpirationEnabled            bool  `gorm:"column:PasswordExpirationEnabled;not null" json:"PasswordExpirationEnabled"`
	PasswordExpirationPeriod             int32 `gorm:"column:PasswordExpirationPeriod" json:"PasswordExpirationPeriod"`
	PasswordResetTokenExpirationPeriod   int32 `gorm:"column:PasswordResetTokenExpirationPeriod;not null" json:"PasswordResetTokenExpirationPeriod"`
	FailedAccessLockoutEnabled           bool  `gorm:"column:FailedAccessLockoutEnabled;not null" json:"FailedAccessLockoutEnabled"`
	FailedAccessLockoutCount             int32 `gorm:"column:FailedAccessLockoutCount" json:"FailedAccessLockoutCount"`
	FailedAccessLockoutPeriod            int32 `gorm:"column:FailedAccessLockoutPeriod" json:"FailedAccessLockoutPeriod"`
	AllowUsersManageEmailAccountPassword bool  `gorm:"column:AllowUsersManageEmailAccountPassword;not null" json:"AllowUsersManageEmailAccountPassword"`
}

// TableName SecuritySetting's table name
func (*SecuritySetting) TableName() string {
	return TableNameSecuritySetting
}
