// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSerialNoTracking = "SerialNoTracking"

// SerialNoTracking mapped from table <SerialNoTracking>
type SerialNoTracking struct {
	SerialNoTrackingID      int32  `gorm:"column:SerialNoTrackingId;primaryKey;autoIncrement:true" json:"SerialNoTrackingId"`
	SerialNo                string `gorm:"column:SerialNo;not null" json:"SerialNo"`
	PricebookID             int32  `gorm:"column:PricebookId" json:"PricebookId"`
	PurchaseItemsQuantityID int32  `gorm:"column:PurchaseItemsQuantityId" json:"PurchaseItemsQuantityId"`
	StockMovementItemID     int32  `gorm:"column:StockMovementItemId" json:"StockMovementItemId"`
	OrderItemsQuantityID    int32  `gorm:"column:OrderItemsQuantityId" json:"OrderItemsQuantityId"`
	DeliveryItemsQuantityID int32  `gorm:"column:DeliveryItemsQuantityId" json:"DeliveryItemsQuantityId"`
}

// TableName SerialNoTracking's table name
func (*SerialNoTracking) TableName() string {
	return TableNameSerialNoTracking
}
