// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameServiceEquipment = "ServiceEquipment"

// ServiceEquipment mapped from table <ServiceEquipment>
type ServiceEquipment struct {
	ServiceEquipmentID int32  `gorm:"column:ServiceEquipmentId;primaryKey;autoIncrement:true" json:"ServiceEquipmentId"`
	Code               string `gorm:"column:Code;not null" json:"Code"`
	Description        string `gorm:"column:Description;not null" json:"Description"`
}

// TableName ServiceEquipment's table name
func (*ServiceEquipment) TableName() string {
	return TableNameServiceEquipment
}
