// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameServiceArea = "ServiceAreas"

// ServiceArea mapped from table <ServiceAreas>
type ServiceArea struct {
	ServiceAreaID int32  `gorm:"column:ServiceAreaId;primaryKey;autoIncrement:true" json:"ServiceAreaId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
}

// TableName ServiceArea's table name
func (*ServiceArea) TableName() string {
	return TableNameServiceArea
}
