// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameServiceType = "ServiceTypes"

// ServiceType mapped from table <ServiceTypes>
type ServiceType struct {
	ServiceTypeID int32  `gorm:"column:ServiceTypeId;primaryKey;autoIncrement:true" json:"ServiceTypeId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
}

// TableName ServiceType's table name
func (*ServiceType) TableName() string {
	return TableNameServiceType
}
