// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSignature = "Signatures"

// Signature mapped from table <Signatures>
type Signature struct {
	SignatureID int32     `gorm:"column:SignatureId;primaryKey;autoIncrement:true" json:"SignatureId"`
	Signature   string    `gorm:"column:Signature;not null" json:"Signature"`
	Default     bool      `gorm:"column:Default;not null" json:"Default"`
	Created     time.Time `gorm:"column:Created;not null" json:"Created"`
	Name        string    `gorm:"column:Name" json:"Name"`
}

// TableName Signature's table name
func (*Signature) TableName() string {
	return TableNameSignature
}
