// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSkill = "Skills"

// Skill mapped from table <Skills>
type Skill struct {
	SkillID     int32  `gorm:"column:SkillId;primaryKey;autoIncrement:true" json:"SkillId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
