// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStationeryLayout = "StationeryLayouts"

// StationeryLayout mapped from table <StationeryLayouts>
type StationeryLayout struct {
	StationeryLayoutID int32  `gorm:"column:StationeryLayoutId;primaryKey;autoIncrement:true" json:"StationeryLayoutId"`
	Code               string `gorm:"column:Code;not null" json:"Code"`
	Type               string `gorm:"column:Type;not null" json:"Type"`
	Description        string `gorm:"column:Description;not null" json:"Description"`
	MessageTemplateID  int32  `gorm:"column:MessageTemplateId" json:"MessageTemplateId"`
	TestKey            string `gorm:"column:TestKey" json:"TestKey"`
	Master             bool   `gorm:"column:Master;not null" json:"Master"`
	Obsolete           bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName StationeryLayout's table name
func (*StationeryLayout) TableName() string {
	return TableNameStationeryLayout
}
