// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStickyNote = "StickyNotes"

// StickyNote mapped from table <StickyNotes>
type StickyNote struct {
	StickyNoteID int32  `gorm:"column:StickyNoteId;primaryKey" json:"StickyNoteId"`
	Note         string `gorm:"column:Note;not null" json:"Note"`
}

// TableName StickyNote's table name
func (*StickyNote) TableName() string {
	return TableNameStickyNote
}
