// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockItemLocation = "StockItemLocations"

// StockItemLocation mapped from table <StockItemLocations>
type StockItemLocation struct {
	StockItemLocationsID int32   `gorm:"column:StockItemLocationsId;primaryKey;autoIncrement:true" json:"StockItemLocationsId"`
	StockID              int32   `gorm:"column:StockId;not null" json:"StockId"`
	StockLocationID      int32   `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	RowID                int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity             float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	ReorderQty           float64 `gorm:"column:ReorderQty;not null" json:"ReorderQty"`
	ReorderLevel         float64 `gorm:"column:ReorderLevel;not null" json:"ReorderLevel"`
}

// TableName StockItemLocation's table name
func (*StockItemLocation) TableName() string {
	return TableNameStockItemLocation
}
