// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockSetting = "StockSetting"

// StockSetting mapped from table <StockSetting>
type StockSetting struct {
	StockSettingID                      int32 `gorm:"column:StockSettingId;primaryKey;autoIncrement:true" json:"StockSettingId"`
	AllowStockMovementNonStock          bool  `gorm:"column:AllowStockMovementNonStock;not null" json:"AllowStockMovementNonStock"`
	AllowStockMovementExceedStockOnHand bool  `gorm:"column:AllowStockMovementExceedStockOnHand;not null" json:"AllowStockMovementExceedStockOnHand"`
	AllowInvoiceExceedStockOnHand       bool  `gorm:"column:AllowInvoiceExceedStockOnHand;not null" json:"AllowInvoiceExceedStockOnHand"`
	LayoutID                            int32 `gorm:"column:LayoutId" json:"LayoutId"`
}

// TableName StockSetting's table name
func (*StockSetting) TableName() string {
	return TableNameStockSetting
}
