// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockValueReportItem = "StockValueReportItem"

// StockValueReportItem mapped from table <StockValueReportItem>
type StockValueReportItem struct {
	ID              int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	StockID         int32   `gorm:"column:StockId;not null" json:"StockId"`
	StockLocationID int32   `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Quantity        float64 `gorm:"column:Quantity;not null;default:0.0000" json:"Quantity"`
	AverageCost     float64 `gorm:"column:AverageCost;not null;default:0.0000" json:"AverageCost"`
	Value           float64 `gorm:"column:Value;not null;default:0.0000" json:"Value"`
	Owner           string  `gorm:"column:Owner;not null" json:"Owner"`
}

// TableName StockValueReportItem's table name
func (*StockValueReportItem) TableName() string {
	return TableNameStockValueReportItem
}
