// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockUpdateLogging = "StockUpdateLogging"

// StockUpdateLogging mapped from table <StockUpdateLogging>
type StockUpdateLogging struct {
	Step                     string    `gorm:"column:Step;not null" json:"Step"`
	SubStep                  string    `gorm:"column:SubStep;not null" json:"SubStep"`
	StockAdjustmentID        int32     `gorm:"column:StockAdjustmentId;not null" json:"StockAdjustmentId"`
	UserID                   int32     `gorm:"column:UserId" json:"UserId"`
	StockLocationStockTakeID int32     `gorm:"column:StockLocationStockTakeId" json:"StockLocationStockTakeId"`
	PricebookID              int32     `gorm:"column:PricebookId;not null" json:"PricebookId"`
	StockLocationID          int32     `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Quantity                 float64   `gorm:"column:Quantity;not null" json:"Quantity"`
	UnitCost                 float64   `gorm:"column:UnitCost" json:"UnitCost"`
	Updates                  string    `gorm:"column:Updates;not null" json:"Updates"`
	UpdateTime               time.Time `gorm:"column:UpdateTime;not null" json:"UpdateTime"`
}

// TableName StockUpdateLogging's table name
func (*StockUpdateLogging) TableName() string {
	return TableNameStockUpdateLogging
}
