// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStocktakeItem = "StocktakeItems"

// StocktakeItem mapped from table <StocktakeItems>
type StocktakeItem struct {
	StocktakeItemID          int32   `gorm:"column:StocktakeItemId;primaryKey;autoIncrement:true" json:"StocktakeItemId"`
	StockLocationStockTakeID int32   `gorm:"column:StockLocationStockTakeId;not null" json:"StockLocationStockTakeId"`
	PricebookID              int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	OnHand                   float64 `gorm:"column:OnHand;not null" json:"OnHand"`
	Count                    float64 `gorm:"column:Count;not null" json:"Count"`
	AverageCost              float64 `gorm:"column:AverageCost;not null" json:"AverageCost"`
	Variance                 float64 `gorm:"column:Variance;not null" json:"Variance"`
	Reason                   string  `gorm:"column:Reason;not null" json:"Reason"`
}

// TableName StocktakeItem's table name
func (*StocktakeItem) TableName() string {
	return TableNameStocktakeItem
}
