// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockLocation = "StockLocations"

// StockLocation mapped from table <StockLocations>
type StockLocation struct {
	StockLocationID  int32     `gorm:"column:StockLocationId;primaryKey;autoIncrement:true" json:"StockLocationId"`
	Code             string    `gorm:"column:Code;not null" json:"Code"`
	Description      string    `gorm:"column:Description;not null" json:"Description"`
	Reference        string    `gorm:"column:Reference;not null" json:"Reference"`
	Room             string    `gorm:"column:Room;not null" json:"Room"`
	DoNotUse         bool      `gorm:"column:DoNotUse;not null" json:"DoNotUse"`
	Shelf            string    `gorm:"column:Shelf;not null" json:"Shelf"`
	Bin              string    `gorm:"column:Bin;not null" json:"Bin"`
	EraID            int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa            time.Time `gorm:"column:Circa;not null" json:"Circa"`
	LastStocktake    time.Time `gorm:"column:LastStocktake" json:"LastStocktake"`
	VehicleID        int32     `gorm:"column:VehicleId" json:"VehicleId"`
	PhysicalLocation string    `gorm:"column:PhysicalLocation;not null" json:"PhysicalLocation"`
	DataVersion      int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	AddressID        int32     `gorm:"column:AddressId" json:"AddressId"`
}

// TableName StockLocation's table name
func (*StockLocation) TableName() string {
	return TableNameStockLocation
}
