// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockMovementText = "StockMovementText"

// StockMovementText mapped from table <StockMovementText>
type StockMovementText struct {
	StockMovementTextID    int32  `gorm:"column:StockMovementTextId;primaryKey" json:"StockMovementTextId"`
	FromJobsList           string `gorm:"column:FromJobsList;not null" json:"FromJobsList"`
	ToJobsList             string `gorm:"column:ToJobsList;not null" json:"ToJobsList"`
	FromStockLocationsList string `gorm:"column:FromStockLocationsList;not null" json:"FromStockLocationsList"`
	ToStockLocationsList   string `gorm:"column:ToStockLocationsList;not null" json:"ToStockLocationsList"`
	PricebookList          string `gorm:"column:PricebookList;not null" json:"PricebookList"`
}

// TableName StockMovementText's table name
func (*StockMovementText) TableName() string {
	return TableNameStockMovementText
}
