// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockText = "StockText"

// StockText mapped from table <StockText>
type StockText struct {
	StockTextID        int32  `gorm:"column:StockTextId;primaryKey" json:"StockTextId"`
	StockLocationsList string `gorm:"column:StockLocationsList;not null" json:"StockLocationsList"`
}

// TableName StockText's table name
func (*StockText) TableName() string {
	return TableNameStockText
}
