// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockPackage = "StockPackages"

// StockPackage mapped from table <StockPackages>
type StockPackage struct {
	StockPackageID int32   `gorm:"column:StockPackageId;primaryKey;autoIncrement:true" json:"StockPackageId"`
	StockID        int32   `gorm:"column:StockId;not null" json:"StockId"`
	PackageID      int32   `gorm:"column:PackageId;not null" json:"PackageId"`
	Quantity       float64 `gorm:"column:Quantity;not null" json:"Quantity"`
}

// TableName StockPackage's table name
func (*StockPackage) TableName() string {
	return TableNameStockPackage
}
