// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockLedgerTransaction = "StockLedgerTransaction"

// StockLedgerTransaction mapped from table <StockLedgerTransaction>
type StockLedgerTransaction struct {
	ID          int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	StockID     int32     `gorm:"column:StockId;not null" json:"StockId"`
	Source      int32     `gorm:"column:Source;not null" json:"Source"`
	SourceID    int32     `gorm:"column:SourceId;not null" json:"SourceId"`
	SourceNo    string    `gorm:"column:SourceNo;not null" json:"SourceNo"`
	Date        time.Time `gorm:"column:Date;not null" json:"Date"`
	Ref         string    `gorm:"column:Ref;not null" json:"Ref"`
	ReferenceID int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	ReferenceNo string    `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	Details     string    `gorm:"column:Details;not null" json:"Details"`
	Ordered     float64   `gorm:"column:Ordered" json:"Ordered"`
	Received    float64   `gorm:"column:Received" json:"Received"`
	Used        float64   `gorm:"column:Used" json:"Used"`
}

// TableName StockLedgerTransaction's table name
func (*StockLedgerTransaction) TableName() string {
	return TableNameStockLedgerTransaction
}
