// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockMovementItem = "StockMovementItems"

// StockMovementItem mapped from table <StockMovementItems>
type StockMovementItem struct {
	StockMovementItemID int32   `gorm:"column:StockMovementItemId;primaryKey;autoIncrement:true" json:"StockMovementItemId"`
	StockMovementID     int32   `gorm:"column:StockMovementId;not null" json:"StockMovementId"`
	RowID               int32   `gorm:"column:RowId;not null" json:"RowId"`
	PricebookID         int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	Quantity            float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                float64 `gorm:"column:Cost;not null" json:"Cost"`
	FromJobID           int32   `gorm:"column:FromJobId" json:"FromJobId"`
	ToJobID             int32   `gorm:"column:ToJobId" json:"ToJobId"`
	FromStockLocationID int32   `gorm:"column:FromStockLocationId" json:"FromStockLocationId"`
	ToStockLocationID   int32   `gorm:"column:ToStockLocationId" json:"ToStockLocationId"`
	ToCostCentreID      int32   `gorm:"column:ToCostCentreId" json:"ToCostCentreId"`
	FromCostCentreID    int32   `gorm:"column:FromCostCentreId" json:"FromCostCentreId"`
}

// TableName StockMovementItem's table name
func (*StockMovementItem) TableName() string {
	return TableNameStockMovementItem
}
