// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStockLocationOpeningItem = "StockLocationOpeningItems"

// StockLocationOpeningItem mapped from table <StockLocationOpeningItems>
type StockLocationOpeningItem struct {
	StockLocationOpeningItemID int32   `gorm:"column:StockLocationOpeningItemId;primaryKey;autoIncrement:true" json:"StockLocationOpeningItemId"`
	PricebookID                int32   `gorm:"column:PricebookId;not null" json:"PricebookId"`
	StockLocationID            int32   `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	RowID                      int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity                   float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                       float64 `gorm:"column:Cost;not null" json:"Cost"`
}

// TableName StockLocationOpeningItem's table name
func (*StockLocationOpeningItem) TableName() string {
	return TableNameStockLocationOpeningItem
}
