// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockAdjustmentItem = "StockAdjustmentItem"

// StockAdjustmentItem mapped from table <StockAdjustmentItem>
type StockAdjustmentItem struct {
	StockAdjustmentItemID int32     `gorm:"column:StockAdjustmentItemId;primaryKey;autoIncrement:true" json:"StockAdjustmentItemId"`
	StockID               int32     `gorm:"column:StockId;not null" json:"StockId"`
	StockLocationID       int32     `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Date                  time.Time `gorm:"column:Date;not null" json:"Date"`
	Quantity              float64   `gorm:"column:Quantity;not null" json:"Quantity"`
	AverageCost           float64   `gorm:"column:AverageCost;not null" json:"AverageCost"`
	Reference             string    `gorm:"column:Reference;not null" json:"Reference"`
}

// TableName StockAdjustmentItem's table name
func (*StockAdjustmentItem) TableName() string {
	return TableNameStockAdjustmentItem
}
