// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockMovement = "StockMovement"

// StockMovement mapped from table <StockMovement>
type StockMovement struct {
	StockMovementID int32     `gorm:"column:StockMovementId;primaryKey;autoIncrement:true" json:"StockMovementId"`
	MovementNo      string    `gorm:"column:MovementNo;not null" json:"MovementNo"`
	Date            time.Time `gorm:"column:Date;not null" json:"Date"`
	Reference       string    `gorm:"column:Reference;not null" json:"Reference"`
	FromJobNo       string    `gorm:"column:FromJobNo" json:"FromJobNo"`
	ToJobNo         string    `gorm:"column:ToJobNo" json:"ToJobNo"`
	FromLocCode     string    `gorm:"column:FromLocCode" json:"FromLocCode"`
	ToLocCode       string    `gorm:"column:ToLocCode" json:"ToLocCode"`
	PricebookList   string    `gorm:"column:PricebookList" json:"PricebookList"`
	LayoutID        int32     `gorm:"column:LayoutId" json:"LayoutId"`
	EraID           int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Circa           time.Time `gorm:"column:Circa" json:"Circa"`
	DataVersion     int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName StockMovement's table name
func (*StockMovement) TableName() string {
	return TableNameStockMovement
}
