// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockLocationStockTake = "StockLocationStockTakes"

// StockLocationStockTake mapped from table <StockLocationStockTakes>
type StockLocationStockTake struct {
	StockLocationStockTakeID int32     `gorm:"column:StockLocationStockTakeId;primaryKey;autoIncrement:true" json:"StockLocationStockTakeId"`
	StockLocationID          int32     `gorm:"column:StockLocationId;not null" json:"StockLocationId"`
	Date                     time.Time `gorm:"column:Date;not null" json:"Date"`
	Details                  string    `gorm:"column:Details;not null" json:"Details"`
	Replenishment            float64   `gorm:"column:Replenishment;not null" json:"Replenishment"`
	Consumption              float64   `gorm:"column:Consumption;not null" json:"Consumption"`
	Adjustments              float64   `gorm:"column:Adjustments;not null" json:"Adjustments"`
	Status                   string    `gorm:"column:Status;not null" json:"Status"`
	Circa                    time.Time `gorm:"column:Circa;not null" json:"Circa"`
	EraID                    int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion              int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName StockLocationStockTake's table name
func (*StockLocationStockTake) TableName() string {
	return TableNameStockLocationStockTake
}
