// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStockLedger = "StockLedger"

// StockLedger mapped from table <StockLedger>
type StockLedger struct {
	ID             int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	StockID        int32     `gorm:"column:StockId;not null" json:"StockId"`
	LedgerDate     time.Time `gorm:"column:LedgerDate;not null" json:"LedgerDate"`
	ReferenceID    int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	Ref            string    `gorm:"column:Ref;not null" json:"Ref"`
	ReferenceNo    string    `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	Details        string    `gorm:"column:Details;not null" json:"Details"`
	Ordered        float64   `gorm:"column:Ordered" json:"Ordered"`
	Received       float64   `gorm:"column:Received" json:"Received"`
	Used           float64   `gorm:"column:Used" json:"Used"`
	OnHand         float64   `gorm:"column:OnHand" json:"OnHand"`
	Opening        float64   `gorm:"column:Opening" json:"Opening"`
	BalanceOnOrder float64   `gorm:"column:BalanceOnOrder" json:"BalanceOnOrder"`
	Owner          int32     `gorm:"column:Owner;not null" json:"Owner"`
}

// TableName StockLedger's table name
func (*StockLedger) TableName() string {
	return TableNameStockLedger
}
