// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameStock = "Stock"

// Stock mapped from table <Stock>
type Stock struct {
	StockID             int32     `gorm:"column:StockId;primaryKey" json:"StockId"`
	LastCost            float64   `gorm:"column:LastCost" json:"LastCost"`
	OpeningBalance      float64   `gorm:"column:OpeningBalance" json:"OpeningBalance"`
	PreferredLocationID int32     `gorm:"column:PreferredLocationId" json:"PreferredLocationId"`
	StockAdjustments    float64   `gorm:"column:StockAdjustments" json:"StockAdjustments"`
	Circa               time.Time `gorm:"column:Circa;not null" json:"Circa"`
	StockLocationCode   string    `gorm:"column:StockLocationCode" json:"StockLocationCode"`
	EraID               int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion         int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Stock's table name
func (*Stock) TableName() string {
	return TableNameStock
}
