// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSubcontractorBatchPaymentContraItem = "SubcontractorBatchPaymentContraItem"

// SubcontractorBatchPaymentContraItem mapped from table <SubcontractorBatchPaymentContraItem>
type SubcontractorBatchPaymentContraItem struct {
	SubcontractorBatchPaymentContraItemID int32 `gorm:"column:SubcontractorBatchPaymentContraItemId;primaryKey;autoIncrement:true" json:"SubcontractorBatchPaymentContraItemId"`
	SubcontractorBatchPaymentID           int32 `gorm:"column:SubcontractorBatchPaymentId;not null" json:"SubcontractorBatchPaymentId"`
	PaymentID                             int32 `gorm:"column:PaymentId" json:"PaymentId"`
	InvoiceID                             int32 `gorm:"column:InvoiceId" json:"InvoiceId"`
	ReceiptID                             int32 `gorm:"column:ReceiptId" json:"ReceiptId"`
}

// TableName SubcontractorBatchPaymentContraItem's table name
func (*SubcontractorBatchPaymentContraItem) TableName() string {
	return TableNameSubcontractorBatchPaymentContraItem
}
