// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSubcontractorBatchPayment = "SubcontractorBatchPayment"

// SubcontractorBatchPayment mapped from table <SubcontractorBatchPayment>
type SubcontractorBatchPayment struct {
	SubcontractorBatchPaymentID int32 `gorm:"column:SubcontractorBatchPaymentId;primaryKey" json:"SubcontractorBatchPaymentId"`
	BatchPaymentID              int32 `gorm:"column:BatchPaymentId;not null" json:"BatchPaymentId"`
}

// TableName SubcontractorBatchPayment's table name
func (*SubcontractorBatchPayment) TableName() string {
	return TableNameSubcontractorBatchPayment
}
