// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSupplier = "Suppliers"

// Supplier mapped from table <Suppliers>
type Supplier struct {
	SupplierID                  int32     `gorm:"column:SupplierId;primaryKey;autoIncrement:true" json:"SupplierId"`
	Code                        string    `gorm:"column:Code;not null" json:"Code"`
	Name                        string    `gorm:"column:Name;not null" json:"Name"`
	PhoneID                     int32     `gorm:"column:PhoneId" json:"PhoneId"`
	FaxID                       int32     `gorm:"column:FaxId" json:"FaxId"`
	TradingTerms                string    `gorm:"column:TradingTerms;not null" json:"TradingTerms"`
	TradingDays                 int32     `gorm:"column:TradingDays;not null" json:"TradingDays"`
	Email                       string    `gorm:"column:Email" json:"Email"`
	SupplierSince               time.Time `gorm:"column:SupplierSince" json:"SupplierSince"`
	ABN                         string    `gorm:"column:ABN;not null" json:"ABN"`
	Active                      bool      `gorm:"column:Active;not null" json:"Active"`
	Website                     string    `gorm:"column:Website" json:"Website"`
	SubcontractorFlag           bool      `gorm:"column:SubcontractorFlag;not null" json:"SubcontractorFlag"`
	OpeningBalance              float64   `gorm:"column:OpeningBalance;not null" json:"OpeningBalance"`
	CodeName                    string    `gorm:"column:CodeName;not null" json:"CodeName"`
	BusinessNatureCode          string    `gorm:"column:BusinessNatureCode" json:"BusinessNatureCode"`
	Circa                       time.Time `gorm:"column:Circa;not null" json:"Circa"`
	UpdateCounter               int32     `gorm:"column:UpdateCounter;not null" json:"UpdateCounter"`
	VendorNo                    string    `gorm:"column:VendorNo" json:"VendorNo"`
	OnHold                      bool      `gorm:"column:OnHold" json:"OnHold"`
	BankID                      int32     `gorm:"column:BankId" json:"BankId"`
	AccountNo                   string    `gorm:"column:AccountNo" json:"AccountNo"`
	AccountName                 string    `gorm:"column:AccountName" json:"AccountName"`
	InputGSTInclusive           bool      `gorm:"column:InputGSTInclusive" json:"InputGSTInclusive"`
	MinimumOrderValue           float64   `gorm:"column:MinimumOrderValue" json:"MinimumOrderValue"`
	BatchChangeMerge            int32     `gorm:"column:BatchChangeMerge" json:"BatchChangeMerge"`
	BatchNewCode                string    `gorm:"column:BatchNewCode" json:"BatchNewCode"`
	PaymentMethodID             int32     `gorm:"column:PaymentMethodId" json:"PaymentMethodId"`
	AccountID                   int32     `gorm:"column:AccountId" json:"AccountId"`
	DivisionID                  int32     `gorm:"column:DivisionId" json:"DivisionId"`
	EraID                       int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	Owing                       float64   `gorm:"column:Owing;not null;default:0.00" json:"Owing"`
	DataVersion                 int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	BatchPaymentReference       int32     `gorm:"column:BatchPaymentReference;not null;default:1" json:"BatchPaymentReference"`
	BatchPaymentReferencePrefix string    `gorm:"column:BatchPaymentReferencePrefix" json:"BatchPaymentReferencePrefix"`
	PurchaseGSTMethod           int32     `gorm:"column:PurchaseGSTMethod;not null" json:"PurchaseGSTMethod"`
	AddressID                   int32     `gorm:"column:AddressId;not null" json:"AddressId"`
	PostalAddressID             int32     `gorm:"column:PostalAddressId;not null" json:"PostalAddressId"`
	InvoiceEmails               string    `gorm:"column:InvoiceEmails" json:"InvoiceEmails"`
}

// TableName Supplier's table name
func (*Supplier) TableName() string {
	return TableNameSupplier
}
