// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSupplierLicence = "SupplierLicences"

// SupplierLicence mapped from table <SupplierLicences>
type SupplierLicence struct {
	SupplierLicenceID int32     `gorm:"column:SupplierLicenceId;primaryKey;autoIncrement:true" json:"SupplierLicenceId"`
	SupplierID        int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	LicenceID         int32     `gorm:"column:LicenceId;not null" json:"LicenceId"`
	LicenceNo         string    `gorm:"column:LicenceNo" json:"LicenceNo"`
	Details           string    `gorm:"column:Details;not null" json:"Details"`
	Expiry            time.Time `gorm:"column:Expiry;not null" json:"Expiry"`
}

// TableName SupplierLicence's table name
func (*SupplierLicence) TableName() string {
	return TableNameSupplierLicence
}
