// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSupplierInsurance = "SupplierInsurances"

// SupplierInsurance mapped from table <SupplierInsurances>
type SupplierInsurance struct {
	SupplierInsuranceID int32     `gorm:"column:SupplierInsuranceId;primaryKey;autoIncrement:true" json:"SupplierInsuranceId"`
	InsuranceID         int32     `gorm:"column:InsuranceId;not null" json:"InsuranceId"`
	SupplierID          int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	Policy              string    `gorm:"column:Policy;not null" json:"Policy"`
	Insurer             string    `gorm:"column:Insurer;not null" json:"Insurer"`
	Details             string    `gorm:"column:Details;not null" json:"Details"`
	Expiry              time.Time `gorm:"column:Expiry;not null" json:"Expiry"`
}

// TableName SupplierInsurance's table name
func (*SupplierInsurance) TableName() string {
	return TableNameSupplierInsurance
}
