// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSuppliersBusinessNature = "SuppliersBusinessNature"

// SuppliersBusinessNature mapped from table <SuppliersBusinessNature>
type SuppliersBusinessNature struct {
	SuppliersBusinessNatureID int32 `gorm:"column:SuppliersBusinessNatureId;primaryKey;autoIncrement:true" json:"SuppliersBusinessNatureId"`
	SupplierID                int32 `gorm:"column:SupplierId;not null" json:"SupplierId"`
	BusinessNatureID          int32 `gorm:"column:BusinessNatureId;not null" json:"BusinessNatureId"`
}

// TableName SuppliersBusinessNature's table name
func (*SuppliersBusinessNature) TableName() string {
	return TableNameSuppliersBusinessNature
}
