// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSupplierSetting = "SupplierSettings"

// SupplierSetting mapped from table <SupplierSettings>
type SupplierSetting struct {
	SupplierSettingID                        int32  `gorm:"column:SupplierSettingId;primaryKey" json:"SupplierSettingId"`
	TermsType                                string `gorm:"column:TermsType;not null" json:"TermsType"`
	TermsDays                                int32  `gorm:"column:TermsDays;not null" json:"TermsDays"`
	FromEmailAccountID                       int32  `gorm:"column:FromEmailAccountId" json:"FromEmailAccountId"`
	PaymentMessageTemplateID                 int32  `gorm:"column:PaymentMessageTemplateId" json:"PaymentMessageTemplateId"`
	RemittanceLayoutID                       int32  `gorm:"column:RemittanceLayoutId" json:"RemittanceLayoutId"`
	AbaBankAccountID                         int32  `gorm:"column:AbaBankAccountId" json:"AbaBankAccountId"`
	PricebookStandardCostUpdateOption        string `gorm:"column:PricebookStandardCostUpdateOption;not null" json:"PricebookStandardCostUpdateOption"`
	PricebookSupplierProductCostUpdateOption string `gorm:"column:PricebookSupplierProductCostUpdateOption;not null" json:"PricebookSupplierProductCostUpdateOption"`
}

// TableName SupplierSetting's table name
func (*SupplierSetting) TableName() string {
	return TableNameSupplierSetting
}
