// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSuppliersLedgerReport = "SuppliersLedgerReport"

// SuppliersLedgerReport mapped from table <SuppliersLedgerReport>
type SuppliersLedgerReport struct {
	ID           int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	SupplierID   int32     `gorm:"column:SupplierId;not null" json:"SupplierId"`
	Type         string    `gorm:"column:Type;not null" json:"Type"`
	ReferenceNo  string    `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	ReferenceID  int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	Date         time.Time `gorm:"column:Date;not null" json:"Date"`
	Details      string    `gorm:"column:Details;not null" json:"Details"`
	DebitAmount  float64   `gorm:"column:DebitAmount;not null;default:0.00" json:"DebitAmount"`
	CreditAmount float64   `gorm:"column:CreditAmount;not null;default:0.00" json:"CreditAmount"`
	Balance      float64   `gorm:"column:Balance;not null;default:0.00" json:"Balance"`
	Owner        string    `gorm:"column:Owner;not null" json:"Owner"`
	OrderID      int32     `gorm:"column:OrderId;not null" json:"OrderId"`
}

// TableName SuppliersLedgerReport's table name
func (*SuppliersLedgerReport) TableName() string {
	return TableNameSuppliersLedgerReport
}
