// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTableCounter = "TableCounters"

// TableCounter mapped from table <TableCounters>
type TableCounter struct {
	TableCounterID int32  `gorm:"column:TableCounterId;primaryKey;autoIncrement:true" json:"TableCounterId"`
	TableName_     string `gorm:"column:TableName;not null" json:"TableName"`
	SeqNo          int32  `gorm:"column:SeqNo;not null" json:"SeqNo"`
	Prefix         string `gorm:"column:Prefix;not null" json:"Prefix"`
}

// TableName TableCounter's table name
func (*TableCounter) TableName() string {
	return TableNameTableCounter
}
