// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTableLock = "TableLocks"

// TableLock mapped from table <TableLocks>
type TableLock struct {
	TableLockID int32     `gorm:"column:TableLockId;primaryKey;autoIncrement:true" json:"TableLockId"`
	TableName_  string    `gorm:"column:TableName;not null" json:"TableName"`
	Sequence    string    `gorm:"column:Sequence;not null" json:"Sequence"`
	UserID      int32     `gorm:"column:UserId;not null" json:"UserId"`
	LockedAt    time.Time `gorm:"column:LockedAt;not null" json:"LockedAt"`
}

// TableName TableLock's table name
func (*TableLock) TableName() string {
	return TableNameTableLock
}
