// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTimesheet = "Timesheets"

// Timesheet mapped from table <Timesheets>
type Timesheet struct {
	TimesheetID int32     `gorm:"column:TimesheetId;primaryKey;autoIncrement:true" json:"TimesheetId"`
	EmployeeID  int32     `gorm:"column:EmployeeId;not null" json:"EmployeeId"`
	Date        time.Time `gorm:"column:Date;not null" json:"Date"`
	JobNo       string    `gorm:"column:JobNo" json:"JobNo"`
	StartTime   string    `gorm:"column:StartTime" json:"StartTime"`
	FinishTime  string    `gorm:"column:FinishTime" json:"FinishTime"`
	Duration    float64   `gorm:"column:Duration;not null" json:"Duration"`
	Hours       float64   `gorm:"column:Hours" json:"Hours"`
	EraID       int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	DataVersion int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	PayrollID   int32     `gorm:"column:PayrollId" json:"PayrollId"`
}

// TableName Timesheet's table name
func (*Timesheet) TableName() string {
	return TableNameTimesheet
}
