// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTimesheetsText = "TimesheetsText"

// TimesheetsText mapped from table <TimesheetsText>
type TimesheetsText struct {
	TimesheetsTextID int32  `gorm:"column:TimesheetsTextId;primaryKey" json:"TimesheetsTextId"`
	JobsList         string `gorm:"column:JobsList;not null" json:"JobsList"`
}

// TableName TimesheetsText's table name
func (*TimesheetsText) TableName() string {
	return TableNameTimesheetsText
}
