// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTimesheetAllowance = "TimesheetAllowances"

// TimesheetAllowance mapped from table <TimesheetAllowances>
type TimesheetAllowance struct {
	TimesheetAllowancesID int32   `gorm:"column:TimesheetAllowancesId;primaryKey;autoIncrement:true" json:"TimesheetAllowancesId"`
	TimesheetID           int32   `gorm:"column:TimesheetId;not null" json:"TimesheetId"`
	PayrollAllowanceID    int32   `gorm:"column:PayrollAllowanceId;not null" json:"PayrollAllowanceId"`
	RowID                 int32   `gorm:"column:RowId;not null" json:"RowId"`
	Quantity              float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Reference             string  `gorm:"column:Reference;not null" json:"Reference"`
	Cost                  float64 `gorm:"column:Cost;not null" json:"Cost"`
	PayrollUnitID         int32   `gorm:"column:PayrollUnitId" json:"PayrollUnitId"`
	JobID                 int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID          int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
}

// TableName TimesheetAllowance's table name
func (*TimesheetAllowance) TableName() string {
	return TableNameTimesheetAllowance
}
