// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTimesheetSetting = "TimesheetSettings"

// TimesheetSetting mapped from table <TimesheetSettings>
type TimesheetSetting struct {
	TimesheetSettingID   int32  `gorm:"column:TimesheetSettingId;primaryKey" json:"TimesheetSettingId"`
	PostZeroHoursToJobs  bool   `gorm:"column:PostZeroHoursToJobs;not null" json:"PostZeroHoursToJobs"`
	LicenceExpiryWarning bool   `gorm:"column:LicenceExpiryWarning;not null" json:"LicenceExpiryWarning"`
	LicenceExpiryWeeks   int32  `gorm:"column:LicenceExpiryWeeks;not null" json:"LicenceExpiryWeeks"`
	UseTaskDetails       bool   `gorm:"column:UseTaskDetails;not null" json:"UseTaskDetails"`
	JobFinishedWarning   bool   `gorm:"column:JobFinishedWarning;not null" json:"JobFinishedWarning"`
	UseLinkedAward       bool   `gorm:"column:UseLinkedAward;not null" json:"UseLinkedAward"`
	UsualStartTime       string `gorm:"column:UsualStartTime" json:"UsualStartTime"`
}

// TableName TimesheetSetting's table name
func (*TimesheetSetting) TableName() string {
	return TableNameTimesheetSetting
}
