// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTimesheetItem = "TimesheetItems"

// TimesheetItem mapped from table <TimesheetItems>
type TimesheetItem struct {
	TimesheetItemID     int32   `gorm:"column:TimesheetItemId;primaryKey;autoIncrement:true" json:"TimesheetItemId"`
	TimesheetID         int32   `gorm:"column:TimesheetId;not null" json:"TimesheetId"`
	RowID               int32   `gorm:"column:RowId;not null" json:"RowId"`
	LabourRateID        int32   `gorm:"column:LabourRateId;not null" json:"LabourRateId"`
	Cost                float64 `gorm:"column:Cost;not null" json:"Cost"`
	Hours               float64 `gorm:"column:Hours;not null" json:"Hours"`
	ChargeHours         float64 `gorm:"column:ChargeHours;not null" json:"ChargeHours"`
	JobID               int32   `gorm:"column:JobId" json:"JobId"`
	CostCentreID        int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
	PayrollTimeTypeID   int32   `gorm:"column:PayrollTimeTypeId" json:"PayrollTimeTypeId"`
	StartTime           string  `gorm:"column:StartTime" json:"StartTime"`
	FinishTime          string  `gorm:"column:FinishTime" json:"FinishTime"`
	ServiceID           int32   `gorm:"column:ServiceId" json:"ServiceId"`
	ServiceIncludeHours float64 `gorm:"column:ServiceIncludeHours" json:"ServiceIncludeHours"`
	Description         string  `gorm:"column:Description;not null" json:"Description"`
}

// TableName TimesheetItem's table name
func (*TimesheetItem) TableName() string {
	return TableNameTimesheetItem
}
