// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTitle = "Titles"

// Title mapped from table <Titles>
type Title struct {
	TitleID int32  `gorm:"column:TitleId;primaryKey;autoIncrement:true" json:"TitleId"`
	Code    string `gorm:"column:Code;not null" json:"Code"`
}

// TableName Title's table name
func (*Title) TableName() string {
	return TableNameTitle
}
