// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTradingTerm = "TradingTerms"

// TradingTerm mapped from table <TradingTerms>
type TradingTerm struct {
	TradingTermID int32  `gorm:"column:TradingTermId;primaryKey;autoIncrement:true" json:"TradingTermId"`
	Code          string `gorm:"column:Code;not null" json:"Code"`
	Description   string `gorm:"column:Description;not null" json:"Description"`
	Days          int32  `gorm:"column:Days;not null" json:"Days"`
	Type          string `gorm:"column:Type;not null" json:"Type"`
	Obsolete      bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName TradingTerm's table name
func (*TradingTerm) TableName() string {
	return TableNameTradingTerm
}
