// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTransaction = "Transactions"

// Transaction mapped from table <Transactions>
type Transaction struct {
	TransactionID              int32     `gorm:"column:TransactionId;primaryKey;autoIncrement:true" json:"TransactionId"`
	TransNo                    int32     `gorm:"column:TransNo;not null" json:"TransNo"`
	Date                       time.Time `gorm:"column:Date;not null" json:"Date"`
	Amount                     float64   `gorm:"column:Amount;not null" json:"Amount"`
	GSTType                    string    `gorm:"column:GSTType" json:"GSTType"`
	GSTAmount                  float64   `gorm:"column:GSTAmount;not null" json:"GSTAmount"`
	Reference                  string    `gorm:"column:Reference;not null" json:"Reference"`
	Type                       string    `gorm:"column:Type;not null" json:"Type"`
	For                        string    `gorm:"column:For;not null" json:"For"`
	ForABA                     bool      `gorm:"column:ForABA;not null" json:"ForABA"`
	ReversingJournalID         int32     `gorm:"column:ReversingJournalId" json:"ReversingJournalId"`
	Details                    string    `gorm:"column:Details;not null" json:"Details"`
	LayoutID                   int32     `gorm:"column:LayoutId" json:"LayoutId"`
	ClientID                   int32     `gorm:"column:ClientId" json:"ClientId"`
	SupplierID                 int32     `gorm:"column:SupplierId" json:"SupplierId"`
	PayrollsHeaderID           int32     `gorm:"column:PayrollsHeaderId" json:"PayrollsHeaderId"`
	EmployeeID                 int32     `gorm:"column:EmployeeId" json:"EmployeeId"`
	CreditAccount              string    `gorm:"column:CreditAccount" json:"CreditAccount"`
	DebitAccount               string    `gorm:"column:DebitAccount" json:"DebitAccount"`
	EraID                      int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	PaymentMethodType          string    `gorm:"column:PaymentMethodType" json:"PaymentMethodType"`
	SurchargeRate              float64   `gorm:"column:SurchargeRate;not null;default:0.0000" json:"SurchargeRate"`
	TransactionReceiptDetailID int32     `gorm:"column:TransactionReceiptDetailId" json:"TransactionReceiptDetailId"`
	DataVersion                int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
