// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTransactionPosting = "TransactionPostings"

// TransactionPosting mapped from table <TransactionPostings>
type TransactionPosting struct {
	TransactionPostingID int32     `gorm:"column:TransactionPostingId;primaryKey;autoIncrement:true" json:"TransactionPostingId"`
	TransactionID        int32     `gorm:"column:TransactionId;not null" json:"TransactionId"`
	Amount               float64   `gorm:"column:Amount;not null" json:"Amount"`
	DebitAccountID       int32     `gorm:"column:DebitAccountId;not null" json:"DebitAccountId"`
	CreditAccountID      int32     `gorm:"column:CreditAccountId;not null" json:"CreditAccountId"`
	GSTType              string    `gorm:"column:GSTType;not null" json:"GSTType"`
	GSTAmount            float64   `gorm:"column:GSTAmount;not null" json:"GSTAmount"`
	InvoiceID            int32     `gorm:"column:InvoiceId" json:"InvoiceId"`
	PurchaseID           int32     `gorm:"column:PurchaseId" json:"PurchaseId"`
	BasID                int32     `gorm:"column:BasId" json:"BasId"`
	PayrollID            int32     `gorm:"column:PayrollId" json:"PayrollId"`
	DebitDivisionID      int32     `gorm:"column:DebitDivisionId" json:"DebitDivisionId"`
	CreditDivisionID     int32     `gorm:"column:CreditDivisionId" json:"CreditDivisionId"`
	JournalReference     string    `gorm:"column:JournalReference;not null" json:"JournalReference"`
	GstDebitAccountID    int32     `gorm:"column:GstDebitAccountId" json:"GstDebitAccountId"`
	GstCreditAccountID   int32     `gorm:"column:GstCreditAccountId" json:"GstCreditAccountId"`
	DebitDateBanked      time.Time `gorm:"column:DebitDateBanked" json:"DebitDateBanked"`
	CreditDateBanked     time.Time `gorm:"column:CreditDateBanked" json:"CreditDateBanked"`
	DebitStatementRowNo  int32     `gorm:"column:DebitStatementRowNo" json:"DebitStatementRowNo"`
	CreditStatementRowNo int32     `gorm:"column:CreditStatementRowNo" json:"CreditStatementRowNo"`
	RowID                int32     `gorm:"column:RowId;not null" json:"RowId"`
}

// TableName TransactionPosting's table name
func (*TransactionPosting) TableName() string {
	return TableNameTransactionPosting
}
