// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransactionReceiptDetail = "TransactionReceiptDetails"

// TransactionReceiptDetail mapped from table <TransactionReceiptDetails>
type TransactionReceiptDetail struct {
	TransactionReceiptDetailID int32  `gorm:"column:TransactionReceiptDetailId;primaryKey;autoIncrement:true" json:"TransactionReceiptDetailId"`
	BankID                     int32  `gorm:"column:BankId" json:"BankId"`
	AccountNo                  string `gorm:"column:AccountNo;not null" json:"AccountNo"`
	ChequeNo                   string `gorm:"column:ChequeNo" json:"ChequeNo"`
	AccountName                string `gorm:"column:AccountName;not null;comment:Account No and Account Name are used for both Cheques and Credit Card to record the bank account number/credit card number and account name and the name on the credit card respectively" json:"AccountName"` // Account No and Account Name are used for both Cheques and Credit Card to record the bank account number/credit card number and account name and the name on the credit card respectively
	CardID                     int32  `gorm:"column:CardId" json:"CardId"`
	CCV                        string `gorm:"column:CCV" json:"CCV"`
	Expiry                     string `gorm:"column:Expiry" json:"Expiry"`
}

// TableName TransactionReceiptDetail's table name
func (*TransactionReceiptDetail) TableName() string {
	return TableNameTransactionReceiptDetail
}
