// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransactionJobCost = "TransactionJobCosts"

// TransactionJobCost mapped from table <TransactionJobCosts>
type TransactionJobCost struct {
	TransactionJobCostID int32   `gorm:"column:TransactionJobCostId;primaryKey;autoIncrement:true" json:"TransactionJobCostId"`
	TransactionID        int32   `gorm:"column:TransactionId;not null" json:"TransactionId"`
	JobID                int32   `gorm:"column:JobId;not null" json:"JobId"`
	RowID                int32   `gorm:"column:RowId;not null" json:"RowId"`
	Reference            string  `gorm:"column:Reference;not null" json:"Reference"`
	Description          string  `gorm:"column:Description;not null" json:"Description"`
	Quantity             float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost                 float64 `gorm:"column:Cost;not null" json:"Cost"`
	PricebookID          int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID         int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	CostCentreID         int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
}

// TableName TransactionJobCost's table name
func (*TransactionJobCost) TableName() string {
	return TableNameTransactionJobCost
}
