// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTransactionSummary = "TransactionSummary"

// TransactionSummary mapped from table <TransactionSummary>
type TransactionSummary struct {
	ID          int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Scope       string    `gorm:"column:Scope;not null" json:"Scope"`
	Owner       string    `gorm:"column:Owner;not null" json:"Owner"`
	AccountID   int32     `gorm:"column:AccountId;not null" json:"AccountId"`
	Type        string    `gorm:"column:Type;not null" json:"Type"`
	ReferenceID int32     `gorm:"column:ReferenceId;not null" json:"ReferenceId"`
	ReferenceNo string    `gorm:"column:ReferenceNo;not null" json:"ReferenceNo"`
	For         string    `gorm:"column:For;not null" json:"For"`
	Date        time.Time `gorm:"column:Date;not null" json:"Date"`
	Details     string    `gorm:"column:Details" json:"Details"`
	Debit       float64   `gorm:"column:Debit;not null;default:0.00" json:"Debit"`
	Credit      float64   `gorm:"column:Credit;not null;default:0.00" json:"Credit"`
}

// TableName TransactionSummary's table name
func (*TransactionSummary) TableName() string {
	return TableNameTransactionSummary
}
