// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransactionsText = "TransactionsText"

// TransactionsText mapped from table <TransactionsText>
type TransactionsText struct {
	TransactionsTextID int32  `gorm:"column:TransactionsTextId;primaryKey" json:"TransactionsTextId"`
	CreditAccountList  string `gorm:"column:CreditAccountList;not null" json:"CreditAccountList"`
	DebitAccountList   string `gorm:"column:DebitAccountList;not null" json:"DebitAccountList"`
}

// TableName TransactionsText's table name
func (*TransactionsText) TableName() string {
	return TableNameTransactionsText
}
