// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransactionCashPosting = "TransactionCashPostings"

// TransactionCashPosting mapped from table <TransactionCashPostings>
type TransactionCashPosting struct {
	ID                 int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	TransactionID      int32   `gorm:"column:TransactionId;not null" json:"TransactionId"`
	AccountID          int32   `gorm:"column:AccountId;not null" json:"AccountId"`
	DivisionID         int32   `gorm:"column:DivisionId" json:"DivisionId"`
	CashFlowActivityID int32   `gorm:"column:CashFlowActivityId;not null" json:"CashFlowActivityId"`
	RowID              int32   `gorm:"column:RowId;not null" json:"RowId"`
	Amount             float64 `gorm:"column:Amount;not null" json:"Amount"`
}

// TableName TransactionCashPosting's table name
func (*TransactionCashPosting) TableName() string {
	return TableNameTransactionCashPosting
}
