// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUnit = "Units"

// Unit mapped from table <Units>
type Unit struct {
	UnitID      int32  `gorm:"column:UnitId;primaryKey;autoIncrement:true" json:"UnitId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
	DataVersion int32  `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
}

// TableName Unit's table name
func (*Unit) TableName() string {
	return TableNameUnit
}
