// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserEmailAccount = "UserEmailAccount"

// UserEmailAccount mapped from table <UserEmailAccount>
type UserEmailAccount struct {
	ID             int32 `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	EmailAccountID int32 `gorm:"column:EmailAccountId;not null" json:"EmailAccountId"`
	UserID         int32 `gorm:"column:UserId;not null" json:"UserId"`
	Default        bool  `gorm:"column:Default;not null" json:"Default"`
}

// TableName UserEmailAccount's table name
func (*UserEmailAccount) TableName() string {
	return TableNameUserEmailAccount
}
