// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	ID                          int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Provider                    string    `gorm:"column:Provider;not null" json:"Provider"`
	ExternalID                  string    `gorm:"column:ExternalId" json:"ExternalId"`
	UserName                    string    `gorm:"column:UserName;not null" json:"UserName"`
	FirstName                   string    `gorm:"column:FirstName" json:"FirstName"`
	LastName                    string    `gorm:"column:LastName" json:"LastName"`
	Email                       string    `gorm:"column:Email;not null" json:"Email"`
	Mobile                      string    `gorm:"column:Mobile" json:"Mobile"`
	Timeout                     int32     `gorm:"column:Timeout" json:"Timeout"`
	SysAdmin                    bool      `gorm:"column:SysAdmin;not null" json:"SysAdmin"`
	Competence                  string    `gorm:"column:Competence;not null;default:0" json:"Competence"`
	Nature                      string    `gorm:"column:Nature;not null" json:"Nature"`
	EmployeeID                  int32     `gorm:"column:EmployeeId" json:"EmployeeId"`
	ABN                         string    `gorm:"column:ABN" json:"ABN"`
	PasswordHash                string    `gorm:"column:PasswordHash" json:"PasswordHash"`
	PasswordCreatedAt           time.Time `gorm:"column:PasswordCreatedAt" json:"PasswordCreatedAt"`
	PasswordResetToken          string    `gorm:"column:PasswordResetToken" json:"PasswordResetToken"`
	PasswordResetTokenCreatedAt time.Time `gorm:"column:PasswordResetTokenCreatedAt" json:"PasswordResetTokenCreatedAt"`
	OneTimePasswordHash         string    `gorm:"column:OneTimePasswordHash" json:"OneTimePasswordHash"`
	OneTimePasswordCreatedAt    time.Time `gorm:"column:OneTimePasswordCreatedAt" json:"OneTimePasswordCreatedAt"`
	SecurityStamp               string    `gorm:"column:SecurityStamp" json:"SecurityStamp"`
	TwoFactorEnabled            bool      `gorm:"column:TwoFactorEnabled;not null" json:"TwoFactorEnabled"`
	TwoFactorDeviceEnabled      bool      `gorm:"column:TwoFactorDeviceEnabled;not null" json:"TwoFactorDeviceEnabled"`
	TwoFactorSecretKey          string    `gorm:"column:TwoFactorSecretKey" json:"TwoFactorSecretKey"`
	AccessLockoutAt             time.Time `gorm:"column:AccessLockoutAt" json:"AccessLockoutAt"`
	AccessFailedCount           int32     `gorm:"column:AccessFailedCount" json:"AccessFailedCount"`
	Deactivated                 bool      `gorm:"column:Deactivated;not null" json:"Deactivated"`
	LastIPAddress               string    `gorm:"column:LastIpAddress" json:"LastIpAddress"`
	LastGeoCode                 string    `gorm:"column:LastGeoCode" json:"LastGeoCode"`
	LastLogin                   time.Time `gorm:"column:LastLogin" json:"LastLogin"`
	LastActivity                time.Time `gorm:"column:LastActivity" json:"LastActivity"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
