// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserRole = "UserRoles"

// UserRole mapped from table <UserRoles>
type UserRole struct {
	UserID int32 `gorm:"column:UserId;primaryKey" json:"UserId"`
	RoleID int32 `gorm:"column:RoleId;primaryKey" json:"RoleId"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
