// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserSTPProfile = "UserSTPProfile"

// UserSTPProfile mapped from table <UserSTPProfile>
type UserSTPProfile struct {
	ID           int32  `gorm:"column:Id;primaryKey" json:"Id"`
	SSIDNotified bool   `gorm:"column:SSIDNotified;not null" json:"SSIDNotified"`
	ContactName  string `gorm:"column:ContactName;not null" json:"ContactName"`
	ContactEmail string `gorm:"column:ContactEmail;not null" json:"ContactEmail"`
}

// TableName UserSTPProfile's table name
func (*UserSTPProfile) TableName() string {
	return TableNameUserSTPProfile
}
