// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserUISetting = "UserUiSettings"

// UserUISetting mapped from table <UserUiSettings>
type UserUISetting struct {
	ID                     int32 `gorm:"column:Id;primaryKey" json:"Id"`
	PageLeftJustified      bool  `gorm:"column:PageLeftJustified;not null" json:"PageLeftJustified"`
	DisableGridEditMessage bool  `gorm:"column:DisableGridEditMessage;not null" json:"DisableGridEditMessage"`
	ProjectAdmin           bool  `gorm:"column:ProjectAdmin;not null" json:"ProjectAdmin"`
	AccountAdmin           bool  `gorm:"column:AccountAdmin;not null" json:"AccountAdmin"`
	PayrollAdmin           bool  `gorm:"column:PayrollAdmin;not null" json:"PayrollAdmin"`
	BusinessOwner          bool  `gorm:"column:BusinessOwner;not null" json:"BusinessOwner"`
}

// TableName UserUISetting's table name
func (*UserUISetting) TableName() string {
	return TableNameUserUISetting
}
