// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserApproveLimit = "UserApproveLimits"

// UserApproveLimit mapped from table <UserApproveLimits>
type UserApproveLimit struct {
	ID     int32   `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	UserID int32   `gorm:"column:UserId;not null" json:"UserId"`
	Form   string  `gorm:"column:Form;not null" json:"Form"`
	Min    float64 `gorm:"column:Min;not null" json:"Min"`
	Max    float64 `gorm:"column:Max;not null" json:"Max"`
}

// TableName UserApproveLimit's table name
func (*UserApproveLimit) TableName() string {
	return TableNameUserApproveLimit
}
