// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserSignature = "UserSignature"

// UserSignature mapped from table <UserSignature>
type UserSignature struct {
	UserSignatureID int32 `gorm:"column:UserSignatureId;primaryKey;autoIncrement:true" json:"UserSignatureId"`
	UserID          int32 `gorm:"column:UserId" json:"UserId"`
	SignatureID     int32 `gorm:"column:SignatureId;not null" json:"SignatureId"`
	EmailAccountID  int32 `gorm:"column:EmailAccountId" json:"EmailAccountId"`
}

// TableName UserSignature's table name
func (*UserSignature) TableName() string {
	return TableNameUserSignature
}
