// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserSetting = "UserSettings"

// UserSetting mapped from table <UserSettings>
type UserSetting struct {
	ID               int32  `gorm:"column:Id;primaryKey" json:"Id"`
	RecentReports    string `gorm:"column:RecentReports" json:"RecentReports"`
	FavouriteReports string `gorm:"column:FavouriteReports" json:"FavouriteReports"`
	Preference       string `gorm:"column:Preference" json:"Preference"`
}

// TableName UserSetting's table name
func (*UserSetting) TableName() string {
	return TableNameUserSetting
}
