// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameVariationsText = "VariationsText"

// VariationsText mapped from table <VariationsText>
type VariationsText struct {
	VariationsTextID int32  `gorm:"column:VariationsTextId;primaryKey;autoIncrement:true" json:"VariationsTextId"`
	Details          string `gorm:"column:Details;not null" json:"Details"`
	Clause1          string `gorm:"column:Clause1;not null" json:"Clause1"`
	Clause2          string `gorm:"column:Clause2;not null" json:"Clause2"`
	Clause3          string `gorm:"column:Clause3;not null" json:"Clause3"`
}

// TableName VariationsText's table name
func (*VariationsText) TableName() string {
	return TableNameVariationsText
}
