// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameVariation = "Variations"

// Variation mapped from table <Variations>
type Variation struct {
	VariationID     int32     `gorm:"column:VariationId;primaryKey;autoIncrement:true" json:"VariationId"`
	ProjectID       int32     `gorm:"column:ProjectId;not null" json:"ProjectId"`
	ClientID        int32     `gorm:"column:ClientId;not null" json:"ClientId"`
	VariationNo     int32     `gorm:"column:VariationNo;not null" json:"VariationNo"`
	Date            time.Time `gorm:"column:Date;not null" json:"Date"`
	Type            string    `gorm:"column:Type;not null" json:"Type"`
	Reference       string    `gorm:"column:Reference;not null" json:"Reference"`
	Claim           float64   `gorm:"column:Claim;not null" json:"Claim"`
	Cost            float64   `gorm:"column:Cost;not null" json:"Cost"`
	LayoutID        int32     `gorm:"column:LayoutId;not null" json:"LayoutId"`
	ApprovedDate    time.Time `gorm:"column:ApprovedDate" json:"ApprovedDate"`
	ApprovedAmount  float64   `gorm:"column:ApprovedAmount;not null" json:"ApprovedAmount"`
	Summary         string    `gorm:"column:Summary;not null" json:"Summary"`
	PricingBasis    string    `gorm:"column:PricingBasis;not null" json:"PricingBasis"`
	VariationTextID int32     `gorm:"column:VariationTextId" json:"VariationTextId"`
	InDispute       bool      `gorm:"column:InDispute;not null" json:"InDispute"`
	DataVersion     int32     `gorm:"column:DataVersion;not null;default:1" json:"DataVersion"`
	EraID           int32     `gorm:"column:EraId;not null;default:1" json:"EraId"`
	SupplierID      int32     `gorm:"column:SupplierId" json:"SupplierId"`
}

// TableName Variation's table name
func (*Variation) TableName() string {
	return TableNameVariation
}
