// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameVariationsItem = "VariationsItems"

// VariationsItem mapped from table <VariationsItems>
type VariationsItem struct {
	VariationsItemID int32   `gorm:"column:VariationsItemId;primaryKey;autoIncrement:true" json:"VariationsItemId"`
	VariationID      int32   `gorm:"column:VariationId;not null" json:"VariationId"`
	RowID            int32   `gorm:"column:RowId;not null" json:"RowId"`
	Description      string  `gorm:"column:Description;not null" json:"Description"`
	Quantity         float64 `gorm:"column:Quantity;not null" json:"Quantity"`
	Cost             float64 `gorm:"column:Cost;not null" json:"Cost"`
	MaterialsCost    float64 `gorm:"column:MaterialsCost;not null" json:"MaterialsCost"`
	LabourCost       float64 `gorm:"column:LabourCost;not null" json:"LabourCost"`
	Hours            float64 `gorm:"column:Hours;not null;default:0.0000" json:"Hours"`
	Claimed          float64 `gorm:"column:Claimed;not null;default:0.00" json:"Claimed"`
	Reference        string  `gorm:"column:Reference;not null" json:"Reference"`
	PricebookID      int32   `gorm:"column:PricebookId" json:"PricebookId"`
	LabourRateID     int32   `gorm:"column:LabourRateId" json:"LabourRateId"`
	AssemblyID       int32   `gorm:"column:AssemblyId" json:"AssemblyId"`
	CostCentreID     int32   `gorm:"column:CostCentreId" json:"CostCentreId"`
}

// TableName VariationsItem's table name
func (*VariationsItem) TableName() string {
	return TableNameVariationsItem
}
