// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameVehicle = "Vehicles"

// Vehicle mapped from table <Vehicles>
type Vehicle struct {
	VehicleID   int32     `gorm:"column:VehicleId;primaryKey;autoIncrement:true" json:"VehicleId"`
	Code        string    `gorm:"column:Code;not null" json:"Code"`
	Description string    `gorm:"column:Description;not null" json:"Description"`
	RegNo       string    `gorm:"column:RegNo;not null" json:"RegNo"`
	RegExpiry   time.Time `gorm:"column:RegExpiry" json:"RegExpiry"`
	Obsolete    bool      `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName Vehicle's table name
func (*Vehicle) TableName() string {
	return TableNameVehicle
}
