// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWarranty = "Warranty"

// Warranty mapped from table <Warranty>
type Warranty struct {
	WarrantyID      int32     `gorm:"column:WarrantyId;primaryKey;autoIncrement:true" json:"WarrantyId"`
	Brand           string    `gorm:"column:Brand;not null" json:"Brand"`
	Appliance       string    `gorm:"column:Appliance;not null" json:"Appliance"`
	ModelNo         string    `gorm:"column:ModelNo;not null" json:"ModelNo"`
	DateOfPurchase  time.Time `gorm:"column:DateOfPurchase" json:"DateOfPurchase"`
	PlaceOfPurchase string    `gorm:"column:PlaceOfPurchase;not null" json:"PlaceOfPurchase"`
	WarrantyPeriod  int32     `gorm:"column:WarrantyPeriod;not null" json:"WarrantyPeriod"`
	Expires         time.Time `gorm:"column:Expires" json:"Expires"`
	Notes           string    `gorm:"column:Notes;not null" json:"Notes"`
}

// TableName Warranty's table name
func (*Warranty) TableName() string {
	return TableNameWarranty
}
