// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWorkInProgressReport = "WorkInProgressReport"

// WorkInProgressReport mapped from table <WorkInProgressReport>
type WorkInProgressReport struct {
	ID                 int32     `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	JobID              int32     `gorm:"column:JobId;not null" json:"JobId"`
	JobNo              string    `gorm:"column:JobNo;not null" json:"JobNo"`
	ClientCode         string    `gorm:"column:ClientCode;not null" json:"ClientCode"`
	JobDesc            string    `gorm:"column:JobDesc;not null" json:"JobDesc"`
	ReportJobHours     float64   `gorm:"column:ReportJobHours;default:0.0000" json:"ReportJobHours"`
	ReportJobLabour    float64   `gorm:"column:ReportJobLabour;default:0.0000" json:"ReportJobLabour"`
	ReportJobMaterials float64   `gorm:"column:ReportJobMaterials;default:0.0000" json:"ReportJobMaterials"`
	ReportJobStock     float64   `gorm:"column:ReportJobStock;default:0.0000" json:"ReportJobStock"`
	ReportJobOnOrder   float64   `gorm:"column:ReportJobOnOrder;default:0.0000" json:"ReportJobOnOrder"`
	ReportJobTotal     float64   `gorm:"column:ReportJobTotal;default:0.0000" json:"ReportJobTotal"`
	InvoicedAsAt       time.Time `gorm:"column:InvoicedAsAt" json:"InvoicedAsAt"`
	JobTypeCode        string    `gorm:"column:JobTypeCode" json:"JobTypeCode"`
	JobFinishDate      time.Time `gorm:"column:JobFinishDate" json:"JobFinishDate"`
	SupervisorCode     string    `gorm:"column:SupervisorCode" json:"SupervisorCode"`
	JobStatusCode      string    `gorm:"column:JobStatusCode" json:"JobStatusCode"`
	Owner              string    `gorm:"column:Owner;not null" json:"Owner"`
}

// TableName WorkInProgressReport's table name
func (*WorkInProgressReport) TableName() string {
	return TableNameWorkInProgressReport
}
