// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameWorkRequired = "WorkRequired"

// WorkRequired mapped from table <WorkRequired>
type WorkRequired struct {
	WorkRequiredID int32   `gorm:"column:WorkRequiredId;primaryKey;autoIncrement:true" json:"WorkRequiredId"`
	Code           string  `gorm:"column:Code;not null" json:"Code"`
	Description    string  `gorm:"column:Description;not null" json:"Description"`
	TimeAllowed    float64 `gorm:"column:TimeAllowed" json:"TimeAllowed"`
	Obsolete       bool    `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName WorkRequired's table name
func (*WorkRequired) TableName() string {
	return TableNameWorkRequired
}
