// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameWorkSite = "WorkSites"

// WorkSite mapped from table <WorkSites>
type WorkSite struct {
	WorkSiteID  int32  `gorm:"column:WorkSiteId;primaryKey;autoIncrement:true" json:"WorkSiteId"`
	Code        string `gorm:"column:Code;not null" json:"Code"`
	Description string `gorm:"column:Description;not null" json:"Description"`
	Obsolete    bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName WorkSite's table name
func (*WorkSite) TableName() string {
	return TableNameWorkSite
}
