// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameXContact = "XContacts"

// XContact mapped from table <XContacts>
type XContact struct {
	XContactID int32  `gorm:"column:XContactId;primaryKey;autoIncrement:true" json:"XContactId"`
	ClientID   int32  `gorm:"column:ClientId" json:"ClientId"`
	JobID      int32  `gorm:"column:JobId" json:"JobId"`
	SupplierID int32  `gorm:"column:SupplierId" json:"SupplierId"`
	RowID      int32  `gorm:"column:RowId;not null" json:"RowId"`
	Title      string `gorm:"column:Title" json:"Title"`
	Position   string `gorm:"column:Position" json:"Position"`
	FirstName  string `gorm:"column:FirstName" json:"FirstName"`
	Surname    string `gorm:"column:Surname" json:"Surname"`
	Phone      string `gorm:"column:Phone" json:"Phone"`
	Email      string `gorm:"column:Email" json:"Email"`
	Obsolete   bool   `gorm:"column:Obsolete;not null" json:"Obsolete"`
}

// TableName XContact's table name
func (*XContact) TableName() string {
	return TableNameXContact
}
