// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameXContactEmailPreference = "XContactEmailPreferences"

// XContactEmailPreference mapped from table <XContactEmailPreferences>
type XContactEmailPreference struct {
	ID         int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	XContactID int32  `gorm:"column:XContactId;not null" json:"XContactId"`
	RowID      int32  `gorm:"column:RowId;not null" json:"RowId"`
	Address    string `gorm:"column:Address;not null" json:"Address"`
	FormType   string `gorm:"column:FormType;not null" json:"FormType"`
}

// TableName XContactEmailPreference's table name
func (*XContactEmailPreference) TableName() string {
	return TableNameXContactEmailPreference
}
